// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2018.2
// Copyright (C) 1986-2018 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module Filter2D_1 (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        p_src_data_stream_0_V_dout,
        p_src_data_stream_0_V_empty_n,
        p_src_data_stream_0_V_read,
        p_src_data_stream_1_V_dout,
        p_src_data_stream_1_V_empty_n,
        p_src_data_stream_1_V_read,
        p_src_data_stream_2_V_dout,
        p_src_data_stream_2_V_empty_n,
        p_src_data_stream_2_V_read,
        p_dst_data_stream_0_V_din,
        p_dst_data_stream_0_V_full_n,
        p_dst_data_stream_0_V_write,
        p_dst_data_stream_1_V_din,
        p_dst_data_stream_1_V_full_n,
        p_dst_data_stream_1_V_write,
        p_dst_data_stream_2_V_din,
        p_dst_data_stream_2_V_full_n,
        p_dst_data_stream_2_V_write
);

parameter    ap_ST_fsm_state1 = 5'd1;
parameter    ap_ST_fsm_state2 = 5'd2;
parameter    ap_ST_fsm_state3 = 5'd4;
parameter    ap_ST_fsm_pp0_stage0 = 5'd8;
parameter    ap_ST_fsm_state10 = 5'd16;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
input  [7:0] p_src_data_stream_0_V_dout;
input   p_src_data_stream_0_V_empty_n;
output   p_src_data_stream_0_V_read;
input  [7:0] p_src_data_stream_1_V_dout;
input   p_src_data_stream_1_V_empty_n;
output   p_src_data_stream_1_V_read;
input  [7:0] p_src_data_stream_2_V_dout;
input   p_src_data_stream_2_V_empty_n;
output   p_src_data_stream_2_V_read;
output  [7:0] p_dst_data_stream_0_V_din;
input   p_dst_data_stream_0_V_full_n;
output   p_dst_data_stream_0_V_write;
output  [7:0] p_dst_data_stream_1_V_din;
input   p_dst_data_stream_1_V_full_n;
output   p_dst_data_stream_1_V_write;
output  [7:0] p_dst_data_stream_2_V_din;
input   p_dst_data_stream_2_V_full_n;
output   p_dst_data_stream_2_V_write;

reg ap_done;
reg ap_idle;
reg ap_ready;
reg p_src_data_stream_0_V_read;
reg p_src_data_stream_1_V_read;
reg p_src_data_stream_2_V_read;
reg p_dst_data_stream_0_V_write;
reg p_dst_data_stream_1_V_write;
reg p_dst_data_stream_2_V_write;

(* fsm_encoding = "none" *) reg   [4:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
reg    p_src_data_stream_0_V_blk_n;
reg    ap_enable_reg_pp0_iter2;
wire    ap_block_pp0_stage0;
reg   [0:0] exitcond389_i_reg_3006;
reg   [0:0] exitcond389_i_reg_3006_pp0_iter1_reg;
reg   [0:0] or_cond_i_i_reg_3015;
reg   [0:0] or_cond_i_i_reg_3015_pp0_iter1_reg;
reg   [0:0] icmp_reg_2959;
reg   [0:0] tmp_34_reg_2950;
reg    p_src_data_stream_1_V_blk_n;
reg    p_src_data_stream_2_V_blk_n;
reg    p_dst_data_stream_0_V_blk_n;
reg    ap_enable_reg_pp0_iter5;
reg   [0:0] or_cond_i_reg_3042;
reg   [0:0] or_cond_i_reg_3042_pp0_iter4_reg;
reg    p_dst_data_stream_1_V_blk_n;
reg    p_dst_data_stream_2_V_blk_n;
reg   [10:0] t_V_3_reg_610;
wire   [1:0] tmp_31_fu_621_p2;
wire    ap_CS_fsm_state2;
wire   [0:0] exitcond390_i_fu_637_p2;
wire    ap_CS_fsm_state3;
wire   [10:0] i_V_fu_643_p2;
reg   [10:0] i_V_reg_2945;
wire   [0:0] tmp_34_fu_649_p2;
wire   [0:0] tmp_528_0_0_not_fu_655_p2;
reg   [0:0] tmp_528_0_0_not_reg_2954;
wire   [0:0] icmp_fu_671_p2;
wire   [0:0] tmp_35_fu_677_p2;
reg   [0:0] tmp_35_reg_2964;
wire   [0:0] tmp_572_0_1_fu_683_p2;
reg   [0:0] tmp_572_0_1_reg_2968;
wire   [0:0] tmp_36_fu_689_p2;
reg   [0:0] tmp_36_reg_2972;
wire   [1:0] row_assign_13_0_0_t_fu_879_p2;
reg   [1:0] row_assign_13_0_0_t_reg_2985;
wire   [1:0] row_assign_13_0_1_t_fu_899_p2;
reg   [1:0] row_assign_13_0_1_t_reg_2992;
wire   [1:0] row_assign_13_0_2_t_fu_919_p2;
reg   [1:0] row_assign_13_0_2_t_reg_2999;
wire   [0:0] exitcond389_i_fu_929_p2;
wire    ap_CS_fsm_pp0_stage0;
wire    ap_block_state4_pp0_stage0_iter0;
wire    ap_block_state5_pp0_stage0_iter1;
reg    ap_predicate_op215_read_state6;
reg    ap_predicate_op227_read_state6;
reg    ap_predicate_op260_read_state6;
reg    ap_predicate_op272_read_state6;
reg    ap_predicate_op302_read_state6;
reg    ap_predicate_op311_read_state6;
reg    ap_block_state6_pp0_stage0_iter2;
wire    ap_block_state7_pp0_stage0_iter3;
wire    ap_block_state8_pp0_stage0_iter4;
reg    ap_block_state9_pp0_stage0_iter5;
reg    ap_block_pp0_stage0_11001;
reg   [0:0] exitcond389_i_reg_3006_pp0_iter2_reg;
wire   [10:0] j_V_fu_935_p2;
reg    ap_enable_reg_pp0_iter0;
wire   [0:0] or_cond_i_i_fu_987_p2;
wire  signed [13:0] x_fu_1039_p3;
reg  signed [13:0] x_reg_3019;
wire   [1:0] tmp_108_fu_1047_p1;
reg   [1:0] tmp_108_reg_3024;
reg   [1:0] tmp_108_reg_3024_pp0_iter1_reg;
wire   [0:0] brmerge_fu_1051_p2;
reg   [0:0] brmerge_reg_3029;
reg   [0:0] brmerge_reg_3029_pp0_iter1_reg;
wire   [0:0] or_cond_i_fu_1056_p2;
reg   [0:0] or_cond_i_reg_3042_pp0_iter1_reg;
reg   [0:0] or_cond_i_reg_3042_pp0_iter2_reg;
reg   [0:0] or_cond_i_reg_3042_pp0_iter3_reg;
reg   [10:0] k_buf_0_val_3_addr_reg_3046;
reg   [10:0] k_buf_0_val_4_addr_reg_3052;
reg   [10:0] k_buf_0_val_5_addr_reg_3058;
reg   [10:0] k_buf_1_val_3_addr_reg_3064;
reg   [10:0] k_buf_1_val_4_addr_reg_3070;
reg   [10:0] k_buf_1_val_5_addr_reg_3076;
reg   [10:0] k_buf_2_val_3_addr_reg_3082;
reg   [10:0] k_buf_2_val_4_addr_reg_3088;
reg   [10:0] k_buf_2_val_5_addr_reg_3094;
wire   [7:0] src_kernel_win_0_va_6_fu_1216_p3;
reg   [7:0] src_kernel_win_0_va_6_reg_3100;
reg   [7:0] src_kernel_win_0_va_6_reg_3100_pp0_iter3_reg;
wire   [7:0] src_kernel_win_0_va_7_fu_1234_p3;
reg   [7:0] src_kernel_win_0_va_7_reg_3106;
wire   [7:0] src_kernel_win_0_va_8_fu_1252_p3;
reg   [7:0] src_kernel_win_0_va_8_reg_3112;
wire   [20:0] r_V_10_0_1_1_fu_2603_p2;
reg   [20:0] r_V_10_0_1_1_reg_3118;
wire   [7:0] src_kernel_win_1_va_6_fu_1391_p3;
reg   [7:0] src_kernel_win_1_va_6_reg_3123;
reg   [7:0] src_kernel_win_1_va_6_reg_3123_pp0_iter3_reg;
wire   [7:0] src_kernel_win_1_va_7_fu_1409_p3;
reg   [7:0] src_kernel_win_1_va_7_reg_3129;
wire   [7:0] src_kernel_win_1_va_8_fu_1427_p3;
reg   [7:0] src_kernel_win_1_va_8_reg_3135;
wire   [20:0] r_V_10_1_1_1_fu_2609_p2;
reg   [20:0] r_V_10_1_1_1_reg_3141;
wire   [7:0] src_kernel_win_2_va_9_fu_1548_p3;
reg   [7:0] src_kernel_win_2_va_9_reg_3146;
reg   [7:0] src_kernel_win_2_va_9_reg_3146_pp0_iter3_reg;
wire   [7:0] src_kernel_win_2_va_10_fu_1566_p3;
reg   [7:0] src_kernel_win_2_va_10_reg_3152;
wire   [7:0] src_kernel_win_2_va_11_fu_1584_p3;
reg   [7:0] src_kernel_win_2_va_11_reg_3158;
wire   [20:0] r_V_10_2_1_1_fu_2615_p2;
reg   [20:0] r_V_10_2_1_1_reg_3164;
reg   [7:0] src_kernel_win_0_va_16_reg_3169;
reg   [7:0] src_kernel_win_1_va_16_reg_3174;
reg   [7:0] src_kernel_win_2_va_7_reg_3179;
reg   [7:0] src_kernel_win_0_va_9_reg_3184;
wire   [24:0] grp_fu_2621_p4;
reg   [24:0] p_Val2_91_0_0_2_reg_3190;
reg    ap_enable_reg_pp0_iter3;
wire   [19:0] r_V_10_0_1_fu_1706_p2;
reg   [19:0] r_V_10_0_1_reg_3195;
wire   [24:0] tmp44_fu_1755_p2;
reg   [24:0] tmp44_reg_3200;
reg   [7:0] src_kernel_win_1_va_9_reg_3205;
wire   [24:0] grp_fu_2639_p4;
reg   [24:0] p_Val2_91_1_0_2_reg_3211;
wire   [19:0] r_V_10_1_1_fu_1845_p2;
reg   [19:0] r_V_10_1_1_reg_3216;
wire   [24:0] tmp60_fu_1894_p2;
reg   [24:0] tmp60_reg_3221;
reg   [7:0] src_kernel_win_2_va_12_reg_3226;
wire   [24:0] grp_fu_2657_p4;
reg   [24:0] p_Val2_91_2_0_2_reg_3232;
wire   [19:0] r_V_10_2_1_fu_1984_p2;
reg   [19:0] r_V_10_2_1_reg_3237;
wire   [24:0] tmp65_fu_2033_p2;
reg   [24:0] tmp65_reg_3242;
wire   [26:0] p_Val2_6_fu_2194_p2;
reg   [26:0] p_Val2_6_reg_3247;
reg   [7:0] p_Val2_7_reg_3252;
reg   [0:0] tmp_111_reg_3257;
reg   [4:0] tmp_58_reg_3262;
wire   [26:0] p_Val2_s_fu_2299_p2;
reg   [26:0] p_Val2_s_reg_3267;
reg   [7:0] p_Val2_9_reg_3272;
reg   [0:0] tmp_117_reg_3277;
reg   [4:0] tmp_71_reg_3282;
wire   [26:0] p_Val2_17_fu_2404_p2;
reg   [26:0] p_Val2_17_reg_3287;
reg   [7:0] p_Val2_19_reg_3292;
reg   [0:0] tmp_123_reg_3297;
reg   [4:0] tmp_80_reg_3302;
reg    ap_block_pp0_stage0_subdone;
reg    ap_enable_reg_pp0_iter1;
reg    ap_condition_pp0_exit_iter2_state6;
reg    ap_enable_reg_pp0_iter4;
wire   [10:0] k_buf_0_val_3_address0;
reg    k_buf_0_val_3_ce0;
wire   [7:0] k_buf_0_val_3_q0;
reg    k_buf_0_val_3_ce1;
reg    k_buf_0_val_3_we1;
wire   [10:0] k_buf_0_val_4_address0;
reg    k_buf_0_val_4_ce0;
wire   [7:0] k_buf_0_val_4_q0;
reg    k_buf_0_val_4_ce1;
reg    k_buf_0_val_4_we1;
reg   [7:0] k_buf_0_val_4_d1;
wire   [10:0] k_buf_0_val_5_address0;
reg    k_buf_0_val_5_ce0;
wire   [7:0] k_buf_0_val_5_q0;
reg    k_buf_0_val_5_ce1;
reg    k_buf_0_val_5_we1;
reg   [7:0] k_buf_0_val_5_d1;
wire   [10:0] k_buf_1_val_3_address0;
reg    k_buf_1_val_3_ce0;
wire   [7:0] k_buf_1_val_3_q0;
reg    k_buf_1_val_3_ce1;
reg    k_buf_1_val_3_we1;
wire   [10:0] k_buf_1_val_4_address0;
reg    k_buf_1_val_4_ce0;
wire   [7:0] k_buf_1_val_4_q0;
reg    k_buf_1_val_4_ce1;
reg    k_buf_1_val_4_we1;
reg   [7:0] k_buf_1_val_4_d1;
wire   [10:0] k_buf_1_val_5_address0;
reg    k_buf_1_val_5_ce0;
wire   [7:0] k_buf_1_val_5_q0;
reg    k_buf_1_val_5_ce1;
reg    k_buf_1_val_5_we1;
reg   [7:0] k_buf_1_val_5_d1;
wire   [10:0] k_buf_2_val_3_address0;
reg    k_buf_2_val_3_ce0;
wire   [7:0] k_buf_2_val_3_q0;
reg    k_buf_2_val_3_ce1;
reg    k_buf_2_val_3_we1;
wire   [10:0] k_buf_2_val_4_address0;
reg    k_buf_2_val_4_ce0;
wire   [7:0] k_buf_2_val_4_q0;
reg    k_buf_2_val_4_ce1;
reg    k_buf_2_val_4_we1;
reg   [7:0] k_buf_2_val_4_d1;
wire   [10:0] k_buf_2_val_5_address0;
reg    k_buf_2_val_5_ce0;
wire   [7:0] k_buf_2_val_5_q0;
reg    k_buf_2_val_5_ce1;
reg    k_buf_2_val_5_we1;
reg   [7:0] k_buf_2_val_5_d1;
reg   [1:0] tmp_s_reg_588;
wire   [0:0] tmp_32_fu_627_p2;
reg   [10:0] t_V_reg_599;
wire    ap_CS_fsm_state10;
wire   [63:0] tmp_51_fu_1064_p1;
reg    ap_block_pp0_stage0_01001;
reg   [7:0] src_kernel_win_0_va_fu_246;
reg   [7:0] src_kernel_win_0_va_1_fu_250;
reg   [7:0] src_kernel_win_0_va_2_fu_254;
reg   [7:0] src_kernel_win_0_va_3_fu_258;
reg   [7:0] src_kernel_win_0_va_4_fu_262;
reg   [7:0] src_kernel_win_0_va_5_fu_266;
reg   [7:0] src_kernel_win_1_va_fu_270;
reg   [7:0] src_kernel_win_1_va_1_fu_274;
reg   [7:0] src_kernel_win_1_va_2_fu_278;
reg   [7:0] src_kernel_win_1_va_3_fu_282;
reg   [7:0] src_kernel_win_1_va_4_fu_286;
reg   [7:0] src_kernel_win_1_va_5_fu_290;
reg   [7:0] src_kernel_win_2_va_fu_294;
reg   [7:0] src_kernel_win_2_va_1_fu_298;
reg   [7:0] src_kernel_win_2_va_2_fu_302;
reg   [7:0] src_kernel_win_2_va_3_fu_306;
reg   [7:0] src_kernel_win_2_va_4_fu_310;
reg   [7:0] src_kernel_win_2_va_5_fu_314;
reg   [7:0] right_border_buf_0_s_fu_318;
wire   [7:0] col_buf_0_val_0_0_fu_1121_p3;
reg   [7:0] right_border_buf_0_1_fu_322;
reg   [7:0] right_border_buf_2_s_fu_326;
reg   [7:0] right_border_buf_0_2_fu_330;
wire   [7:0] col_buf_0_val_1_0_fu_1140_p3;
reg   [7:0] right_border_buf_0_3_fu_334;
reg   [7:0] right_border_buf_2_1_fu_338;
wire   [7:0] col_buf_2_val_2_0_fu_1500_p3;
reg   [7:0] right_border_buf_0_4_fu_342;
wire   [7:0] col_buf_0_val_2_0_fu_1159_p3;
reg   [7:0] right_border_buf_0_5_fu_346;
reg   [7:0] right_border_buf_2_2_fu_350;
reg   [7:0] right_border_buf_1_s_fu_354;
wire   [7:0] col_buf_1_val_0_0_fu_1296_p3;
reg   [7:0] right_border_buf_1_1_fu_358;
reg   [7:0] right_border_buf_2_3_fu_362;
wire   [7:0] col_buf_2_val_1_0_fu_1481_p3;
reg   [7:0] right_border_buf_1_2_fu_366;
wire   [7:0] col_buf_1_val_1_0_fu_1315_p3;
reg   [7:0] right_border_buf_1_3_fu_370;
reg   [7:0] right_border_buf_2_4_fu_374;
reg   [7:0] right_border_buf_1_4_fu_378;
wire   [7:0] col_buf_1_val_2_0_fu_1334_p3;
reg   [7:0] right_border_buf_1_5_fu_382;
reg   [7:0] right_border_buf_2_5_fu_386;
wire   [7:0] col_buf_2_val_0_0_fu_1462_p3;
wire   [9:0] tmp_fu_661_p4;
wire   [11:0] t_V_cast_fu_633_p1;
wire   [11:0] tmp_38_fu_699_p2;
wire   [0:0] tmp_62_fu_705_p3;
wire   [0:0] tmp_39_fu_719_p2;
wire   [0:0] rev_fu_713_p2;
wire   [0:0] tmp_65_fu_731_p3;
wire   [11:0] p_assign_1_fu_739_p2;
wire   [11:0] p_p2_i426_i_fu_745_p3;
wire   [11:0] p_assign_14_0_1_fu_763_p2;
wire   [1:0] tmp_72_fu_785_p1;
wire   [0:0] tmp_70_fu_777_p3;
wire   [1:0] tmp_74_fu_789_p2;
wire   [1:0] tmp_83_fu_795_p1;
wire   [11:0] p_assign_14_0_2_fu_807_p2;
wire   [1:0] tmp_101_fu_829_p1;
wire   [0:0] tmp_100_fu_821_p3;
wire   [1:0] tmp_102_fu_833_p2;
wire   [1:0] tmp_103_fu_839_p1;
wire   [1:0] tmp_66_fu_759_p1;
wire   [0:0] tmp_40_fu_753_p2;
wire   [1:0] tmp_41_fu_851_p2;
wire   [1:0] tmp_61_fu_695_p1;
wire   [0:0] or_cond_i425_i_fu_725_p2;
wire   [1:0] tmp_43_fu_865_p2;
wire   [1:0] tmp_42_fu_857_p3;
wire   [1:0] tmp_44_fu_871_p3;
wire   [0:0] tmp_69_fu_769_p3;
wire   [1:0] tmp_91_fu_799_p3;
wire   [1:0] tmp_45_fu_885_p2;
wire   [1:0] tmp_46_fu_891_p3;
wire   [0:0] tmp_99_fu_813_p3;
wire   [1:0] tmp_104_fu_843_p3;
wire   [1:0] tmp_47_fu_905_p2;
wire   [1:0] tmp_48_fu_911_p3;
wire   [9:0] tmp_105_fu_941_p4;
wire   [11:0] t_V_3_cast_fu_925_p1;
wire  signed [11:0] ImagLoc_x_fu_957_p2;
wire   [0:0] tmp_106_fu_967_p3;
wire   [0:0] tmp_49_fu_981_p2;
wire   [0:0] rev1_fu_975_p2;
wire   [0:0] tmp_107_fu_993_p3;
wire   [11:0] p_assign_9_fu_1001_p2;
wire  signed [11:0] p_p2_i_i_fu_1007_p3;
wire  signed [13:0] p_p2_i_i_cast_fu_1015_p1;
wire   [0:0] tmp_50_fu_1019_p2;
wire   [13:0] p_assign_s_fu_1025_p2;
wire  signed [13:0] ImagLoc_x_cast_fu_963_p1;
wire   [13:0] p_p2_i_i_p_assign_s_fu_1031_p3;
wire   [0:0] icmp1_fu_951_p2;
wire  signed [31:0] x_cast_fu_1061_p1;
wire   [1:0] col_assign_6_0_t_fu_1104_p2;
wire   [7:0] tmp_52_fu_1109_p5;
wire   [7:0] tmp_53_fu_1128_p5;
wire   [7:0] tmp_54_fu_1147_p5;
wire   [7:0] tmp_55_fu_1205_p5;
wire   [7:0] tmp_56_fu_1223_p5;
wire   [7:0] tmp_57_fu_1241_p5;
wire   [7:0] tmp_59_fu_1284_p5;
wire   [7:0] tmp_60_fu_1303_p5;
wire   [7:0] tmp_63_fu_1322_p5;
wire   [7:0] tmp_64_fu_1380_p5;
wire   [7:0] tmp_67_fu_1398_p5;
wire   [7:0] tmp_68_fu_1416_p5;
wire   [7:0] tmp_73_fu_1450_p5;
wire   [7:0] tmp_75_fu_1469_p5;
wire   [7:0] tmp_76_fu_1488_p5;
wire   [7:0] tmp_77_fu_1537_p5;
wire   [7:0] tmp_78_fu_1555_p5;
wire   [7:0] tmp_79_fu_1573_p5;
wire   [18:0] p_shl1_fu_1641_p3;
wire   [9:0] p_shl2_fu_1653_p3;
wire   [19:0] p_shl1_cast_fu_1649_p1;
wire   [19:0] p_shl2_cast_fu_1661_p1;
wire   [19:0] r_V_10_0_0_1_fu_1665_p2;
wire  signed [23:0] r_V_10_0_0_1_cast_fu_1671_p1;
wire   [18:0] p_shl3_fu_1682_p3;
wire   [9:0] p_shl4_fu_1694_p3;
wire   [19:0] p_shl3_cast_fu_1690_p1;
wire   [19:0] p_shl4_cast_fu_1702_p1;
wire   [18:0] p_shl5_fu_1712_p3;
wire   [9:0] p_shl6_fu_1723_p3;
wire   [19:0] p_shl5_cast_fu_1719_p1;
wire   [19:0] p_shl6_cast_fu_1730_p1;
wire   [19:0] r_V_10_0_1_2_fu_1734_p2;
wire  signed [23:0] r_V_10_0_1_2_cast_fu_1740_p1;
wire   [20:0] grp_fu_2631_p3;
wire   [24:0] tmp56_cast_fu_1752_p1;
wire   [24:0] tmp_616_0_1_2_cast_c_fu_1744_p1;
wire   [18:0] p_shl8_fu_1780_p3;
wire   [9:0] p_shl9_fu_1792_p3;
wire   [19:0] p_shl8_cast_fu_1788_p1;
wire   [19:0] p_shl9_cast_fu_1800_p1;
wire   [19:0] r_V_10_1_0_1_fu_1804_p2;
wire  signed [23:0] r_V_10_1_0_1_cast_fu_1810_p1;
wire   [18:0] p_shl10_fu_1821_p3;
wire   [9:0] p_shl11_fu_1833_p3;
wire   [19:0] p_shl10_cast_fu_1829_p1;
wire   [19:0] p_shl11_cast_fu_1841_p1;
wire   [18:0] p_shl12_fu_1851_p3;
wire   [9:0] p_shl13_fu_1862_p3;
wire   [19:0] p_shl12_cast_fu_1858_p1;
wire   [19:0] p_shl13_cast_fu_1869_p1;
wire   [19:0] r_V_10_1_1_2_fu_1873_p2;
wire  signed [23:0] r_V_10_1_1_2_cast_fu_1879_p1;
wire   [20:0] grp_fu_2649_p3;
wire   [24:0] tmp61_cast_fu_1891_p1;
wire   [24:0] tmp_616_1_1_2_cast_c_fu_1883_p1;
wire   [18:0] p_shl16_fu_1919_p3;
wire   [9:0] p_shl17_fu_1931_p3;
wire   [19:0] p_shl16_cast_fu_1927_p1;
wire   [19:0] p_shl17_cast_fu_1939_p1;
wire   [19:0] r_V_10_2_0_1_fu_1943_p2;
wire  signed [23:0] r_V_10_2_0_1_cast_fu_1949_p1;
wire   [18:0] p_shl18_fu_1960_p3;
wire   [9:0] p_shl19_fu_1972_p3;
wire   [19:0] p_shl18_cast_fu_1968_p1;
wire   [19:0] p_shl19_cast_fu_1980_p1;
wire   [18:0] p_shl20_fu_1990_p3;
wire   [9:0] p_shl21_fu_2001_p3;
wire   [19:0] p_shl20_cast_fu_1997_p1;
wire   [19:0] p_shl21_cast_fu_2008_p1;
wire   [19:0] r_V_10_2_1_2_fu_2012_p2;
wire  signed [23:0] r_V_10_2_1_2_cast_fu_2018_p1;
wire   [20:0] grp_fu_2667_p3;
wire   [24:0] tmp66_cast_fu_2030_p1;
wire   [24:0] tmp_616_2_1_2_cast_c_fu_2022_p1;
wire  signed [23:0] r_V_10_0_1_cast_fu_2126_p1;
wire   [25:0] p_Val2_91_0_0_2_ca_fu_2123_p1;
wire   [25:0] tmp_616_0_1_cast_fu_2129_p1;
wire   [25:0] tmp55_cast_fu_2139_p1;
wire   [25:0] tmp42_fu_2133_p2;
wire   [25:0] p_Val2_91_0_2_fu_2142_p2;
wire   [18:0] p_shl_fu_2152_p3;
wire   [9:0] p_shl7_fu_2163_p3;
wire   [19:0] p_shl_cast_fu_2159_p1;
wire   [19:0] p_shl7_cast_fu_2170_p1;
wire   [19:0] r_V_10_0_2_1_fu_2174_p2;
wire  signed [23:0] r_V_10_0_2_1_cast_fu_2180_p1;
wire   [24:0] grp_fu_2675_p3;
wire   [26:0] tmp57_cast_fu_2191_p1;
wire   [26:0] p_Val2_91_0_2_cast_fu_2148_p1;
wire  signed [23:0] r_V_10_1_1_cast_fu_2231_p1;
wire   [25:0] p_Val2_91_1_0_2_ca_fu_2228_p1;
wire   [25:0] tmp_616_1_1_cast_fu_2234_p1;
wire   [25:0] tmp60_cast_fu_2244_p1;
wire   [25:0] tmp59_fu_2238_p2;
wire   [25:0] p_Val2_91_1_2_fu_2247_p2;
wire   [18:0] p_shl14_fu_2257_p3;
wire   [9:0] p_shl15_fu_2268_p3;
wire   [19:0] p_shl14_cast_fu_2264_p1;
wire   [19:0] p_shl15_cast_fu_2275_p1;
wire   [19:0] r_V_10_1_2_1_fu_2279_p2;
wire  signed [23:0] r_V_10_1_2_1_cast_fu_2285_p1;
wire   [24:0] grp_fu_2684_p3;
wire   [26:0] tmp62_cast_fu_2296_p1;
wire   [26:0] p_Val2_91_1_2_cast_fu_2253_p1;
wire  signed [23:0] r_V_10_2_1_cast_fu_2336_p1;
wire   [25:0] p_Val2_91_2_0_2_ca_fu_2333_p1;
wire   [25:0] tmp_616_2_1_cast_fu_2339_p1;
wire   [25:0] tmp65_cast_fu_2349_p1;
wire   [25:0] tmp64_fu_2343_p2;
wire   [25:0] p_Val2_91_2_2_fu_2352_p2;
wire   [18:0] p_shl22_fu_2362_p3;
wire   [9:0] p_shl23_fu_2373_p3;
wire   [19:0] p_shl22_cast_fu_2369_p1;
wire   [19:0] p_shl23_cast_fu_2380_p1;
wire   [19:0] r_V_10_2_2_1_fu_2384_p2;
wire  signed [23:0] r_V_10_2_2_1_cast_fu_2390_p1;
wire   [24:0] grp_fu_2693_p3;
wire   [26:0] tmp67_cast_fu_2401_p1;
wire   [26:0] p_Val2_91_2_2_cast_fu_2358_p1;
wire   [7:0] tmp_4_i_i_fu_2438_p1;
wire   [7:0] p_Val2_8_fu_2448_p2;
wire   [0:0] tmp_112_fu_2441_p3;
wire   [0:0] tmp_113_fu_2453_p3;
wire   [0:0] not_Result_4_i_i_fu_2461_p2;
wire   [0:0] Range1_all_zeros_fu_2473_p2;
wire   [0:0] carry_i_fu_2467_p2;
wire   [0:0] brmerge_i_i_not_i_i_fu_2478_p2;
wire   [7:0] tmp_4_i_i1_fu_2493_p1;
wire   [7:0] p_Val2_15_fu_2503_p2;
wire   [0:0] tmp_118_fu_2496_p3;
wire   [0:0] tmp_119_fu_2508_p3;
wire   [0:0] not_Result_4_i_i_1_fu_2516_p2;
wire   [0:0] Range1_all_zeros_2_fu_2528_p2;
wire   [0:0] carry_i1_fu_2522_p2;
wire   [0:0] brmerge_i_i_not_i_i1_fu_2533_p2;
wire   [7:0] tmp_4_i_i2_fu_2548_p1;
wire   [7:0] p_Val2_20_fu_2558_p2;
wire   [0:0] tmp_124_fu_2551_p3;
wire   [0:0] tmp_125_fu_2563_p3;
wire   [0:0] not_Result_4_i_i_2_fu_2571_p2;
wire   [0:0] Range1_all_zeros_3_fu_2583_p2;
wire   [0:0] carry_i2_fu_2577_p2;
wire   [0:0] brmerge_i_i_not_i_i2_fu_2588_p2;
wire   [7:0] r_V_10_0_1_1_fu_2603_p0;
wire   [13:0] r_V_10_0_1_1_fu_2603_p1;
wire   [7:0] r_V_10_1_1_1_fu_2609_p0;
wire   [13:0] r_V_10_1_1_1_fu_2609_p1;
wire   [7:0] r_V_10_2_1_1_fu_2615_p0;
wire   [13:0] r_V_10_2_1_1_fu_2615_p1;
wire   [7:0] grp_fu_2621_p0;
wire   [7:0] grp_fu_2621_p1;
wire   [10:0] grp_fu_2621_p2;
wire   [23:0] grp_fu_2621_p3;
wire   [7:0] grp_fu_2631_p0;
wire   [10:0] grp_fu_2631_p1;
wire   [7:0] grp_fu_2639_p0;
wire   [7:0] grp_fu_2639_p1;
wire   [10:0] grp_fu_2639_p2;
wire   [23:0] grp_fu_2639_p3;
wire   [7:0] grp_fu_2649_p0;
wire   [10:0] grp_fu_2649_p1;
wire   [7:0] grp_fu_2657_p0;
wire   [7:0] grp_fu_2657_p1;
wire   [10:0] grp_fu_2657_p2;
wire   [23:0] grp_fu_2657_p3;
wire   [7:0] grp_fu_2667_p0;
wire   [10:0] grp_fu_2667_p1;
wire   [7:0] grp_fu_2675_p0;
wire   [10:0] grp_fu_2675_p1;
wire   [23:0] grp_fu_2675_p2;
wire   [7:0] grp_fu_2684_p0;
wire   [10:0] grp_fu_2684_p1;
wire   [23:0] grp_fu_2684_p2;
wire   [7:0] grp_fu_2693_p0;
wire   [10:0] grp_fu_2693_p1;
wire   [23:0] grp_fu_2693_p2;
reg   [4:0] ap_NS_fsm;
reg    ap_idle_pp0;
wire    ap_enable_pp0;
wire   [8:0] grp_fu_2621_p00;
wire   [8:0] grp_fu_2621_p10;
wire   [24:0] grp_fu_2621_p30;
wire   [18:0] grp_fu_2631_p00;
wire   [8:0] grp_fu_2639_p00;
wire   [8:0] grp_fu_2639_p10;
wire   [24:0] grp_fu_2639_p30;
wire   [18:0] grp_fu_2649_p00;
wire   [8:0] grp_fu_2657_p00;
wire   [8:0] grp_fu_2657_p10;
wire   [24:0] grp_fu_2657_p30;
wire   [18:0] grp_fu_2667_p00;
wire   [18:0] grp_fu_2675_p00;
wire   [24:0] grp_fu_2675_p20;
wire   [18:0] grp_fu_2684_p00;
wire   [24:0] grp_fu_2684_p20;
wire   [18:0] grp_fu_2693_p00;
wire   [24:0] grp_fu_2693_p20;
wire   [20:0] r_V_10_0_1_1_fu_2603_p00;
wire   [20:0] r_V_10_1_1_1_fu_2609_p00;
wire   [20:0] r_V_10_2_1_1_fu_2615_p00;
reg    ap_condition_647;
reg    ap_condition_641;

// power-on initialization
initial begin
#0 ap_CS_fsm = 5'd1;
#0 ap_enable_reg_pp0_iter2 = 1'b0;
#0 ap_enable_reg_pp0_iter5 = 1'b0;
#0 ap_enable_reg_pp0_iter0 = 1'b0;
#0 ap_enable_reg_pp0_iter3 = 1'b0;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter4 = 1'b0;
end

Filter2D_1_k_buf_eOg #(
    .DataWidth( 8 ),
    .AddressRange( 1920 ),
    .AddressWidth( 11 ))
k_buf_0_val_3_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(k_buf_0_val_3_address0),
    .ce0(k_buf_0_val_3_ce0),
    .q0(k_buf_0_val_3_q0),
    .address1(k_buf_0_val_3_addr_reg_3046),
    .ce1(k_buf_0_val_3_ce1),
    .we1(k_buf_0_val_3_we1),
    .d1(p_src_data_stream_0_V_dout)
);

Filter2D_1_k_buf_eOg #(
    .DataWidth( 8 ),
    .AddressRange( 1920 ),
    .AddressWidth( 11 ))
k_buf_0_val_4_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(k_buf_0_val_4_address0),
    .ce0(k_buf_0_val_4_ce0),
    .q0(k_buf_0_val_4_q0),
    .address1(k_buf_0_val_4_addr_reg_3052),
    .ce1(k_buf_0_val_4_ce1),
    .we1(k_buf_0_val_4_we1),
    .d1(k_buf_0_val_4_d1)
);

Filter2D_1_k_buf_eOg #(
    .DataWidth( 8 ),
    .AddressRange( 1920 ),
    .AddressWidth( 11 ))
k_buf_0_val_5_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(k_buf_0_val_5_address0),
    .ce0(k_buf_0_val_5_ce0),
    .q0(k_buf_0_val_5_q0),
    .address1(k_buf_0_val_5_addr_reg_3058),
    .ce1(k_buf_0_val_5_ce1),
    .we1(k_buf_0_val_5_we1),
    .d1(k_buf_0_val_5_d1)
);

Filter2D_1_k_buf_eOg #(
    .DataWidth( 8 ),
    .AddressRange( 1920 ),
    .AddressWidth( 11 ))
k_buf_1_val_3_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(k_buf_1_val_3_address0),
    .ce0(k_buf_1_val_3_ce0),
    .q0(k_buf_1_val_3_q0),
    .address1(k_buf_1_val_3_addr_reg_3064),
    .ce1(k_buf_1_val_3_ce1),
    .we1(k_buf_1_val_3_we1),
    .d1(p_src_data_stream_1_V_dout)
);

Filter2D_1_k_buf_eOg #(
    .DataWidth( 8 ),
    .AddressRange( 1920 ),
    .AddressWidth( 11 ))
k_buf_1_val_4_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(k_buf_1_val_4_address0),
    .ce0(k_buf_1_val_4_ce0),
    .q0(k_buf_1_val_4_q0),
    .address1(k_buf_1_val_4_addr_reg_3070),
    .ce1(k_buf_1_val_4_ce1),
    .we1(k_buf_1_val_4_we1),
    .d1(k_buf_1_val_4_d1)
);

Filter2D_1_k_buf_eOg #(
    .DataWidth( 8 ),
    .AddressRange( 1920 ),
    .AddressWidth( 11 ))
k_buf_1_val_5_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(k_buf_1_val_5_address0),
    .ce0(k_buf_1_val_5_ce0),
    .q0(k_buf_1_val_5_q0),
    .address1(k_buf_1_val_5_addr_reg_3076),
    .ce1(k_buf_1_val_5_ce1),
    .we1(k_buf_1_val_5_we1),
    .d1(k_buf_1_val_5_d1)
);

Filter2D_1_k_buf_eOg #(
    .DataWidth( 8 ),
    .AddressRange( 1920 ),
    .AddressWidth( 11 ))
k_buf_2_val_3_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(k_buf_2_val_3_address0),
    .ce0(k_buf_2_val_3_ce0),
    .q0(k_buf_2_val_3_q0),
    .address1(k_buf_2_val_3_addr_reg_3082),
    .ce1(k_buf_2_val_3_ce1),
    .we1(k_buf_2_val_3_we1),
    .d1(p_src_data_stream_2_V_dout)
);

Filter2D_1_k_buf_eOg #(
    .DataWidth( 8 ),
    .AddressRange( 1920 ),
    .AddressWidth( 11 ))
k_buf_2_val_4_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(k_buf_2_val_4_address0),
    .ce0(k_buf_2_val_4_ce0),
    .q0(k_buf_2_val_4_q0),
    .address1(k_buf_2_val_4_addr_reg_3088),
    .ce1(k_buf_2_val_4_ce1),
    .we1(k_buf_2_val_4_we1),
    .d1(k_buf_2_val_4_d1)
);

Filter2D_1_k_buf_eOg #(
    .DataWidth( 8 ),
    .AddressRange( 1920 ),
    .AddressWidth( 11 ))
k_buf_2_val_5_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(k_buf_2_val_5_address0),
    .ce0(k_buf_2_val_5_ce0),
    .q0(k_buf_2_val_5_q0),
    .address1(k_buf_2_val_5_addr_reg_3094),
    .ce1(k_buf_2_val_5_ce1),
    .we1(k_buf_2_val_5_we1),
    .d1(k_buf_2_val_5_d1)
);

SobelFilter_mux_3ncg #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 8 ),
    .din2_WIDTH( 8 ),
    .din3_WIDTH( 2 ),
    .dout_WIDTH( 8 ))
SobelFilter_mux_3ncg_U27(
    .din0(right_border_buf_0_s_fu_318),
    .din1(right_border_buf_0_1_fu_322),
    .din2(8'd0),
    .din3(col_assign_6_0_t_fu_1104_p2),
    .dout(tmp_52_fu_1109_p5)
);

SobelFilter_mux_3ncg #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 8 ),
    .din2_WIDTH( 8 ),
    .din3_WIDTH( 2 ),
    .dout_WIDTH( 8 ))
SobelFilter_mux_3ncg_U28(
    .din0(right_border_buf_0_2_fu_330),
    .din1(right_border_buf_0_3_fu_334),
    .din2(8'd0),
    .din3(col_assign_6_0_t_fu_1104_p2),
    .dout(tmp_53_fu_1128_p5)
);

SobelFilter_mux_3ncg #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 8 ),
    .din2_WIDTH( 8 ),
    .din3_WIDTH( 2 ),
    .dout_WIDTH( 8 ))
SobelFilter_mux_3ncg_U29(
    .din0(right_border_buf_0_4_fu_342),
    .din1(right_border_buf_0_5_fu_346),
    .din2(8'd0),
    .din3(col_assign_6_0_t_fu_1104_p2),
    .dout(tmp_54_fu_1147_p5)
);

SobelFilter_mux_3ncg #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 8 ),
    .din2_WIDTH( 8 ),
    .din3_WIDTH( 2 ),
    .dout_WIDTH( 8 ))
SobelFilter_mux_3ncg_U30(
    .din0(col_buf_0_val_0_0_fu_1121_p3),
    .din1(col_buf_0_val_1_0_fu_1140_p3),
    .din2(col_buf_0_val_2_0_fu_1159_p3),
    .din3(row_assign_13_0_0_t_reg_2985),
    .dout(tmp_55_fu_1205_p5)
);

SobelFilter_mux_3ncg #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 8 ),
    .din2_WIDTH( 8 ),
    .din3_WIDTH( 2 ),
    .dout_WIDTH( 8 ))
SobelFilter_mux_3ncg_U31(
    .din0(col_buf_0_val_0_0_fu_1121_p3),
    .din1(col_buf_0_val_1_0_fu_1140_p3),
    .din2(col_buf_0_val_2_0_fu_1159_p3),
    .din3(row_assign_13_0_1_t_reg_2992),
    .dout(tmp_56_fu_1223_p5)
);

SobelFilter_mux_3ncg #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 8 ),
    .din2_WIDTH( 8 ),
    .din3_WIDTH( 2 ),
    .dout_WIDTH( 8 ))
SobelFilter_mux_3ncg_U32(
    .din0(col_buf_0_val_0_0_fu_1121_p3),
    .din1(col_buf_0_val_1_0_fu_1140_p3),
    .din2(col_buf_0_val_2_0_fu_1159_p3),
    .din3(row_assign_13_0_2_t_reg_2999),
    .dout(tmp_57_fu_1241_p5)
);

SobelFilter_mux_3ncg #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 8 ),
    .din2_WIDTH( 8 ),
    .din3_WIDTH( 2 ),
    .dout_WIDTH( 8 ))
SobelFilter_mux_3ncg_U33(
    .din0(right_border_buf_1_s_fu_354),
    .din1(right_border_buf_1_1_fu_358),
    .din2(8'd0),
    .din3(col_assign_6_0_t_fu_1104_p2),
    .dout(tmp_59_fu_1284_p5)
);

SobelFilter_mux_3ncg #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 8 ),
    .din2_WIDTH( 8 ),
    .din3_WIDTH( 2 ),
    .dout_WIDTH( 8 ))
SobelFilter_mux_3ncg_U34(
    .din0(right_border_buf_1_2_fu_366),
    .din1(right_border_buf_1_3_fu_370),
    .din2(8'd0),
    .din3(col_assign_6_0_t_fu_1104_p2),
    .dout(tmp_60_fu_1303_p5)
);

SobelFilter_mux_3ncg #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 8 ),
    .din2_WIDTH( 8 ),
    .din3_WIDTH( 2 ),
    .dout_WIDTH( 8 ))
SobelFilter_mux_3ncg_U35(
    .din0(right_border_buf_1_4_fu_378),
    .din1(right_border_buf_1_5_fu_382),
    .din2(8'd0),
    .din3(col_assign_6_0_t_fu_1104_p2),
    .dout(tmp_63_fu_1322_p5)
);

SobelFilter_mux_3ncg #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 8 ),
    .din2_WIDTH( 8 ),
    .din3_WIDTH( 2 ),
    .dout_WIDTH( 8 ))
SobelFilter_mux_3ncg_U36(
    .din0(col_buf_1_val_0_0_fu_1296_p3),
    .din1(col_buf_1_val_1_0_fu_1315_p3),
    .din2(col_buf_1_val_2_0_fu_1334_p3),
    .din3(row_assign_13_0_0_t_reg_2985),
    .dout(tmp_64_fu_1380_p5)
);

SobelFilter_mux_3ncg #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 8 ),
    .din2_WIDTH( 8 ),
    .din3_WIDTH( 2 ),
    .dout_WIDTH( 8 ))
SobelFilter_mux_3ncg_U37(
    .din0(col_buf_1_val_0_0_fu_1296_p3),
    .din1(col_buf_1_val_1_0_fu_1315_p3),
    .din2(col_buf_1_val_2_0_fu_1334_p3),
    .din3(row_assign_13_0_1_t_reg_2992),
    .dout(tmp_67_fu_1398_p5)
);

SobelFilter_mux_3ncg #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 8 ),
    .din2_WIDTH( 8 ),
    .din3_WIDTH( 2 ),
    .dout_WIDTH( 8 ))
SobelFilter_mux_3ncg_U38(
    .din0(col_buf_1_val_0_0_fu_1296_p3),
    .din1(col_buf_1_val_1_0_fu_1315_p3),
    .din2(col_buf_1_val_2_0_fu_1334_p3),
    .din3(row_assign_13_0_2_t_reg_2999),
    .dout(tmp_68_fu_1416_p5)
);

SobelFilter_mux_3ncg #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 8 ),
    .din2_WIDTH( 8 ),
    .din3_WIDTH( 2 ),
    .dout_WIDTH( 8 ))
SobelFilter_mux_3ncg_U39(
    .din0(right_border_buf_2_5_fu_386),
    .din1(right_border_buf_2_4_fu_374),
    .din2(8'd0),
    .din3(col_assign_6_0_t_fu_1104_p2),
    .dout(tmp_73_fu_1450_p5)
);

SobelFilter_mux_3ncg #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 8 ),
    .din2_WIDTH( 8 ),
    .din3_WIDTH( 2 ),
    .dout_WIDTH( 8 ))
SobelFilter_mux_3ncg_U40(
    .din0(right_border_buf_2_3_fu_362),
    .din1(right_border_buf_2_2_fu_350),
    .din2(8'd0),
    .din3(col_assign_6_0_t_fu_1104_p2),
    .dout(tmp_75_fu_1469_p5)
);

SobelFilter_mux_3ncg #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 8 ),
    .din2_WIDTH( 8 ),
    .din3_WIDTH( 2 ),
    .dout_WIDTH( 8 ))
SobelFilter_mux_3ncg_U41(
    .din0(right_border_buf_2_1_fu_338),
    .din1(right_border_buf_2_s_fu_326),
    .din2(8'd0),
    .din3(col_assign_6_0_t_fu_1104_p2),
    .dout(tmp_76_fu_1488_p5)
);

SobelFilter_mux_3ncg #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 8 ),
    .din2_WIDTH( 8 ),
    .din3_WIDTH( 2 ),
    .dout_WIDTH( 8 ))
SobelFilter_mux_3ncg_U42(
    .din0(col_buf_2_val_0_0_fu_1462_p3),
    .din1(col_buf_2_val_1_0_fu_1481_p3),
    .din2(col_buf_2_val_2_0_fu_1500_p3),
    .din3(row_assign_13_0_0_t_reg_2985),
    .dout(tmp_77_fu_1537_p5)
);

SobelFilter_mux_3ncg #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 8 ),
    .din2_WIDTH( 8 ),
    .din3_WIDTH( 2 ),
    .dout_WIDTH( 8 ))
SobelFilter_mux_3ncg_U43(
    .din0(col_buf_2_val_0_0_fu_1462_p3),
    .din1(col_buf_2_val_1_0_fu_1481_p3),
    .din2(col_buf_2_val_2_0_fu_1500_p3),
    .din3(row_assign_13_0_1_t_reg_2992),
    .dout(tmp_78_fu_1555_p5)
);

SobelFilter_mux_3ncg #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 8 ),
    .din2_WIDTH( 8 ),
    .din3_WIDTH( 2 ),
    .dout_WIDTH( 8 ))
SobelFilter_mux_3ncg_U44(
    .din0(col_buf_2_val_0_0_fu_1462_p3),
    .din1(col_buf_2_val_1_0_fu_1481_p3),
    .din2(col_buf_2_val_2_0_fu_1500_p3),
    .din3(row_assign_13_0_2_t_reg_2999),
    .dout(tmp_79_fu_1573_p5)
);

SobelFilter_mul_mocq #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 14 ),
    .dout_WIDTH( 21 ))
SobelFilter_mul_mocq_U45(
    .din0(r_V_10_0_1_1_fu_2603_p0),
    .din1(r_V_10_0_1_1_fu_2603_p1),
    .dout(r_V_10_0_1_1_fu_2603_p2)
);

SobelFilter_mul_mocq #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 14 ),
    .dout_WIDTH( 21 ))
SobelFilter_mul_mocq_U46(
    .din0(r_V_10_1_1_1_fu_2609_p0),
    .din1(r_V_10_1_1_1_fu_2609_p1),
    .dout(r_V_10_1_1_1_fu_2609_p2)
);

SobelFilter_mul_mocq #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 14 ),
    .dout_WIDTH( 21 ))
SobelFilter_mul_mocq_U47(
    .din0(r_V_10_2_1_1_fu_2615_p0),
    .din1(r_V_10_2_1_1_fu_2615_p1),
    .dout(r_V_10_2_1_1_fu_2615_p2)
);

SobelFilter_ama_apcA #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 8 ),
    .din2_WIDTH( 11 ),
    .din3_WIDTH( 24 ),
    .dout_WIDTH( 25 ))
SobelFilter_ama_apcA_U48(
    .din0(grp_fu_2621_p0),
    .din1(grp_fu_2621_p1),
    .din2(grp_fu_2621_p2),
    .din3(grp_fu_2621_p3),
    .dout(grp_fu_2621_p4)
);

SobelFilter_mac_mqcK #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 11 ),
    .din2_WIDTH( 21 ),
    .dout_WIDTH( 21 ))
SobelFilter_mac_mqcK_U49(
    .din0(grp_fu_2631_p0),
    .din1(grp_fu_2631_p1),
    .din2(r_V_10_0_1_1_reg_3118),
    .dout(grp_fu_2631_p3)
);

SobelFilter_ama_apcA #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 8 ),
    .din2_WIDTH( 11 ),
    .din3_WIDTH( 24 ),
    .dout_WIDTH( 25 ))
SobelFilter_ama_apcA_U50(
    .din0(grp_fu_2639_p0),
    .din1(grp_fu_2639_p1),
    .din2(grp_fu_2639_p2),
    .din3(grp_fu_2639_p3),
    .dout(grp_fu_2639_p4)
);

SobelFilter_mac_mqcK #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 11 ),
    .din2_WIDTH( 21 ),
    .dout_WIDTH( 21 ))
SobelFilter_mac_mqcK_U51(
    .din0(grp_fu_2649_p0),
    .din1(grp_fu_2649_p1),
    .din2(r_V_10_1_1_1_reg_3141),
    .dout(grp_fu_2649_p3)
);

SobelFilter_ama_apcA #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 8 ),
    .din2_WIDTH( 11 ),
    .din3_WIDTH( 24 ),
    .dout_WIDTH( 25 ))
SobelFilter_ama_apcA_U52(
    .din0(grp_fu_2657_p0),
    .din1(grp_fu_2657_p1),
    .din2(grp_fu_2657_p2),
    .din3(grp_fu_2657_p3),
    .dout(grp_fu_2657_p4)
);

SobelFilter_mac_mqcK #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 11 ),
    .din2_WIDTH( 21 ),
    .dout_WIDTH( 21 ))
SobelFilter_mac_mqcK_U53(
    .din0(grp_fu_2667_p0),
    .din1(grp_fu_2667_p1),
    .din2(r_V_10_2_1_1_reg_3164),
    .dout(grp_fu_2667_p3)
);

SobelFilter_mac_mrcU #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 11 ),
    .din2_WIDTH( 24 ),
    .dout_WIDTH( 25 ))
SobelFilter_mac_mrcU_U54(
    .din0(grp_fu_2675_p0),
    .din1(grp_fu_2675_p1),
    .din2(grp_fu_2675_p2),
    .dout(grp_fu_2675_p3)
);

SobelFilter_mac_mrcU #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 11 ),
    .din2_WIDTH( 24 ),
    .dout_WIDTH( 25 ))
SobelFilter_mac_mrcU_U55(
    .din0(grp_fu_2684_p0),
    .din1(grp_fu_2684_p1),
    .din2(grp_fu_2684_p2),
    .dout(grp_fu_2684_p3)
);

SobelFilter_mac_mrcU #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 11 ),
    .din2_WIDTH( 24 ),
    .dout_WIDTH( 25 ))
SobelFilter_mac_mrcU_U56(
    .din0(grp_fu_2693_p0),
    .din1(grp_fu_2693_p1),
    .din2(grp_fu_2693_p2),
    .dout(grp_fu_2693_p3)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter0 <= 1'b0;
    end else begin
        if (((exitcond389_i_fu_929_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_enable_reg_pp0_iter0 <= 1'b0;
        end else if (((exitcond390_i_fu_637_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state3))) begin
            ap_enable_reg_pp0_iter0 <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter1 <= ap_enable_reg_pp0_iter0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter2 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter3 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            if ((1'b1 == ap_condition_pp0_exit_iter2_state6)) begin
                ap_enable_reg_pp0_iter3 <= ap_enable_reg_pp0_iter1;
            end else if ((1'b1 == 1'b1)) begin
                ap_enable_reg_pp0_iter3 <= ap_enable_reg_pp0_iter2;
            end
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter4 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter4 <= ap_enable_reg_pp0_iter3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter5 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter5 <= ap_enable_reg_pp0_iter4;
        end else if (((exitcond390_i_fu_637_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state3))) begin
            ap_enable_reg_pp0_iter5 <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((exitcond389_i_fu_929_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        t_V_3_reg_610 <= j_V_fu_935_p2;
    end else if (((exitcond390_i_fu_637_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state3))) begin
        t_V_3_reg_610 <= 11'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((tmp_32_fu_627_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state2))) begin
        t_V_reg_599 <= 11'd0;
    end else if ((1'b1 == ap_CS_fsm_state10)) begin
        t_V_reg_599 <= i_V_reg_2945;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
        tmp_s_reg_588 <= 2'd0;
    end else if (((tmp_32_fu_627_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state2))) begin
        tmp_s_reg_588 <= tmp_31_fu_621_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((exitcond389_i_fu_929_p2 == 1'd0) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        brmerge_reg_3029 <= brmerge_fu_1051_p2;
        or_cond_i_i_reg_3015 <= or_cond_i_i_fu_987_p2;
        or_cond_i_reg_3042 <= or_cond_i_fu_1056_p2;
        tmp_108_reg_3024 <= tmp_108_fu_1047_p1;
        x_reg_3019 <= x_fu_1039_p3;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        brmerge_reg_3029_pp0_iter1_reg <= brmerge_reg_3029;
        exitcond389_i_reg_3006 <= exitcond389_i_fu_929_p2;
        exitcond389_i_reg_3006_pp0_iter1_reg <= exitcond389_i_reg_3006;
        or_cond_i_i_reg_3015_pp0_iter1_reg <= or_cond_i_i_reg_3015;
        or_cond_i_reg_3042_pp0_iter1_reg <= or_cond_i_reg_3042;
        tmp_108_reg_3024_pp0_iter1_reg <= tmp_108_reg_3024;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        exitcond389_i_reg_3006_pp0_iter2_reg <= exitcond389_i_reg_3006_pp0_iter1_reg;
        or_cond_i_reg_3042_pp0_iter2_reg <= or_cond_i_reg_3042_pp0_iter1_reg;
        or_cond_i_reg_3042_pp0_iter3_reg <= or_cond_i_reg_3042_pp0_iter2_reg;
        or_cond_i_reg_3042_pp0_iter4_reg <= or_cond_i_reg_3042_pp0_iter3_reg;
        src_kernel_win_0_va_6_reg_3100_pp0_iter3_reg <= src_kernel_win_0_va_6_reg_3100;
        src_kernel_win_1_va_6_reg_3123_pp0_iter3_reg <= src_kernel_win_1_va_6_reg_3123;
        src_kernel_win_2_va_9_reg_3146_pp0_iter3_reg <= src_kernel_win_2_va_9_reg_3146;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        i_V_reg_2945 <= i_V_fu_643_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((exitcond390_i_fu_637_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state3))) begin
        icmp_reg_2959 <= icmp_fu_671_p2;
        row_assign_13_0_0_t_reg_2985 <= row_assign_13_0_0_t_fu_879_p2;
        row_assign_13_0_1_t_reg_2992 <= row_assign_13_0_1_t_fu_899_p2;
        row_assign_13_0_2_t_reg_2999 <= row_assign_13_0_2_t_fu_919_p2;
        tmp_34_reg_2950 <= tmp_34_fu_649_p2;
        tmp_35_reg_2964 <= tmp_35_fu_677_p2;
        tmp_36_reg_2972 <= tmp_36_fu_689_p2;
        tmp_528_0_0_not_reg_2954 <= tmp_528_0_0_not_fu_655_p2;
        tmp_572_0_1_reg_2968 <= tmp_572_0_1_fu_683_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((exitcond389_i_reg_3006 == 1'd0) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        k_buf_0_val_3_addr_reg_3046 <= tmp_51_fu_1064_p1;
        k_buf_0_val_4_addr_reg_3052 <= tmp_51_fu_1064_p1;
        k_buf_0_val_5_addr_reg_3058 <= tmp_51_fu_1064_p1;
        k_buf_1_val_3_addr_reg_3064 <= tmp_51_fu_1064_p1;
        k_buf_1_val_4_addr_reg_3070 <= tmp_51_fu_1064_p1;
        k_buf_1_val_5_addr_reg_3076 <= tmp_51_fu_1064_p1;
        k_buf_2_val_3_addr_reg_3082 <= tmp_51_fu_1064_p1;
        k_buf_2_val_4_addr_reg_3088 <= tmp_51_fu_1064_p1;
        k_buf_2_val_5_addr_reg_3094 <= tmp_51_fu_1064_p1;
    end
end

always @ (posedge ap_clk) begin
    if (((or_cond_i_reg_3042_pp0_iter3_reg == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        p_Val2_17_reg_3287 <= p_Val2_17_fu_2404_p2;
        p_Val2_19_reg_3292 <= {{p_Val2_17_fu_2404_p2[21:14]}};
        p_Val2_6_reg_3247 <= p_Val2_6_fu_2194_p2;
        p_Val2_7_reg_3252 <= {{p_Val2_6_fu_2194_p2[21:14]}};
        p_Val2_9_reg_3272 <= {{p_Val2_s_fu_2299_p2[21:14]}};
        p_Val2_s_reg_3267 <= p_Val2_s_fu_2299_p2;
        tmp_111_reg_3257 <= p_Val2_6_fu_2194_p2[32'd13];
        tmp_117_reg_3277 <= p_Val2_s_fu_2299_p2[32'd13];
        tmp_123_reg_3297 <= p_Val2_17_fu_2404_p2[32'd13];
        tmp_58_reg_3262 <= {{p_Val2_6_fu_2194_p2[26:22]}};
        tmp_71_reg_3282 <= {{p_Val2_s_fu_2299_p2[26:22]}};
        tmp_80_reg_3302 <= {{p_Val2_17_fu_2404_p2[26:22]}};
    end
end

always @ (posedge ap_clk) begin
    if (((or_cond_i_reg_3042_pp0_iter2_reg == 1'd1) & (ap_enable_reg_pp0_iter3 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        p_Val2_91_0_0_2_reg_3190 <= grp_fu_2621_p4;
        p_Val2_91_1_0_2_reg_3211 <= grp_fu_2639_p4;
        p_Val2_91_2_0_2_reg_3232 <= grp_fu_2657_p4;
    end
end

always @ (posedge ap_clk) begin
    if (((or_cond_i_reg_3042_pp0_iter1_reg == 1'd1) & (exitcond389_i_reg_3006_pp0_iter1_reg == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        r_V_10_0_1_1_reg_3118 <= r_V_10_0_1_1_fu_2603_p2;
        r_V_10_1_1_1_reg_3141 <= r_V_10_1_1_1_fu_2609_p2;
        r_V_10_2_1_1_reg_3164 <= r_V_10_2_1_1_fu_2615_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((or_cond_i_reg_3042_pp0_iter2_reg == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        r_V_10_0_1_reg_3195[19 : 2] <= r_V_10_0_1_fu_1706_p2[19 : 2];
        r_V_10_1_1_reg_3216[19 : 2] <= r_V_10_1_1_fu_1845_p2[19 : 2];
        r_V_10_2_1_reg_3237[19 : 2] <= r_V_10_2_1_fu_1984_p2[19 : 2];
        src_kernel_win_0_va_9_reg_3184 <= src_kernel_win_0_va_fu_246;
        src_kernel_win_1_va_9_reg_3205 <= src_kernel_win_1_va_fu_270;
        src_kernel_win_2_va_12_reg_3226 <= src_kernel_win_2_va_fu_294;
        tmp44_reg_3200 <= tmp44_fu_1755_p2;
        tmp60_reg_3221 <= tmp60_fu_1894_p2;
        tmp65_reg_3242 <= tmp65_fu_2033_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_enable_reg_pp0_iter2 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_predicate_op227_read_state6 == 1'b1))) begin
        right_border_buf_0_1_fu_322 <= right_border_buf_0_s_fu_318;
        right_border_buf_0_2_fu_330 <= col_buf_0_val_1_0_fu_1140_p3;
        right_border_buf_0_3_fu_334 <= right_border_buf_0_2_fu_330;
        right_border_buf_0_4_fu_342 <= col_buf_0_val_2_0_fu_1159_p3;
        right_border_buf_0_5_fu_346 <= right_border_buf_0_4_fu_342;
        right_border_buf_0_s_fu_318 <= col_buf_0_val_0_0_fu_1121_p3;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_enable_reg_pp0_iter2 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_predicate_op272_read_state6 == 1'b1))) begin
        right_border_buf_1_1_fu_358 <= right_border_buf_1_s_fu_354;
        right_border_buf_1_2_fu_366 <= col_buf_1_val_1_0_fu_1315_p3;
        right_border_buf_1_3_fu_370 <= right_border_buf_1_2_fu_366;
        right_border_buf_1_4_fu_378 <= col_buf_1_val_2_0_fu_1334_p3;
        right_border_buf_1_5_fu_382 <= right_border_buf_1_4_fu_378;
        right_border_buf_1_s_fu_354 <= col_buf_1_val_0_0_fu_1296_p3;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_enable_reg_pp0_iter2 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_predicate_op311_read_state6 == 1'b1))) begin
        right_border_buf_2_1_fu_338 <= col_buf_2_val_2_0_fu_1500_p3;
        right_border_buf_2_2_fu_350 <= right_border_buf_2_3_fu_362;
        right_border_buf_2_3_fu_362 <= col_buf_2_val_1_0_fu_1481_p3;
        right_border_buf_2_4_fu_374 <= right_border_buf_2_5_fu_386;
        right_border_buf_2_5_fu_386 <= col_buf_2_val_0_0_fu_1462_p3;
        right_border_buf_2_s_fu_326 <= right_border_buf_2_1_fu_338;
    end
end

always @ (posedge ap_clk) begin
    if (((exitcond389_i_reg_3006_pp0_iter1_reg == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        src_kernel_win_0_va_16_reg_3169 <= src_kernel_win_0_va_2_fu_254;
        src_kernel_win_0_va_6_reg_3100 <= src_kernel_win_0_va_6_fu_1216_p3;
        src_kernel_win_0_va_7_reg_3106 <= src_kernel_win_0_va_7_fu_1234_p3;
        src_kernel_win_0_va_8_reg_3112 <= src_kernel_win_0_va_8_fu_1252_p3;
        src_kernel_win_1_va_16_reg_3174 <= src_kernel_win_1_va_2_fu_278;
        src_kernel_win_1_va_6_reg_3123 <= src_kernel_win_1_va_6_fu_1391_p3;
        src_kernel_win_1_va_7_reg_3129 <= src_kernel_win_1_va_7_fu_1409_p3;
        src_kernel_win_1_va_8_reg_3135 <= src_kernel_win_1_va_8_fu_1427_p3;
        src_kernel_win_2_va_10_reg_3152 <= src_kernel_win_2_va_10_fu_1566_p3;
        src_kernel_win_2_va_11_reg_3158 <= src_kernel_win_2_va_11_fu_1584_p3;
        src_kernel_win_2_va_7_reg_3179 <= src_kernel_win_2_va_2_fu_302;
        src_kernel_win_2_va_9_reg_3146 <= src_kernel_win_2_va_9_fu_1548_p3;
    end
end

always @ (posedge ap_clk) begin
    if (((exitcond389_i_reg_3006_pp0_iter2_reg == 1'd0) & (ap_enable_reg_pp0_iter3 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        src_kernel_win_0_va_1_fu_250 <= src_kernel_win_0_va_fu_246;
        src_kernel_win_0_va_3_fu_258 <= src_kernel_win_0_va_16_reg_3169;
        src_kernel_win_0_va_4_fu_262 <= src_kernel_win_0_va_8_reg_3112;
        src_kernel_win_0_va_5_fu_266 <= src_kernel_win_0_va_4_fu_262;
        src_kernel_win_0_va_fu_246 <= src_kernel_win_0_va_6_reg_3100;
        src_kernel_win_1_va_1_fu_274 <= src_kernel_win_1_va_fu_270;
        src_kernel_win_1_va_3_fu_282 <= src_kernel_win_1_va_16_reg_3174;
        src_kernel_win_1_va_4_fu_286 <= src_kernel_win_1_va_8_reg_3135;
        src_kernel_win_1_va_5_fu_290 <= src_kernel_win_1_va_4_fu_286;
        src_kernel_win_1_va_fu_270 <= src_kernel_win_1_va_6_reg_3123;
        src_kernel_win_2_va_1_fu_298 <= src_kernel_win_2_va_fu_294;
        src_kernel_win_2_va_3_fu_306 <= src_kernel_win_2_va_7_reg_3179;
        src_kernel_win_2_va_4_fu_310 <= src_kernel_win_2_va_11_reg_3158;
        src_kernel_win_2_va_5_fu_314 <= src_kernel_win_2_va_4_fu_310;
        src_kernel_win_2_va_fu_294 <= src_kernel_win_2_va_9_reg_3146;
    end
end

always @ (posedge ap_clk) begin
    if (((exitcond389_i_reg_3006_pp0_iter1_reg == 1'd0) & (ap_enable_reg_pp0_iter2 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        src_kernel_win_0_va_2_fu_254 <= src_kernel_win_0_va_7_fu_1234_p3;
        src_kernel_win_1_va_2_fu_278 <= src_kernel_win_1_va_7_fu_1409_p3;
        src_kernel_win_2_va_2_fu_302 <= src_kernel_win_2_va_10_fu_1566_p3;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter2 == 1'b1) & (ap_enable_reg_pp0_iter1 == 1'b0))) begin
        ap_condition_pp0_exit_iter2_state6 = 1'b1;
    end else begin
        ap_condition_pp0_exit_iter2_state6 = 1'b0;
    end
end

always @ (*) begin
    if ((((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1)) | ((exitcond390_i_fu_637_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state3)))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter5 == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter4 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter3 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((exitcond390_i_fu_637_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state3))) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        k_buf_0_val_3_ce0 = 1'b1;
    end else begin
        k_buf_0_val_3_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((((tmp_35_reg_2964 == 1'd1) & (or_cond_i_i_reg_3015_pp0_iter1_reg == 1'd1) & (icmp_reg_2959 == 1'd0) & (exitcond389_i_reg_3006_pp0_iter1_reg == 1'd0) & (ap_enable_reg_pp0_iter2 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001)) | ((ap_enable_reg_pp0_iter2 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_predicate_op227_read_state6 == 1'b1)))) begin
        k_buf_0_val_3_ce1 = 1'b1;
    end else begin
        k_buf_0_val_3_ce1 = 1'b0;
    end
end

always @ (*) begin
    if ((((tmp_35_reg_2964 == 1'd1) & (or_cond_i_i_reg_3015_pp0_iter1_reg == 1'd1) & (icmp_reg_2959 == 1'd0) & (exitcond389_i_reg_3006_pp0_iter1_reg == 1'd0) & (ap_enable_reg_pp0_iter2 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001)) | ((ap_enable_reg_pp0_iter2 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_predicate_op227_read_state6 == 1'b1)))) begin
        k_buf_0_val_3_we1 = 1'b1;
    end else begin
        k_buf_0_val_3_we1 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        k_buf_0_val_4_ce0 = 1'b1;
    end else begin
        k_buf_0_val_4_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((((tmp_572_0_1_reg_2968 == 1'd1) & (or_cond_i_i_reg_3015_pp0_iter1_reg == 1'd1) & (icmp_reg_2959 == 1'd0) & (exitcond389_i_reg_3006_pp0_iter1_reg == 1'd0) & (ap_enable_reg_pp0_iter2 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001)) | ((ap_enable_reg_pp0_iter2 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_predicate_op227_read_state6 == 1'b1)))) begin
        k_buf_0_val_4_ce1 = 1'b1;
    end else begin
        k_buf_0_val_4_ce1 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        if ((ap_predicate_op227_read_state6 == 1'b1)) begin
            k_buf_0_val_4_d1 = k_buf_0_val_3_q0;
        end else if ((1'b1 == ap_condition_647)) begin
            k_buf_0_val_4_d1 = p_src_data_stream_0_V_dout;
        end else begin
            k_buf_0_val_4_d1 = 'bx;
        end
    end else begin
        k_buf_0_val_4_d1 = 'bx;
    end
end

always @ (*) begin
    if ((((tmp_572_0_1_reg_2968 == 1'd1) & (or_cond_i_i_reg_3015_pp0_iter1_reg == 1'd1) & (icmp_reg_2959 == 1'd0) & (exitcond389_i_reg_3006_pp0_iter1_reg == 1'd0) & (ap_enable_reg_pp0_iter2 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001)) | ((ap_enable_reg_pp0_iter2 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_predicate_op227_read_state6 == 1'b1)))) begin
        k_buf_0_val_4_we1 = 1'b1;
    end else begin
        k_buf_0_val_4_we1 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        k_buf_0_val_5_ce0 = 1'b1;
    end else begin
        k_buf_0_val_5_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((((tmp_35_reg_2964 == 1'd1) & (or_cond_i_i_reg_3015_pp0_iter1_reg == 1'd1) & (icmp_reg_2959 == 1'd0) & (exitcond389_i_reg_3006_pp0_iter1_reg == 1'd0) & (ap_enable_reg_pp0_iter2 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001)) | ((ap_enable_reg_pp0_iter2 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_predicate_op227_read_state6 == 1'b1)))) begin
        k_buf_0_val_5_ce1 = 1'b1;
    end else begin
        k_buf_0_val_5_ce1 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        if ((ap_predicate_op227_read_state6 == 1'b1)) begin
            k_buf_0_val_5_d1 = k_buf_0_val_4_q0;
        end else if ((1'b1 == ap_condition_641)) begin
            k_buf_0_val_5_d1 = p_src_data_stream_0_V_dout;
        end else begin
            k_buf_0_val_5_d1 = 'bx;
        end
    end else begin
        k_buf_0_val_5_d1 = 'bx;
    end
end

always @ (*) begin
    if ((((tmp_35_reg_2964 == 1'd1) & (or_cond_i_i_reg_3015_pp0_iter1_reg == 1'd1) & (icmp_reg_2959 == 1'd0) & (exitcond389_i_reg_3006_pp0_iter1_reg == 1'd0) & (ap_enable_reg_pp0_iter2 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001)) | ((ap_enable_reg_pp0_iter2 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_predicate_op227_read_state6 == 1'b1)))) begin
        k_buf_0_val_5_we1 = 1'b1;
    end else begin
        k_buf_0_val_5_we1 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        k_buf_1_val_3_ce0 = 1'b1;
    end else begin
        k_buf_1_val_3_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((((tmp_35_reg_2964 == 1'd1) & (or_cond_i_i_reg_3015_pp0_iter1_reg == 1'd1) & (icmp_reg_2959 == 1'd0) & (exitcond389_i_reg_3006_pp0_iter1_reg == 1'd0) & (ap_enable_reg_pp0_iter2 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001)) | ((ap_enable_reg_pp0_iter2 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_predicate_op272_read_state6 == 1'b1)))) begin
        k_buf_1_val_3_ce1 = 1'b1;
    end else begin
        k_buf_1_val_3_ce1 = 1'b0;
    end
end

always @ (*) begin
    if ((((tmp_35_reg_2964 == 1'd1) & (or_cond_i_i_reg_3015_pp0_iter1_reg == 1'd1) & (icmp_reg_2959 == 1'd0) & (exitcond389_i_reg_3006_pp0_iter1_reg == 1'd0) & (ap_enable_reg_pp0_iter2 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001)) | ((ap_enable_reg_pp0_iter2 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_predicate_op272_read_state6 == 1'b1)))) begin
        k_buf_1_val_3_we1 = 1'b1;
    end else begin
        k_buf_1_val_3_we1 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        k_buf_1_val_4_ce0 = 1'b1;
    end else begin
        k_buf_1_val_4_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((((tmp_572_0_1_reg_2968 == 1'd1) & (or_cond_i_i_reg_3015_pp0_iter1_reg == 1'd1) & (icmp_reg_2959 == 1'd0) & (exitcond389_i_reg_3006_pp0_iter1_reg == 1'd0) & (ap_enable_reg_pp0_iter2 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001)) | ((ap_enable_reg_pp0_iter2 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_predicate_op272_read_state6 == 1'b1)))) begin
        k_buf_1_val_4_ce1 = 1'b1;
    end else begin
        k_buf_1_val_4_ce1 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        if ((ap_predicate_op272_read_state6 == 1'b1)) begin
            k_buf_1_val_4_d1 = k_buf_1_val_3_q0;
        end else if ((1'b1 == ap_condition_647)) begin
            k_buf_1_val_4_d1 = p_src_data_stream_1_V_dout;
        end else begin
            k_buf_1_val_4_d1 = 'bx;
        end
    end else begin
        k_buf_1_val_4_d1 = 'bx;
    end
end

always @ (*) begin
    if ((((tmp_572_0_1_reg_2968 == 1'd1) & (or_cond_i_i_reg_3015_pp0_iter1_reg == 1'd1) & (icmp_reg_2959 == 1'd0) & (exitcond389_i_reg_3006_pp0_iter1_reg == 1'd0) & (ap_enable_reg_pp0_iter2 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001)) | ((ap_enable_reg_pp0_iter2 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_predicate_op272_read_state6 == 1'b1)))) begin
        k_buf_1_val_4_we1 = 1'b1;
    end else begin
        k_buf_1_val_4_we1 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        k_buf_1_val_5_ce0 = 1'b1;
    end else begin
        k_buf_1_val_5_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((((tmp_35_reg_2964 == 1'd1) & (or_cond_i_i_reg_3015_pp0_iter1_reg == 1'd1) & (icmp_reg_2959 == 1'd0) & (exitcond389_i_reg_3006_pp0_iter1_reg == 1'd0) & (ap_enable_reg_pp0_iter2 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001)) | ((ap_enable_reg_pp0_iter2 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_predicate_op272_read_state6 == 1'b1)))) begin
        k_buf_1_val_5_ce1 = 1'b1;
    end else begin
        k_buf_1_val_5_ce1 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        if ((ap_predicate_op272_read_state6 == 1'b1)) begin
            k_buf_1_val_5_d1 = k_buf_1_val_4_q0;
        end else if ((1'b1 == ap_condition_641)) begin
            k_buf_1_val_5_d1 = p_src_data_stream_1_V_dout;
        end else begin
            k_buf_1_val_5_d1 = 'bx;
        end
    end else begin
        k_buf_1_val_5_d1 = 'bx;
    end
end

always @ (*) begin
    if ((((tmp_35_reg_2964 == 1'd1) & (or_cond_i_i_reg_3015_pp0_iter1_reg == 1'd1) & (icmp_reg_2959 == 1'd0) & (exitcond389_i_reg_3006_pp0_iter1_reg == 1'd0) & (ap_enable_reg_pp0_iter2 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001)) | ((ap_enable_reg_pp0_iter2 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_predicate_op272_read_state6 == 1'b1)))) begin
        k_buf_1_val_5_we1 = 1'b1;
    end else begin
        k_buf_1_val_5_we1 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        k_buf_2_val_3_ce0 = 1'b1;
    end else begin
        k_buf_2_val_3_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((((tmp_35_reg_2964 == 1'd1) & (or_cond_i_i_reg_3015_pp0_iter1_reg == 1'd1) & (icmp_reg_2959 == 1'd0) & (exitcond389_i_reg_3006_pp0_iter1_reg == 1'd0) & (ap_enable_reg_pp0_iter2 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001)) | ((ap_enable_reg_pp0_iter2 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_predicate_op311_read_state6 == 1'b1)))) begin
        k_buf_2_val_3_ce1 = 1'b1;
    end else begin
        k_buf_2_val_3_ce1 = 1'b0;
    end
end

always @ (*) begin
    if ((((tmp_35_reg_2964 == 1'd1) & (or_cond_i_i_reg_3015_pp0_iter1_reg == 1'd1) & (icmp_reg_2959 == 1'd0) & (exitcond389_i_reg_3006_pp0_iter1_reg == 1'd0) & (ap_enable_reg_pp0_iter2 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001)) | ((ap_enable_reg_pp0_iter2 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_predicate_op311_read_state6 == 1'b1)))) begin
        k_buf_2_val_3_we1 = 1'b1;
    end else begin
        k_buf_2_val_3_we1 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        k_buf_2_val_4_ce0 = 1'b1;
    end else begin
        k_buf_2_val_4_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((((tmp_572_0_1_reg_2968 == 1'd1) & (or_cond_i_i_reg_3015_pp0_iter1_reg == 1'd1) & (icmp_reg_2959 == 1'd0) & (exitcond389_i_reg_3006_pp0_iter1_reg == 1'd0) & (ap_enable_reg_pp0_iter2 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001)) | ((ap_enable_reg_pp0_iter2 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_predicate_op311_read_state6 == 1'b1)))) begin
        k_buf_2_val_4_ce1 = 1'b1;
    end else begin
        k_buf_2_val_4_ce1 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        if ((ap_predicate_op311_read_state6 == 1'b1)) begin
            k_buf_2_val_4_d1 = k_buf_2_val_3_q0;
        end else if ((1'b1 == ap_condition_647)) begin
            k_buf_2_val_4_d1 = p_src_data_stream_2_V_dout;
        end else begin
            k_buf_2_val_4_d1 = 'bx;
        end
    end else begin
        k_buf_2_val_4_d1 = 'bx;
    end
end

always @ (*) begin
    if ((((tmp_572_0_1_reg_2968 == 1'd1) & (or_cond_i_i_reg_3015_pp0_iter1_reg == 1'd1) & (icmp_reg_2959 == 1'd0) & (exitcond389_i_reg_3006_pp0_iter1_reg == 1'd0) & (ap_enable_reg_pp0_iter2 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001)) | ((ap_enable_reg_pp0_iter2 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_predicate_op311_read_state6 == 1'b1)))) begin
        k_buf_2_val_4_we1 = 1'b1;
    end else begin
        k_buf_2_val_4_we1 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        k_buf_2_val_5_ce0 = 1'b1;
    end else begin
        k_buf_2_val_5_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((((tmp_35_reg_2964 == 1'd1) & (or_cond_i_i_reg_3015_pp0_iter1_reg == 1'd1) & (icmp_reg_2959 == 1'd0) & (exitcond389_i_reg_3006_pp0_iter1_reg == 1'd0) & (ap_enable_reg_pp0_iter2 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001)) | ((ap_enable_reg_pp0_iter2 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_predicate_op311_read_state6 == 1'b1)))) begin
        k_buf_2_val_5_ce1 = 1'b1;
    end else begin
        k_buf_2_val_5_ce1 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        if ((ap_predicate_op311_read_state6 == 1'b1)) begin
            k_buf_2_val_5_d1 = k_buf_2_val_4_q0;
        end else if ((1'b1 == ap_condition_641)) begin
            k_buf_2_val_5_d1 = p_src_data_stream_2_V_dout;
        end else begin
            k_buf_2_val_5_d1 = 'bx;
        end
    end else begin
        k_buf_2_val_5_d1 = 'bx;
    end
end

always @ (*) begin
    if ((((tmp_35_reg_2964 == 1'd1) & (or_cond_i_i_reg_3015_pp0_iter1_reg == 1'd1) & (icmp_reg_2959 == 1'd0) & (exitcond389_i_reg_3006_pp0_iter1_reg == 1'd0) & (ap_enable_reg_pp0_iter2 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001)) | ((ap_enable_reg_pp0_iter2 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_predicate_op311_read_state6 == 1'b1)))) begin
        k_buf_2_val_5_we1 = 1'b1;
    end else begin
        k_buf_2_val_5_we1 = 1'b0;
    end
end

always @ (*) begin
    if (((or_cond_i_reg_3042_pp0_iter4_reg == 1'd1) & (1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter5 == 1'b1))) begin
        p_dst_data_stream_0_V_blk_n = p_dst_data_stream_0_V_full_n;
    end else begin
        p_dst_data_stream_0_V_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((or_cond_i_reg_3042_pp0_iter4_reg == 1'd1) & (ap_enable_reg_pp0_iter5 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        p_dst_data_stream_0_V_write = 1'b1;
    end else begin
        p_dst_data_stream_0_V_write = 1'b0;
    end
end

always @ (*) begin
    if (((or_cond_i_reg_3042_pp0_iter4_reg == 1'd1) & (1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter5 == 1'b1))) begin
        p_dst_data_stream_1_V_blk_n = p_dst_data_stream_1_V_full_n;
    end else begin
        p_dst_data_stream_1_V_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((or_cond_i_reg_3042_pp0_iter4_reg == 1'd1) & (ap_enable_reg_pp0_iter5 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        p_dst_data_stream_1_V_write = 1'b1;
    end else begin
        p_dst_data_stream_1_V_write = 1'b0;
    end
end

always @ (*) begin
    if (((or_cond_i_reg_3042_pp0_iter4_reg == 1'd1) & (1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter5 == 1'b1))) begin
        p_dst_data_stream_2_V_blk_n = p_dst_data_stream_2_V_full_n;
    end else begin
        p_dst_data_stream_2_V_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((or_cond_i_reg_3042_pp0_iter4_reg == 1'd1) & (ap_enable_reg_pp0_iter5 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        p_dst_data_stream_2_V_write = 1'b1;
    end else begin
        p_dst_data_stream_2_V_write = 1'b0;
    end
end

always @ (*) begin
    if ((((or_cond_i_i_reg_3015_pp0_iter1_reg == 1'd1) & (icmp_reg_2959 == 1'd0) & (exitcond389_i_reg_3006_pp0_iter1_reg == 1'd0) & (1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter2 == 1'b1)) | ((tmp_34_reg_2950 == 1'd1) & (icmp_reg_2959 == 1'd1) & (or_cond_i_i_reg_3015_pp0_iter1_reg == 1'd1) & (exitcond389_i_reg_3006_pp0_iter1_reg == 1'd0) & (1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter2 == 1'b1)))) begin
        p_src_data_stream_0_V_blk_n = p_src_data_stream_0_V_empty_n;
    end else begin
        p_src_data_stream_0_V_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((((ap_enable_reg_pp0_iter2 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_predicate_op227_read_state6 == 1'b1)) | ((ap_enable_reg_pp0_iter2 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_predicate_op215_read_state6 == 1'b1)))) begin
        p_src_data_stream_0_V_read = 1'b1;
    end else begin
        p_src_data_stream_0_V_read = 1'b0;
    end
end

always @ (*) begin
    if ((((or_cond_i_i_reg_3015_pp0_iter1_reg == 1'd1) & (icmp_reg_2959 == 1'd0) & (exitcond389_i_reg_3006_pp0_iter1_reg == 1'd0) & (1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter2 == 1'b1)) | ((tmp_34_reg_2950 == 1'd1) & (icmp_reg_2959 == 1'd1) & (or_cond_i_i_reg_3015_pp0_iter1_reg == 1'd1) & (exitcond389_i_reg_3006_pp0_iter1_reg == 1'd0) & (1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter2 == 1'b1)))) begin
        p_src_data_stream_1_V_blk_n = p_src_data_stream_1_V_empty_n;
    end else begin
        p_src_data_stream_1_V_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((((ap_enable_reg_pp0_iter2 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_predicate_op272_read_state6 == 1'b1)) | ((ap_enable_reg_pp0_iter2 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_predicate_op260_read_state6 == 1'b1)))) begin
        p_src_data_stream_1_V_read = 1'b1;
    end else begin
        p_src_data_stream_1_V_read = 1'b0;
    end
end

always @ (*) begin
    if ((((or_cond_i_i_reg_3015_pp0_iter1_reg == 1'd1) & (icmp_reg_2959 == 1'd0) & (exitcond389_i_reg_3006_pp0_iter1_reg == 1'd0) & (1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter2 == 1'b1)) | ((tmp_34_reg_2950 == 1'd1) & (icmp_reg_2959 == 1'd1) & (or_cond_i_i_reg_3015_pp0_iter1_reg == 1'd1) & (exitcond389_i_reg_3006_pp0_iter1_reg == 1'd0) & (1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter2 == 1'b1)))) begin
        p_src_data_stream_2_V_blk_n = p_src_data_stream_2_V_empty_n;
    end else begin
        p_src_data_stream_2_V_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((((ap_enable_reg_pp0_iter2 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_predicate_op311_read_state6 == 1'b1)) | ((ap_enable_reg_pp0_iter2 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_predicate_op302_read_state6 == 1'b1)))) begin
        p_src_data_stream_2_V_read = 1'b1;
    end else begin
        p_src_data_stream_2_V_read = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            if (((tmp_32_fu_627_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state2))) begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end
        end
        ap_ST_fsm_state3 : begin
            if (((exitcond390_i_fu_637_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state3))) begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end
        end
        ap_ST_fsm_pp0_stage0 : begin
            if ((~((ap_enable_reg_pp0_iter1 == 1'b0) & (1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter3 == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b1)) & ~((ap_enable_reg_pp0_iter4 == 1'b0) & (1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter5 == 1'b1)))) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end else if ((((ap_enable_reg_pp0_iter4 == 1'b0) & (1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter5 == 1'b1)) | ((ap_enable_reg_pp0_iter1 == 1'b0) & (1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter3 == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b1)))) begin
                ap_NS_fsm = ap_ST_fsm_state10;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end
        end
        ap_ST_fsm_state10 : begin
            ap_NS_fsm = ap_ST_fsm_state3;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign ImagLoc_x_cast_fu_963_p1 = ImagLoc_x_fu_957_p2;

assign ImagLoc_x_fu_957_p2 = ($signed(12'd4095) + $signed(t_V_3_cast_fu_925_p1));

assign Range1_all_zeros_2_fu_2528_p2 = ((tmp_71_reg_3282 == 5'd0) ? 1'b1 : 1'b0);

assign Range1_all_zeros_3_fu_2583_p2 = ((tmp_80_reg_3302 == 5'd0) ? 1'b1 : 1'b0);

assign Range1_all_zeros_fu_2473_p2 = ((tmp_58_reg_3262 == 5'd0) ? 1'b1 : 1'b0);

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd3];

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state10 = ap_CS_fsm[32'd4];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state3 = ap_CS_fsm[32'd2];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage0_01001 = (((ap_enable_reg_pp0_iter5 == 1'b1) & (((or_cond_i_reg_3042_pp0_iter4_reg == 1'd1) & (p_dst_data_stream_2_V_full_n == 1'b0)) | ((or_cond_i_reg_3042_pp0_iter4_reg == 1'd1) & (p_dst_data_stream_1_V_full_n == 1'b0)) | ((or_cond_i_reg_3042_pp0_iter4_reg == 1'd1) & (p_dst_data_stream_0_V_full_n == 1'b0)))) | ((ap_enable_reg_pp0_iter2 == 1'b1) & (((p_src_data_stream_2_V_empty_n == 1'b0) & (ap_predicate_op311_read_state6 == 1'b1)) | ((p_src_data_stream_2_V_empty_n == 1'b0) & (ap_predicate_op302_read_state6 == 1'b1)) | ((p_src_data_stream_1_V_empty_n == 1'b0) & (ap_predicate_op272_read_state6 == 1'b1)) | ((p_src_data_stream_1_V_empty_n == 1'b0) & (ap_predicate_op260_read_state6 == 1'b1)) | ((p_src_data_stream_0_V_empty_n == 1'b0) & (ap_predicate_op227_read_state6 == 1'b1)) | ((p_src_data_stream_0_V_empty_n == 1'b0) & (ap_predicate_op215_read_state6 == 1'b1)))));
end

always @ (*) begin
    ap_block_pp0_stage0_11001 = (((ap_enable_reg_pp0_iter5 == 1'b1) & (((or_cond_i_reg_3042_pp0_iter4_reg == 1'd1) & (p_dst_data_stream_2_V_full_n == 1'b0)) | ((or_cond_i_reg_3042_pp0_iter4_reg == 1'd1) & (p_dst_data_stream_1_V_full_n == 1'b0)) | ((or_cond_i_reg_3042_pp0_iter4_reg == 1'd1) & (p_dst_data_stream_0_V_full_n == 1'b0)))) | ((ap_enable_reg_pp0_iter2 == 1'b1) & (((p_src_data_stream_2_V_empty_n == 1'b0) & (ap_predicate_op311_read_state6 == 1'b1)) | ((p_src_data_stream_2_V_empty_n == 1'b0) & (ap_predicate_op302_read_state6 == 1'b1)) | ((p_src_data_stream_1_V_empty_n == 1'b0) & (ap_predicate_op272_read_state6 == 1'b1)) | ((p_src_data_stream_1_V_empty_n == 1'b0) & (ap_predicate_op260_read_state6 == 1'b1)) | ((p_src_data_stream_0_V_empty_n == 1'b0) & (ap_predicate_op227_read_state6 == 1'b1)) | ((p_src_data_stream_0_V_empty_n == 1'b0) & (ap_predicate_op215_read_state6 == 1'b1)))));
end

always @ (*) begin
    ap_block_pp0_stage0_subdone = (((ap_enable_reg_pp0_iter5 == 1'b1) & (((or_cond_i_reg_3042_pp0_iter4_reg == 1'd1) & (p_dst_data_stream_2_V_full_n == 1'b0)) | ((or_cond_i_reg_3042_pp0_iter4_reg == 1'd1) & (p_dst_data_stream_1_V_full_n == 1'b0)) | ((or_cond_i_reg_3042_pp0_iter4_reg == 1'd1) & (p_dst_data_stream_0_V_full_n == 1'b0)))) | ((ap_enable_reg_pp0_iter2 == 1'b1) & (((p_src_data_stream_2_V_empty_n == 1'b0) & (ap_predicate_op311_read_state6 == 1'b1)) | ((p_src_data_stream_2_V_empty_n == 1'b0) & (ap_predicate_op302_read_state6 == 1'b1)) | ((p_src_data_stream_1_V_empty_n == 1'b0) & (ap_predicate_op272_read_state6 == 1'b1)) | ((p_src_data_stream_1_V_empty_n == 1'b0) & (ap_predicate_op260_read_state6 == 1'b1)) | ((p_src_data_stream_0_V_empty_n == 1'b0) & (ap_predicate_op227_read_state6 == 1'b1)) | ((p_src_data_stream_0_V_empty_n == 1'b0) & (ap_predicate_op215_read_state6 == 1'b1)))));
end

assign ap_block_state4_pp0_stage0_iter0 = ~(1'b1 == 1'b1);

assign ap_block_state5_pp0_stage0_iter1 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_state6_pp0_stage0_iter2 = (((p_src_data_stream_2_V_empty_n == 1'b0) & (ap_predicate_op311_read_state6 == 1'b1)) | ((p_src_data_stream_2_V_empty_n == 1'b0) & (ap_predicate_op302_read_state6 == 1'b1)) | ((p_src_data_stream_1_V_empty_n == 1'b0) & (ap_predicate_op272_read_state6 == 1'b1)) | ((p_src_data_stream_1_V_empty_n == 1'b0) & (ap_predicate_op260_read_state6 == 1'b1)) | ((p_src_data_stream_0_V_empty_n == 1'b0) & (ap_predicate_op227_read_state6 == 1'b1)) | ((p_src_data_stream_0_V_empty_n == 1'b0) & (ap_predicate_op215_read_state6 == 1'b1)));
end

assign ap_block_state7_pp0_stage0_iter3 = ~(1'b1 == 1'b1);

assign ap_block_state8_pp0_stage0_iter4 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_state9_pp0_stage0_iter5 = (((or_cond_i_reg_3042_pp0_iter4_reg == 1'd1) & (p_dst_data_stream_2_V_full_n == 1'b0)) | ((or_cond_i_reg_3042_pp0_iter4_reg == 1'd1) & (p_dst_data_stream_1_V_full_n == 1'b0)) | ((or_cond_i_reg_3042_pp0_iter4_reg == 1'd1) & (p_dst_data_stream_0_V_full_n == 1'b0)));
end

always @ (*) begin
    ap_condition_641 = ((tmp_35_reg_2964 == 1'd1) & (or_cond_i_i_reg_3015_pp0_iter1_reg == 1'd1) & (icmp_reg_2959 == 1'd0) & (exitcond389_i_reg_3006_pp0_iter1_reg == 1'd0));
end

always @ (*) begin
    ap_condition_647 = ((tmp_572_0_1_reg_2968 == 1'd1) & (or_cond_i_i_reg_3015_pp0_iter1_reg == 1'd1) & (icmp_reg_2959 == 1'd0) & (exitcond389_i_reg_3006_pp0_iter1_reg == 1'd0));
end

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

always @ (*) begin
    ap_predicate_op215_read_state6 = ((or_cond_i_i_reg_3015_pp0_iter1_reg == 1'd1) & (icmp_reg_2959 == 1'd0) & (exitcond389_i_reg_3006_pp0_iter1_reg == 1'd0));
end

always @ (*) begin
    ap_predicate_op227_read_state6 = ((tmp_34_reg_2950 == 1'd1) & (icmp_reg_2959 == 1'd1) & (or_cond_i_i_reg_3015_pp0_iter1_reg == 1'd1) & (exitcond389_i_reg_3006_pp0_iter1_reg == 1'd0));
end

always @ (*) begin
    ap_predicate_op260_read_state6 = ((or_cond_i_i_reg_3015_pp0_iter1_reg == 1'd1) & (icmp_reg_2959 == 1'd0) & (exitcond389_i_reg_3006_pp0_iter1_reg == 1'd0));
end

always @ (*) begin
    ap_predicate_op272_read_state6 = ((tmp_34_reg_2950 == 1'd1) & (icmp_reg_2959 == 1'd1) & (or_cond_i_i_reg_3015_pp0_iter1_reg == 1'd1) & (exitcond389_i_reg_3006_pp0_iter1_reg == 1'd0));
end

always @ (*) begin
    ap_predicate_op302_read_state6 = ((or_cond_i_i_reg_3015_pp0_iter1_reg == 1'd1) & (icmp_reg_2959 == 1'd0) & (exitcond389_i_reg_3006_pp0_iter1_reg == 1'd0));
end

always @ (*) begin
    ap_predicate_op311_read_state6 = ((tmp_34_reg_2950 == 1'd1) & (icmp_reg_2959 == 1'd1) & (or_cond_i_i_reg_3015_pp0_iter1_reg == 1'd1) & (exitcond389_i_reg_3006_pp0_iter1_reg == 1'd0));
end

assign brmerge_fu_1051_p2 = (tmp_528_0_0_not_reg_2954 | tmp_49_fu_981_p2);

assign brmerge_i_i_not_i_i1_fu_2533_p2 = (carry_i1_fu_2522_p2 & Range1_all_zeros_2_fu_2528_p2);

assign brmerge_i_i_not_i_i2_fu_2588_p2 = (carry_i2_fu_2577_p2 & Range1_all_zeros_3_fu_2583_p2);

assign brmerge_i_i_not_i_i_fu_2478_p2 = (carry_i_fu_2467_p2 & Range1_all_zeros_fu_2473_p2);

assign carry_i1_fu_2522_p2 = (tmp_119_fu_2508_p3 | not_Result_4_i_i_1_fu_2516_p2);

assign carry_i2_fu_2577_p2 = (tmp_125_fu_2563_p3 | not_Result_4_i_i_2_fu_2571_p2);

assign carry_i_fu_2467_p2 = (tmp_113_fu_2453_p3 | not_Result_4_i_i_fu_2461_p2);

assign col_assign_6_0_t_fu_1104_p2 = (tmp_108_reg_3024_pp0_iter1_reg ^ 2'd3);

assign col_buf_0_val_0_0_fu_1121_p3 = ((brmerge_reg_3029_pp0_iter1_reg[0:0] === 1'b1) ? k_buf_0_val_3_q0 : tmp_52_fu_1109_p5);

assign col_buf_0_val_1_0_fu_1140_p3 = ((brmerge_reg_3029_pp0_iter1_reg[0:0] === 1'b1) ? k_buf_0_val_4_q0 : tmp_53_fu_1128_p5);

assign col_buf_0_val_2_0_fu_1159_p3 = ((brmerge_reg_3029_pp0_iter1_reg[0:0] === 1'b1) ? k_buf_0_val_5_q0 : tmp_54_fu_1147_p5);

assign col_buf_1_val_0_0_fu_1296_p3 = ((brmerge_reg_3029_pp0_iter1_reg[0:0] === 1'b1) ? k_buf_1_val_3_q0 : tmp_59_fu_1284_p5);

assign col_buf_1_val_1_0_fu_1315_p3 = ((brmerge_reg_3029_pp0_iter1_reg[0:0] === 1'b1) ? k_buf_1_val_4_q0 : tmp_60_fu_1303_p5);

assign col_buf_1_val_2_0_fu_1334_p3 = ((brmerge_reg_3029_pp0_iter1_reg[0:0] === 1'b1) ? k_buf_1_val_5_q0 : tmp_63_fu_1322_p5);

assign col_buf_2_val_0_0_fu_1462_p3 = ((brmerge_reg_3029_pp0_iter1_reg[0:0] === 1'b1) ? k_buf_2_val_3_q0 : tmp_73_fu_1450_p5);

assign col_buf_2_val_1_0_fu_1481_p3 = ((brmerge_reg_3029_pp0_iter1_reg[0:0] === 1'b1) ? k_buf_2_val_4_q0 : tmp_75_fu_1469_p5);

assign col_buf_2_val_2_0_fu_1500_p3 = ((brmerge_reg_3029_pp0_iter1_reg[0:0] === 1'b1) ? k_buf_2_val_5_q0 : tmp_76_fu_1488_p5);

assign exitcond389_i_fu_929_p2 = ((t_V_3_reg_610 == 11'd1922) ? 1'b1 : 1'b0);

assign exitcond390_i_fu_637_p2 = ((t_V_reg_599 == 11'd1082) ? 1'b1 : 1'b0);

assign grp_fu_2621_p0 = grp_fu_2621_p00;

assign grp_fu_2621_p00 = src_kernel_win_0_va_5_fu_266;

assign grp_fu_2621_p1 = grp_fu_2621_p10;

assign grp_fu_2621_p10 = src_kernel_win_0_va_8_reg_3112;

assign grp_fu_2621_p2 = 19'd936;

assign grp_fu_2621_p3 = grp_fu_2621_p30;

assign grp_fu_2621_p30 = $unsigned(r_V_10_0_0_1_cast_fu_1671_p1);

assign grp_fu_2631_p0 = grp_fu_2631_p00;

assign grp_fu_2631_p00 = src_kernel_win_0_va_1_fu_250;

assign grp_fu_2631_p1 = 19'd936;

assign grp_fu_2639_p0 = grp_fu_2639_p00;

assign grp_fu_2639_p00 = src_kernel_win_1_va_5_fu_290;

assign grp_fu_2639_p1 = grp_fu_2639_p10;

assign grp_fu_2639_p10 = src_kernel_win_1_va_8_reg_3135;

assign grp_fu_2639_p2 = 19'd936;

assign grp_fu_2639_p3 = grp_fu_2639_p30;

assign grp_fu_2639_p30 = $unsigned(r_V_10_1_0_1_cast_fu_1810_p1);

assign grp_fu_2649_p0 = grp_fu_2649_p00;

assign grp_fu_2649_p00 = src_kernel_win_1_va_1_fu_274;

assign grp_fu_2649_p1 = 19'd936;

assign grp_fu_2657_p0 = grp_fu_2657_p00;

assign grp_fu_2657_p00 = src_kernel_win_2_va_5_fu_314;

assign grp_fu_2657_p1 = grp_fu_2657_p10;

assign grp_fu_2657_p10 = src_kernel_win_2_va_11_reg_3158;

assign grp_fu_2657_p2 = 19'd936;

assign grp_fu_2657_p3 = grp_fu_2657_p30;

assign grp_fu_2657_p30 = $unsigned(r_V_10_2_0_1_cast_fu_1949_p1);

assign grp_fu_2667_p0 = grp_fu_2667_p00;

assign grp_fu_2667_p00 = src_kernel_win_2_va_1_fu_298;

assign grp_fu_2667_p1 = 19'd936;

assign grp_fu_2675_p0 = grp_fu_2675_p00;

assign grp_fu_2675_p00 = src_kernel_win_0_va_6_reg_3100_pp0_iter3_reg;

assign grp_fu_2675_p1 = 19'd936;

assign grp_fu_2675_p2 = grp_fu_2675_p20;

assign grp_fu_2675_p20 = $unsigned(r_V_10_0_2_1_cast_fu_2180_p1);

assign grp_fu_2684_p0 = grp_fu_2684_p00;

assign grp_fu_2684_p00 = src_kernel_win_1_va_6_reg_3123_pp0_iter3_reg;

assign grp_fu_2684_p1 = 19'd936;

assign grp_fu_2684_p2 = grp_fu_2684_p20;

assign grp_fu_2684_p20 = $unsigned(r_V_10_1_2_1_cast_fu_2285_p1);

assign grp_fu_2693_p0 = grp_fu_2693_p00;

assign grp_fu_2693_p00 = src_kernel_win_2_va_9_reg_3146_pp0_iter3_reg;

assign grp_fu_2693_p1 = 19'd936;

assign grp_fu_2693_p2 = grp_fu_2693_p20;

assign grp_fu_2693_p20 = $unsigned(r_V_10_2_2_1_cast_fu_2390_p1);

assign i_V_fu_643_p2 = (t_V_reg_599 + 11'd1);

assign icmp1_fu_951_p2 = ((tmp_105_fu_941_p4 != 10'd0) ? 1'b1 : 1'b0);

assign icmp_fu_671_p2 = ((tmp_fu_661_p4 != 10'd0) ? 1'b1 : 1'b0);

assign j_V_fu_935_p2 = (t_V_3_reg_610 + 11'd1);

assign k_buf_0_val_3_address0 = tmp_51_fu_1064_p1;

assign k_buf_0_val_4_address0 = tmp_51_fu_1064_p1;

assign k_buf_0_val_5_address0 = tmp_51_fu_1064_p1;

assign k_buf_1_val_3_address0 = tmp_51_fu_1064_p1;

assign k_buf_1_val_4_address0 = tmp_51_fu_1064_p1;

assign k_buf_1_val_5_address0 = tmp_51_fu_1064_p1;

assign k_buf_2_val_3_address0 = tmp_51_fu_1064_p1;

assign k_buf_2_val_4_address0 = tmp_51_fu_1064_p1;

assign k_buf_2_val_5_address0 = tmp_51_fu_1064_p1;

assign not_Result_4_i_i_1_fu_2516_p2 = (tmp_118_fu_2496_p3 ^ 1'd1);

assign not_Result_4_i_i_2_fu_2571_p2 = (tmp_124_fu_2551_p3 ^ 1'd1);

assign not_Result_4_i_i_fu_2461_p2 = (tmp_112_fu_2441_p3 ^ 1'd1);

assign or_cond_i425_i_fu_725_p2 = (tmp_39_fu_719_p2 & rev_fu_713_p2);

assign or_cond_i_fu_1056_p2 = (icmp_reg_2959 & icmp1_fu_951_p2);

assign or_cond_i_i_fu_987_p2 = (tmp_49_fu_981_p2 & rev1_fu_975_p2);

assign p_Val2_15_fu_2503_p2 = (p_Val2_9_reg_3272 + tmp_4_i_i1_fu_2493_p1);

assign p_Val2_17_fu_2404_p2 = (tmp67_cast_fu_2401_p1 + p_Val2_91_2_2_cast_fu_2358_p1);

assign p_Val2_20_fu_2558_p2 = (p_Val2_19_reg_3292 + tmp_4_i_i2_fu_2548_p1);

assign p_Val2_6_fu_2194_p2 = (tmp57_cast_fu_2191_p1 + p_Val2_91_0_2_cast_fu_2148_p1);

assign p_Val2_8_fu_2448_p2 = (p_Val2_7_reg_3252 + tmp_4_i_i_fu_2438_p1);

assign p_Val2_91_0_0_2_ca_fu_2123_p1 = p_Val2_91_0_0_2_reg_3190;

assign p_Val2_91_0_2_cast_fu_2148_p1 = p_Val2_91_0_2_fu_2142_p2;

assign p_Val2_91_0_2_fu_2142_p2 = (tmp55_cast_fu_2139_p1 + tmp42_fu_2133_p2);

assign p_Val2_91_1_0_2_ca_fu_2228_p1 = p_Val2_91_1_0_2_reg_3211;

assign p_Val2_91_1_2_cast_fu_2253_p1 = p_Val2_91_1_2_fu_2247_p2;

assign p_Val2_91_1_2_fu_2247_p2 = (tmp60_cast_fu_2244_p1 + tmp59_fu_2238_p2);

assign p_Val2_91_2_0_2_ca_fu_2333_p1 = p_Val2_91_2_0_2_reg_3232;

assign p_Val2_91_2_2_cast_fu_2358_p1 = p_Val2_91_2_2_fu_2352_p2;

assign p_Val2_91_2_2_fu_2352_p2 = (tmp65_cast_fu_2349_p1 + tmp64_fu_2343_p2);

assign p_Val2_s_fu_2299_p2 = (tmp62_cast_fu_2296_p1 + p_Val2_91_1_2_cast_fu_2253_p1);

assign p_assign_14_0_1_fu_763_p2 = ($signed(12'd4094) + $signed(t_V_cast_fu_633_p1));

assign p_assign_14_0_2_fu_807_p2 = ($signed(12'd4093) + $signed(t_V_cast_fu_633_p1));

assign p_assign_1_fu_739_p2 = (12'd1 - t_V_cast_fu_633_p1);

assign p_assign_9_fu_1001_p2 = (12'd1 - t_V_3_cast_fu_925_p1);

assign p_assign_s_fu_1025_p2 = ($signed(14'd3838) - $signed(p_p2_i_i_cast_fu_1015_p1));

assign p_dst_data_stream_0_V_din = ((brmerge_i_i_not_i_i_fu_2478_p2[0:0] === 1'b1) ? p_Val2_8_fu_2448_p2 : 8'd255);

assign p_dst_data_stream_1_V_din = ((brmerge_i_i_not_i_i1_fu_2533_p2[0:0] === 1'b1) ? p_Val2_15_fu_2503_p2 : 8'd255);

assign p_dst_data_stream_2_V_din = ((brmerge_i_i_not_i_i2_fu_2588_p2[0:0] === 1'b1) ? p_Val2_20_fu_2558_p2 : 8'd255);

assign p_p2_i426_i_fu_745_p3 = ((tmp_65_fu_731_p3[0:0] === 1'b1) ? p_assign_1_fu_739_p2 : tmp_38_fu_699_p2);

assign p_p2_i_i_cast_fu_1015_p1 = p_p2_i_i_fu_1007_p3;

assign p_p2_i_i_fu_1007_p3 = ((tmp_107_fu_993_p3[0:0] === 1'b1) ? p_assign_9_fu_1001_p2 : ImagLoc_x_fu_957_p2);

assign p_p2_i_i_p_assign_s_fu_1031_p3 = ((tmp_50_fu_1019_p2[0:0] === 1'b1) ? p_p2_i_i_cast_fu_1015_p1 : p_assign_s_fu_1025_p2);

assign p_shl10_cast_fu_1829_p1 = p_shl10_fu_1821_p3;

assign p_shl10_fu_1821_p3 = {{src_kernel_win_1_va_3_fu_282}, {11'd0}};

assign p_shl11_cast_fu_1841_p1 = p_shl11_fu_1833_p3;

assign p_shl11_fu_1833_p3 = {{src_kernel_win_1_va_3_fu_282}, {2'd0}};

assign p_shl12_cast_fu_1858_p1 = p_shl12_fu_1851_p3;

assign p_shl12_fu_1851_p3 = {{src_kernel_win_1_va_7_reg_3129}, {11'd0}};

assign p_shl13_cast_fu_1869_p1 = p_shl13_fu_1862_p3;

assign p_shl13_fu_1862_p3 = {{src_kernel_win_1_va_7_reg_3129}, {2'd0}};

assign p_shl14_cast_fu_2264_p1 = p_shl14_fu_2257_p3;

assign p_shl14_fu_2257_p3 = {{src_kernel_win_1_va_9_reg_3205}, {11'd0}};

assign p_shl15_cast_fu_2275_p1 = p_shl15_fu_2268_p3;

assign p_shl15_fu_2268_p3 = {{src_kernel_win_1_va_9_reg_3205}, {2'd0}};

assign p_shl16_cast_fu_1927_p1 = p_shl16_fu_1919_p3;

assign p_shl16_fu_1919_p3 = {{src_kernel_win_2_va_4_fu_310}, {11'd0}};

assign p_shl17_cast_fu_1939_p1 = p_shl17_fu_1931_p3;

assign p_shl17_fu_1931_p3 = {{src_kernel_win_2_va_4_fu_310}, {2'd0}};

assign p_shl18_cast_fu_1968_p1 = p_shl18_fu_1960_p3;

assign p_shl18_fu_1960_p3 = {{src_kernel_win_2_va_3_fu_306}, {11'd0}};

assign p_shl19_cast_fu_1980_p1 = p_shl19_fu_1972_p3;

assign p_shl19_fu_1972_p3 = {{src_kernel_win_2_va_3_fu_306}, {2'd0}};

assign p_shl1_cast_fu_1649_p1 = p_shl1_fu_1641_p3;

assign p_shl1_fu_1641_p3 = {{src_kernel_win_0_va_4_fu_262}, {11'd0}};

assign p_shl20_cast_fu_1997_p1 = p_shl20_fu_1990_p3;

assign p_shl20_fu_1990_p3 = {{src_kernel_win_2_va_10_reg_3152}, {11'd0}};

assign p_shl21_cast_fu_2008_p1 = p_shl21_fu_2001_p3;

assign p_shl21_fu_2001_p3 = {{src_kernel_win_2_va_10_reg_3152}, {2'd0}};

assign p_shl22_cast_fu_2369_p1 = p_shl22_fu_2362_p3;

assign p_shl22_fu_2362_p3 = {{src_kernel_win_2_va_12_reg_3226}, {11'd0}};

assign p_shl23_cast_fu_2380_p1 = p_shl23_fu_2373_p3;

assign p_shl23_fu_2373_p3 = {{src_kernel_win_2_va_12_reg_3226}, {2'd0}};

assign p_shl2_cast_fu_1661_p1 = p_shl2_fu_1653_p3;

assign p_shl2_fu_1653_p3 = {{src_kernel_win_0_va_4_fu_262}, {2'd0}};

assign p_shl3_cast_fu_1690_p1 = p_shl3_fu_1682_p3;

assign p_shl3_fu_1682_p3 = {{src_kernel_win_0_va_3_fu_258}, {11'd0}};

assign p_shl4_cast_fu_1702_p1 = p_shl4_fu_1694_p3;

assign p_shl4_fu_1694_p3 = {{src_kernel_win_0_va_3_fu_258}, {2'd0}};

assign p_shl5_cast_fu_1719_p1 = p_shl5_fu_1712_p3;

assign p_shl5_fu_1712_p3 = {{src_kernel_win_0_va_7_reg_3106}, {11'd0}};

assign p_shl6_cast_fu_1730_p1 = p_shl6_fu_1723_p3;

assign p_shl6_fu_1723_p3 = {{src_kernel_win_0_va_7_reg_3106}, {2'd0}};

assign p_shl7_cast_fu_2170_p1 = p_shl7_fu_2163_p3;

assign p_shl7_fu_2163_p3 = {{src_kernel_win_0_va_9_reg_3184}, {2'd0}};

assign p_shl8_cast_fu_1788_p1 = p_shl8_fu_1780_p3;

assign p_shl8_fu_1780_p3 = {{src_kernel_win_1_va_4_fu_286}, {11'd0}};

assign p_shl9_cast_fu_1800_p1 = p_shl9_fu_1792_p3;

assign p_shl9_fu_1792_p3 = {{src_kernel_win_1_va_4_fu_286}, {2'd0}};

assign p_shl_cast_fu_2159_p1 = p_shl_fu_2152_p3;

assign p_shl_fu_2152_p3 = {{src_kernel_win_0_va_9_reg_3184}, {11'd0}};

assign r_V_10_0_0_1_cast_fu_1671_p1 = $signed(r_V_10_0_0_1_fu_1665_p2);

assign r_V_10_0_0_1_fu_1665_p2 = (p_shl1_cast_fu_1649_p1 - p_shl2_cast_fu_1661_p1);

assign r_V_10_0_1_1_fu_2603_p0 = r_V_10_0_1_1_fu_2603_p00;

assign r_V_10_0_1_1_fu_2603_p00 = src_kernel_win_0_va_2_fu_254;

assign r_V_10_0_1_1_fu_2603_p1 = 21'd4465;

assign r_V_10_0_1_2_cast_fu_1740_p1 = $signed(r_V_10_0_1_2_fu_1734_p2);

assign r_V_10_0_1_2_fu_1734_p2 = (p_shl5_cast_fu_1719_p1 - p_shl6_cast_fu_1730_p1);

assign r_V_10_0_1_cast_fu_2126_p1 = $signed(r_V_10_0_1_reg_3195);

assign r_V_10_0_1_fu_1706_p2 = (p_shl3_cast_fu_1690_p1 - p_shl4_cast_fu_1702_p1);

assign r_V_10_0_2_1_cast_fu_2180_p1 = $signed(r_V_10_0_2_1_fu_2174_p2);

assign r_V_10_0_2_1_fu_2174_p2 = (p_shl_cast_fu_2159_p1 - p_shl7_cast_fu_2170_p1);

assign r_V_10_1_0_1_cast_fu_1810_p1 = $signed(r_V_10_1_0_1_fu_1804_p2);

assign r_V_10_1_0_1_fu_1804_p2 = (p_shl8_cast_fu_1788_p1 - p_shl9_cast_fu_1800_p1);

assign r_V_10_1_1_1_fu_2609_p0 = r_V_10_1_1_1_fu_2609_p00;

assign r_V_10_1_1_1_fu_2609_p00 = src_kernel_win_1_va_2_fu_278;

assign r_V_10_1_1_1_fu_2609_p1 = 21'd4465;

assign r_V_10_1_1_2_cast_fu_1879_p1 = $signed(r_V_10_1_1_2_fu_1873_p2);

assign r_V_10_1_1_2_fu_1873_p2 = (p_shl12_cast_fu_1858_p1 - p_shl13_cast_fu_1869_p1);

assign r_V_10_1_1_cast_fu_2231_p1 = $signed(r_V_10_1_1_reg_3216);

assign r_V_10_1_1_fu_1845_p2 = (p_shl10_cast_fu_1829_p1 - p_shl11_cast_fu_1841_p1);

assign r_V_10_1_2_1_cast_fu_2285_p1 = $signed(r_V_10_1_2_1_fu_2279_p2);

assign r_V_10_1_2_1_fu_2279_p2 = (p_shl14_cast_fu_2264_p1 - p_shl15_cast_fu_2275_p1);

assign r_V_10_2_0_1_cast_fu_1949_p1 = $signed(r_V_10_2_0_1_fu_1943_p2);

assign r_V_10_2_0_1_fu_1943_p2 = (p_shl16_cast_fu_1927_p1 - p_shl17_cast_fu_1939_p1);

assign r_V_10_2_1_1_fu_2615_p0 = r_V_10_2_1_1_fu_2615_p00;

assign r_V_10_2_1_1_fu_2615_p00 = src_kernel_win_2_va_2_fu_302;

assign r_V_10_2_1_1_fu_2615_p1 = 21'd4465;

assign r_V_10_2_1_2_cast_fu_2018_p1 = $signed(r_V_10_2_1_2_fu_2012_p2);

assign r_V_10_2_1_2_fu_2012_p2 = (p_shl20_cast_fu_1997_p1 - p_shl21_cast_fu_2008_p1);

assign r_V_10_2_1_cast_fu_2336_p1 = $signed(r_V_10_2_1_reg_3237);

assign r_V_10_2_1_fu_1984_p2 = (p_shl18_cast_fu_1968_p1 - p_shl19_cast_fu_1980_p1);

assign r_V_10_2_2_1_cast_fu_2390_p1 = $signed(r_V_10_2_2_1_fu_2384_p2);

assign r_V_10_2_2_1_fu_2384_p2 = (p_shl22_cast_fu_2369_p1 - p_shl23_cast_fu_2380_p1);

assign rev1_fu_975_p2 = (tmp_106_fu_967_p3 ^ 1'd1);

assign rev_fu_713_p2 = (tmp_62_fu_705_p3 ^ 1'd1);

assign row_assign_13_0_0_t_fu_879_p2 = (tmp_44_fu_871_p3 ^ 2'd3);

assign row_assign_13_0_1_t_fu_899_p2 = (tmp_46_fu_891_p3 ^ 2'd3);

assign row_assign_13_0_2_t_fu_919_p2 = (tmp_48_fu_911_p3 ^ 2'd3);

assign src_kernel_win_0_va_6_fu_1216_p3 = ((tmp_36_reg_2972[0:0] === 1'b1) ? tmp_55_fu_1205_p5 : col_buf_0_val_0_0_fu_1121_p3);

assign src_kernel_win_0_va_7_fu_1234_p3 = ((tmp_36_reg_2972[0:0] === 1'b1) ? tmp_56_fu_1223_p5 : col_buf_0_val_1_0_fu_1140_p3);

assign src_kernel_win_0_va_8_fu_1252_p3 = ((tmp_36_reg_2972[0:0] === 1'b1) ? tmp_57_fu_1241_p5 : col_buf_0_val_2_0_fu_1159_p3);

assign src_kernel_win_1_va_6_fu_1391_p3 = ((tmp_36_reg_2972[0:0] === 1'b1) ? tmp_64_fu_1380_p5 : col_buf_1_val_0_0_fu_1296_p3);

assign src_kernel_win_1_va_7_fu_1409_p3 = ((tmp_36_reg_2972[0:0] === 1'b1) ? tmp_67_fu_1398_p5 : col_buf_1_val_1_0_fu_1315_p3);

assign src_kernel_win_1_va_8_fu_1427_p3 = ((tmp_36_reg_2972[0:0] === 1'b1) ? tmp_68_fu_1416_p5 : col_buf_1_val_2_0_fu_1334_p3);

assign src_kernel_win_2_va_10_fu_1566_p3 = ((tmp_36_reg_2972[0:0] === 1'b1) ? tmp_78_fu_1555_p5 : col_buf_2_val_1_0_fu_1481_p3);

assign src_kernel_win_2_va_11_fu_1584_p3 = ((tmp_36_reg_2972[0:0] === 1'b1) ? tmp_79_fu_1573_p5 : col_buf_2_val_2_0_fu_1500_p3);

assign src_kernel_win_2_va_9_fu_1548_p3 = ((tmp_36_reg_2972[0:0] === 1'b1) ? tmp_77_fu_1537_p5 : col_buf_2_val_0_0_fu_1462_p3);

assign t_V_3_cast_fu_925_p1 = t_V_3_reg_610;

assign t_V_cast_fu_633_p1 = t_V_reg_599;

assign tmp42_fu_2133_p2 = (p_Val2_91_0_0_2_ca_fu_2123_p1 + tmp_616_0_1_cast_fu_2129_p1);

assign tmp44_fu_1755_p2 = (tmp56_cast_fu_1752_p1 + tmp_616_0_1_2_cast_c_fu_1744_p1);

assign tmp55_cast_fu_2139_p1 = tmp44_reg_3200;

assign tmp56_cast_fu_1752_p1 = grp_fu_2631_p3;

assign tmp57_cast_fu_2191_p1 = grp_fu_2675_p3;

assign tmp59_fu_2238_p2 = (p_Val2_91_1_0_2_ca_fu_2228_p1 + tmp_616_1_1_cast_fu_2234_p1);

assign tmp60_cast_fu_2244_p1 = tmp60_reg_3221;

assign tmp60_fu_1894_p2 = (tmp61_cast_fu_1891_p1 + tmp_616_1_1_2_cast_c_fu_1883_p1);

assign tmp61_cast_fu_1891_p1 = grp_fu_2649_p3;

assign tmp62_cast_fu_2296_p1 = grp_fu_2684_p3;

assign tmp64_fu_2343_p2 = (p_Val2_91_2_0_2_ca_fu_2333_p1 + tmp_616_2_1_cast_fu_2339_p1);

assign tmp65_cast_fu_2349_p1 = tmp65_reg_3242;

assign tmp65_fu_2033_p2 = (tmp66_cast_fu_2030_p1 + tmp_616_2_1_2_cast_c_fu_2022_p1);

assign tmp66_cast_fu_2030_p1 = grp_fu_2667_p3;

assign tmp67_cast_fu_2401_p1 = grp_fu_2693_p3;

assign tmp_100_fu_821_p3 = p_assign_14_0_2_fu_807_p2[32'd11];

assign tmp_101_fu_829_p1 = t_V_reg_599[1:0];

assign tmp_102_fu_833_p2 = (tmp_101_fu_829_p1 ^ 2'd3);

assign tmp_103_fu_839_p1 = p_assign_14_0_2_fu_807_p2[1:0];

assign tmp_104_fu_843_p3 = ((tmp_100_fu_821_p3[0:0] === 1'b1) ? tmp_102_fu_833_p2 : tmp_103_fu_839_p1);

assign tmp_105_fu_941_p4 = {{t_V_3_reg_610[10:1]}};

assign tmp_106_fu_967_p3 = ImagLoc_x_fu_957_p2[32'd11];

assign tmp_107_fu_993_p3 = ImagLoc_x_fu_957_p2[32'd11];

assign tmp_108_fu_1047_p1 = x_fu_1039_p3[1:0];

assign tmp_112_fu_2441_p3 = p_Val2_6_reg_3247[32'd21];

assign tmp_113_fu_2453_p3 = p_Val2_8_fu_2448_p2[32'd7];

assign tmp_118_fu_2496_p3 = p_Val2_s_reg_3267[32'd21];

assign tmp_119_fu_2508_p3 = p_Val2_15_fu_2503_p2[32'd7];

assign tmp_124_fu_2551_p3 = p_Val2_17_reg_3287[32'd21];

assign tmp_125_fu_2563_p3 = p_Val2_20_fu_2558_p2[32'd7];

assign tmp_31_fu_621_p2 = (tmp_s_reg_588 + 2'd1);

assign tmp_32_fu_627_p2 = ((tmp_s_reg_588 == 2'd2) ? 1'b1 : 1'b0);

assign tmp_34_fu_649_p2 = ((t_V_reg_599 < 11'd1080) ? 1'b1 : 1'b0);

assign tmp_35_fu_677_p2 = ((t_V_reg_599 == 11'd1) ? 1'b1 : 1'b0);

assign tmp_36_fu_689_p2 = ((t_V_reg_599 > 11'd1080) ? 1'b1 : 1'b0);

assign tmp_38_fu_699_p2 = ($signed(12'd4095) + $signed(t_V_cast_fu_633_p1));

assign tmp_39_fu_719_p2 = (($signed(tmp_38_fu_699_p2) < $signed(12'd1080)) ? 1'b1 : 1'b0);

assign tmp_40_fu_753_p2 = (($signed(p_p2_i426_i_fu_745_p3) < $signed(12'd1080)) ? 1'b1 : 1'b0);

assign tmp_41_fu_851_p2 = ($signed(2'd2) - $signed(tmp_66_fu_759_p1));

assign tmp_42_fu_857_p3 = ((tmp_40_fu_753_p2[0:0] === 1'b1) ? tmp_66_fu_759_p1 : tmp_41_fu_851_p2);

assign tmp_43_fu_865_p2 = ($signed(2'd3) + $signed(tmp_61_fu_695_p1));

assign tmp_44_fu_871_p3 = ((or_cond_i425_i_fu_725_p2[0:0] === 1'b1) ? tmp_43_fu_865_p2 : tmp_42_fu_857_p3);

assign tmp_45_fu_885_p2 = (tmp_61_fu_695_p1 ^ 2'd2);

assign tmp_46_fu_891_p3 = ((tmp_69_fu_769_p3[0:0] === 1'b1) ? tmp_91_fu_799_p3 : tmp_45_fu_885_p2);

assign tmp_47_fu_905_p2 = (2'd1 + tmp_61_fu_695_p1);

assign tmp_48_fu_911_p3 = ((tmp_99_fu_813_p3[0:0] === 1'b1) ? tmp_104_fu_843_p3 : tmp_47_fu_905_p2);

assign tmp_49_fu_981_p2 = (($signed(ImagLoc_x_fu_957_p2) < $signed(12'd1920)) ? 1'b1 : 1'b0);

assign tmp_4_i_i1_fu_2493_p1 = tmp_117_reg_3277;

assign tmp_4_i_i2_fu_2548_p1 = tmp_123_reg_3297;

assign tmp_4_i_i_fu_2438_p1 = tmp_111_reg_3257;

assign tmp_50_fu_1019_p2 = (($signed(p_p2_i_i_fu_1007_p3) < $signed(12'd1920)) ? 1'b1 : 1'b0);

assign tmp_51_fu_1064_p1 = $unsigned(x_cast_fu_1061_p1);

assign tmp_528_0_0_not_fu_655_p2 = (tmp_34_fu_649_p2 ^ 1'd1);

assign tmp_572_0_1_fu_683_p2 = ((t_V_reg_599 == 11'd0) ? 1'b1 : 1'b0);

assign tmp_616_0_1_2_cast_c_fu_1744_p1 = $unsigned(r_V_10_0_1_2_cast_fu_1740_p1);

assign tmp_616_0_1_cast_fu_2129_p1 = $unsigned(r_V_10_0_1_cast_fu_2126_p1);

assign tmp_616_1_1_2_cast_c_fu_1883_p1 = $unsigned(r_V_10_1_1_2_cast_fu_1879_p1);

assign tmp_616_1_1_cast_fu_2234_p1 = $unsigned(r_V_10_1_1_cast_fu_2231_p1);

assign tmp_616_2_1_2_cast_c_fu_2022_p1 = $unsigned(r_V_10_2_1_2_cast_fu_2018_p1);

assign tmp_616_2_1_cast_fu_2339_p1 = $unsigned(r_V_10_2_1_cast_fu_2336_p1);

assign tmp_61_fu_695_p1 = t_V_reg_599[1:0];

assign tmp_62_fu_705_p3 = tmp_38_fu_699_p2[32'd11];

assign tmp_65_fu_731_p3 = tmp_38_fu_699_p2[32'd11];

assign tmp_66_fu_759_p1 = p_p2_i426_i_fu_745_p3[1:0];

assign tmp_69_fu_769_p3 = p_assign_14_0_1_fu_763_p2[32'd11];

assign tmp_70_fu_777_p3 = p_assign_14_0_1_fu_763_p2[32'd11];

assign tmp_72_fu_785_p1 = t_V_reg_599[1:0];

assign tmp_74_fu_789_p2 = ($signed(2'd2) - $signed(tmp_72_fu_785_p1));

assign tmp_83_fu_795_p1 = p_assign_14_0_1_fu_763_p2[1:0];

assign tmp_91_fu_799_p3 = ((tmp_70_fu_777_p3[0:0] === 1'b1) ? tmp_74_fu_789_p2 : tmp_83_fu_795_p1);

assign tmp_99_fu_813_p3 = p_assign_14_0_2_fu_807_p2[32'd11];

assign tmp_fu_661_p4 = {{t_V_reg_599[10:1]}};

assign x_cast_fu_1061_p1 = x_reg_3019;

assign x_fu_1039_p3 = ((or_cond_i_i_fu_987_p2[0:0] === 1'b1) ? ImagLoc_x_cast_fu_963_p1 : p_p2_i_i_p_assign_s_fu_1031_p3);

always @ (posedge ap_clk) begin
    r_V_10_0_1_reg_3195[1:0] <= 2'b00;
    r_V_10_1_1_reg_3216[1:0] <= 2'b00;
    r_V_10_2_1_reg_3237[1:0] <= 2'b00;
end

endmodule //Filter2D_1
