// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2018.2
// Copyright (C) 1986-2018 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module Filter2D (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        p_src_data_stream_0_V_dout,
        p_src_data_stream_0_V_empty_n,
        p_src_data_stream_0_V_read,
        p_src_data_stream_1_V_dout,
        p_src_data_stream_1_V_empty_n,
        p_src_data_stream_1_V_read,
        p_src_data_stream_2_V_dout,
        p_src_data_stream_2_V_empty_n,
        p_src_data_stream_2_V_read,
        p_dst_data_stream_0_V_din,
        p_dst_data_stream_0_V_full_n,
        p_dst_data_stream_0_V_write,
        p_dst_data_stream_1_V_din,
        p_dst_data_stream_1_V_full_n,
        p_dst_data_stream_1_V_write,
        p_dst_data_stream_2_V_din,
        p_dst_data_stream_2_V_full_n,
        p_dst_data_stream_2_V_write,
        p_kernel_val_0_V_1_read,
        p_kernel_val_0_V_2_read,
        p_kernel_val_1_V_0_read,
        p_kernel_val_1_V_2_read,
        p_kernel_val_2_V_0_read,
        p_kernel_val_2_V_1_read
);

parameter    ap_ST_fsm_state1 = 5'd1;
parameter    ap_ST_fsm_state2 = 5'd2;
parameter    ap_ST_fsm_state3 = 5'd4;
parameter    ap_ST_fsm_pp0_stage0 = 5'd8;
parameter    ap_ST_fsm_state10 = 5'd16;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
input  [7:0] p_src_data_stream_0_V_dout;
input   p_src_data_stream_0_V_empty_n;
output   p_src_data_stream_0_V_read;
input  [7:0] p_src_data_stream_1_V_dout;
input   p_src_data_stream_1_V_empty_n;
output   p_src_data_stream_1_V_read;
input  [7:0] p_src_data_stream_2_V_dout;
input   p_src_data_stream_2_V_empty_n;
output   p_src_data_stream_2_V_read;
output  [7:0] p_dst_data_stream_0_V_din;
input   p_dst_data_stream_0_V_full_n;
output   p_dst_data_stream_0_V_write;
output  [7:0] p_dst_data_stream_1_V_din;
input   p_dst_data_stream_1_V_full_n;
output   p_dst_data_stream_1_V_write;
output  [7:0] p_dst_data_stream_2_V_din;
input   p_dst_data_stream_2_V_full_n;
output   p_dst_data_stream_2_V_write;
input  [1:0] p_kernel_val_0_V_1_read;
input  [1:0] p_kernel_val_0_V_2_read;
input  [2:0] p_kernel_val_1_V_0_read;
input  [3:0] p_kernel_val_1_V_2_read;
input  [1:0] p_kernel_val_2_V_0_read;
input  [2:0] p_kernel_val_2_V_1_read;

reg ap_done;
reg ap_idle;
reg ap_ready;
reg p_src_data_stream_0_V_read;
reg p_src_data_stream_1_V_read;
reg p_src_data_stream_2_V_read;
reg p_dst_data_stream_0_V_write;
reg p_dst_data_stream_1_V_write;
reg p_dst_data_stream_2_V_write;

(* fsm_encoding = "none" *) reg   [4:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
reg    p_src_data_stream_0_V_blk_n;
reg    ap_enable_reg_pp0_iter2;
wire    ap_block_pp0_stage0;
reg   [0:0] exitcond389_i_reg_2815;
reg   [0:0] exitcond389_i_reg_2815_pp0_iter1_reg;
reg   [0:0] or_cond_i_i_reg_2824;
reg   [0:0] or_cond_i_i_reg_2824_pp0_iter1_reg;
reg   [0:0] icmp_reg_2768;
reg   [0:0] tmp_38_reg_2759;
reg    p_src_data_stream_1_V_blk_n;
reg    p_src_data_stream_2_V_blk_n;
reg    p_dst_data_stream_0_V_blk_n;
reg    ap_enable_reg_pp0_iter5;
reg   [0:0] or_cond_i_reg_2851;
reg   [0:0] or_cond_i_reg_2851_pp0_iter4_reg;
reg    p_dst_data_stream_1_V_blk_n;
reg    p_dst_data_stream_2_V_blk_n;
reg   [10:0] t_V_3_reg_644;
wire   [1:0] tmp_32_fu_655_p2;
wire    ap_CS_fsm_state2;
wire  signed [9:0] OP2_V_0_0_1_cast_fu_667_p1;
reg  signed [9:0] OP2_V_0_0_1_cast_reg_2708;
wire   [0:0] tmp_33_fu_661_p2;
wire  signed [9:0] OP2_V_0_0_2_cast_fu_670_p1;
reg  signed [9:0] OP2_V_0_0_2_cast_reg_2715;
wire  signed [10:0] OP2_V_0_1_cast_fu_673_p1;
reg  signed [10:0] OP2_V_0_1_cast_reg_2722;
wire   [11:0] OP2_V_0_1_2_cast_fu_676_p1;
reg   [11:0] OP2_V_0_1_2_cast_reg_2729;
wire  signed [9:0] OP2_V_0_2_cast_fu_679_p1;
reg  signed [9:0] OP2_V_0_2_cast_reg_2736;
wire   [10:0] OP2_V_0_2_1_cast_fu_682_p1;
reg   [10:0] OP2_V_0_2_1_cast_reg_2743;
wire   [0:0] exitcond390_i_fu_689_p2;
wire    ap_CS_fsm_state3;
wire   [10:0] i_V_fu_695_p2;
reg   [10:0] i_V_reg_2754;
wire   [0:0] tmp_38_fu_701_p2;
wire   [0:0] tmp_384_0_0_not_fu_707_p2;
reg   [0:0] tmp_384_0_0_not_reg_2763;
wire   [0:0] icmp_fu_723_p2;
wire   [0:0] tmp_40_fu_729_p2;
reg   [0:0] tmp_40_reg_2773;
wire   [0:0] tmp_428_0_1_fu_735_p2;
reg   [0:0] tmp_428_0_1_reg_2777;
wire   [0:0] tmp_41_fu_741_p2;
reg   [0:0] tmp_41_reg_2781;
wire   [1:0] row_assign_10_0_0_t_fu_931_p2;
reg   [1:0] row_assign_10_0_0_t_reg_2794;
wire   [1:0] row_assign_10_0_1_t_fu_951_p2;
reg   [1:0] row_assign_10_0_1_t_reg_2801;
wire   [1:0] row_assign_10_0_2_t_fu_971_p2;
reg   [1:0] row_assign_10_0_2_t_reg_2808;
wire   [0:0] exitcond389_i_fu_981_p2;
wire    ap_CS_fsm_pp0_stage0;
wire    ap_block_state4_pp0_stage0_iter0;
wire    ap_block_state5_pp0_stage0_iter1;
reg    ap_predicate_op227_read_state6;
reg    ap_predicate_op239_read_state6;
reg    ap_predicate_op278_read_state6;
reg    ap_predicate_op290_read_state6;
reg    ap_predicate_op326_read_state6;
reg    ap_predicate_op335_read_state6;
reg    ap_block_state6_pp0_stage0_iter2;
wire    ap_block_state7_pp0_stage0_iter3;
wire    ap_block_state8_pp0_stage0_iter4;
reg    ap_block_state9_pp0_stage0_iter5;
reg    ap_block_pp0_stage0_11001;
reg   [0:0] exitcond389_i_reg_2815_pp0_iter2_reg;
wire   [10:0] j_V_fu_987_p2;
reg    ap_enable_reg_pp0_iter0;
wire   [0:0] or_cond_i_i_fu_1039_p2;
wire  signed [13:0] x_fu_1091_p3;
reg  signed [13:0] x_reg_2828;
wire   [1:0] tmp_146_fu_1099_p1;
reg   [1:0] tmp_146_reg_2833;
reg   [1:0] tmp_146_reg_2833_pp0_iter1_reg;
wire   [0:0] brmerge_fu_1103_p2;
reg   [0:0] brmerge_reg_2838;
reg   [0:0] brmerge_reg_2838_pp0_iter1_reg;
wire   [0:0] or_cond_i_fu_1108_p2;
reg   [0:0] or_cond_i_reg_2851_pp0_iter1_reg;
reg   [0:0] or_cond_i_reg_2851_pp0_iter2_reg;
reg   [0:0] or_cond_i_reg_2851_pp0_iter3_reg;
reg   [10:0] k_buf_0_val_3_addr_reg_2855;
reg   [10:0] k_buf_0_val_4_addr_reg_2861;
reg   [10:0] k_buf_0_val_5_addr_reg_2867;
reg   [10:0] k_buf_1_val_3_addr_reg_2873;
reg   [10:0] k_buf_1_val_4_addr_reg_2879;
reg   [10:0] k_buf_1_val_5_addr_reg_2885;
reg   [10:0] k_buf_2_val_3_addr_reg_2891;
reg   [10:0] k_buf_2_val_4_addr_reg_2897;
reg   [10:0] k_buf_2_val_5_addr_reg_2903;
wire   [7:0] src_kernel_win_0_va_23_fu_1268_p3;
reg   [7:0] src_kernel_win_0_va_23_reg_2909;
wire   [7:0] src_kernel_win_0_va_24_fu_1286_p3;
reg   [7:0] src_kernel_win_0_va_24_reg_2916;
wire   [7:0] src_kernel_win_0_va_25_fu_1304_p3;
reg   [7:0] src_kernel_win_0_va_25_reg_2922;
wire  signed [10:0] grp_fu_2397_p3;
reg  signed [10:0] p_Val2_89_0_0_1_reg_2927;
wire   [7:0] src_kernel_win_1_va_23_fu_1460_p3;
reg   [7:0] src_kernel_win_1_va_23_reg_2932;
wire   [7:0] src_kernel_win_1_va_24_fu_1478_p3;
reg   [7:0] src_kernel_win_1_va_24_reg_2939;
wire   [7:0] src_kernel_win_1_va_25_fu_1496_p3;
reg   [7:0] src_kernel_win_1_va_25_reg_2945;
wire  signed [10:0] grp_fu_2404_p3;
reg  signed [10:0] p_Val2_89_1_0_1_reg_2950;
wire   [7:0] src_kernel_win_2_va_26_fu_1634_p3;
reg   [7:0] src_kernel_win_2_va_26_reg_2955;
wire   [7:0] src_kernel_win_2_va_27_fu_1652_p3;
reg   [7:0] src_kernel_win_2_va_27_reg_2962;
wire   [7:0] src_kernel_win_2_va_28_fu_1670_p3;
reg   [7:0] src_kernel_win_2_va_28_reg_2968;
wire  signed [10:0] grp_fu_2411_p3;
reg  signed [10:0] p_Val2_89_2_0_1_reg_2973;
wire   [11:0] p_Val2_89_0_1_1_fu_1775_p2;
reg   [11:0] p_Val2_89_0_1_1_reg_2978;
wire   [11:0] r_V_8_0_1_2_fu_1784_p2;
reg   [11:0] r_V_8_0_1_2_reg_2983;
wire   [7:0] tmp_152_fu_1808_p1;
reg   [7:0] tmp_152_reg_2988;
wire   [10:0] tmp32_fu_1838_p2;
reg   [10:0] tmp32_reg_2993;
wire   [7:0] tmp34_fu_1844_p2;
reg   [7:0] tmp34_reg_2998;
wire   [7:0] tmp36_fu_1850_p2;
reg   [7:0] tmp36_reg_3003;
wire   [11:0] p_Val2_89_1_1_1_fu_1890_p2;
reg   [11:0] p_Val2_89_1_1_1_reg_3008;
wire   [11:0] r_V_8_1_1_2_fu_1899_p2;
reg   [11:0] r_V_8_1_1_2_reg_3013;
wire   [7:0] tmp_161_fu_1923_p1;
reg   [7:0] tmp_161_reg_3018;
wire   [10:0] tmp40_fu_1953_p2;
reg   [10:0] tmp40_reg_3023;
wire   [7:0] tmp42_fu_1959_p2;
reg   [7:0] tmp42_reg_3028;
wire   [7:0] tmp44_fu_1965_p2;
reg   [7:0] tmp44_reg_3033;
wire   [11:0] p_Val2_89_2_1_1_fu_2005_p2;
reg   [11:0] p_Val2_89_2_1_1_reg_3038;
wire   [11:0] r_V_8_2_1_2_fu_2014_p2;
reg   [11:0] r_V_8_2_1_2_reg_3043;
wire   [7:0] tmp_170_fu_2038_p1;
reg   [7:0] tmp_170_reg_3048;
wire   [10:0] tmp48_fu_2068_p2;
reg   [10:0] tmp48_reg_3053;
wire   [7:0] tmp50_fu_2074_p2;
reg   [7:0] tmp50_reg_3058;
wire   [7:0] tmp52_fu_2080_p2;
reg   [7:0] tmp52_reg_3063;
wire   [7:0] p_Val2_33_fu_2229_p3;
reg   [7:0] p_Val2_33_reg_3068;
wire   [7:0] p_Val2_34_fu_2309_p3;
reg   [7:0] p_Val2_34_reg_3073;
wire   [7:0] p_Val2_35_fu_2389_p3;
reg   [7:0] p_Val2_35_reg_3078;
reg    ap_block_pp0_stage0_subdone;
reg    ap_enable_reg_pp0_iter1;
reg    ap_enable_reg_pp0_iter3;
reg    ap_condition_pp0_exit_iter2_state6;
reg    ap_enable_reg_pp0_iter4;
wire   [10:0] k_buf_0_val_3_address0;
reg    k_buf_0_val_3_ce0;
wire   [7:0] k_buf_0_val_3_q0;
reg    k_buf_0_val_3_ce1;
reg    k_buf_0_val_3_we1;
wire   [10:0] k_buf_0_val_4_address0;
reg    k_buf_0_val_4_ce0;
wire   [7:0] k_buf_0_val_4_q0;
reg    k_buf_0_val_4_ce1;
reg    k_buf_0_val_4_we1;
reg   [7:0] k_buf_0_val_4_d1;
wire   [10:0] k_buf_0_val_5_address0;
reg    k_buf_0_val_5_ce0;
wire   [7:0] k_buf_0_val_5_q0;
reg    k_buf_0_val_5_ce1;
reg    k_buf_0_val_5_we1;
reg   [7:0] k_buf_0_val_5_d1;
wire   [10:0] k_buf_1_val_3_address0;
reg    k_buf_1_val_3_ce0;
wire   [7:0] k_buf_1_val_3_q0;
reg    k_buf_1_val_3_ce1;
reg    k_buf_1_val_3_we1;
wire   [10:0] k_buf_1_val_4_address0;
reg    k_buf_1_val_4_ce0;
wire   [7:0] k_buf_1_val_4_q0;
reg    k_buf_1_val_4_ce1;
reg    k_buf_1_val_4_we1;
reg   [7:0] k_buf_1_val_4_d1;
wire   [10:0] k_buf_1_val_5_address0;
reg    k_buf_1_val_5_ce0;
wire   [7:0] k_buf_1_val_5_q0;
reg    k_buf_1_val_5_ce1;
reg    k_buf_1_val_5_we1;
reg   [7:0] k_buf_1_val_5_d1;
wire   [10:0] k_buf_2_val_3_address0;
reg    k_buf_2_val_3_ce0;
wire   [7:0] k_buf_2_val_3_q0;
reg    k_buf_2_val_3_ce1;
reg    k_buf_2_val_3_we1;
wire   [10:0] k_buf_2_val_4_address0;
reg    k_buf_2_val_4_ce0;
wire   [7:0] k_buf_2_val_4_q0;
reg    k_buf_2_val_4_ce1;
reg    k_buf_2_val_4_we1;
reg   [7:0] k_buf_2_val_4_d1;
wire   [10:0] k_buf_2_val_5_address0;
reg    k_buf_2_val_5_ce0;
wire   [7:0] k_buf_2_val_5_q0;
reg    k_buf_2_val_5_ce1;
reg    k_buf_2_val_5_we1;
reg   [7:0] k_buf_2_val_5_d1;
reg   [1:0] tmp_s_reg_622;
reg   [10:0] t_V_reg_633;
wire    ap_CS_fsm_state10;
wire   [63:0] tmp_61_fu_1116_p1;
reg    ap_block_pp0_stage0_01001;
reg   [7:0] src_kernel_win_0_va_fu_244;
reg   [7:0] src_kernel_win_0_va_18_fu_248;
reg   [7:0] src_kernel_win_0_va_19_fu_252;
reg   [7:0] src_kernel_win_0_va_20_fu_256;
reg   [7:0] src_kernel_win_0_va_21_fu_260;
reg   [7:0] src_kernel_win_0_va_22_fu_264;
reg   [7:0] src_kernel_win_1_va_fu_268;
reg   [7:0] src_kernel_win_1_va_18_fu_272;
reg   [7:0] src_kernel_win_1_va_19_fu_276;
reg   [7:0] src_kernel_win_1_va_20_fu_280;
reg   [7:0] src_kernel_win_1_va_21_fu_284;
reg   [7:0] src_kernel_win_1_va_22_fu_288;
reg   [7:0] src_kernel_win_2_va_fu_292;
reg   [7:0] src_kernel_win_2_va_18_fu_296;
reg   [7:0] src_kernel_win_2_va_19_fu_300;
reg   [7:0] src_kernel_win_2_va_20_fu_304;
reg   [7:0] src_kernel_win_2_va_21_fu_308;
reg   [7:0] src_kernel_win_2_va_22_fu_312;
reg   [7:0] right_border_buf_0_s_fu_316;
wire   [7:0] col_buf_0_val_0_0_fu_1173_p3;
reg   [7:0] right_border_buf_0_15_fu_320;
reg   [7:0] right_border_buf_2_s_fu_324;
reg   [7:0] right_border_buf_0_16_fu_328;
wire   [7:0] col_buf_0_val_1_0_fu_1192_p3;
reg   [7:0] right_border_buf_0_17_fu_332;
reg   [7:0] right_border_buf_2_12_fu_336;
wire   [7:0] col_buf_2_val_2_0_fu_1586_p3;
reg   [7:0] right_border_buf_0_18_fu_340;
wire   [7:0] col_buf_0_val_2_0_fu_1211_p3;
reg   [7:0] right_border_buf_0_19_fu_344;
reg   [7:0] right_border_buf_2_13_fu_348;
reg   [7:0] right_border_buf_1_s_fu_352;
wire   [7:0] col_buf_1_val_0_0_fu_1365_p3;
reg   [7:0] right_border_buf_1_15_fu_356;
reg   [7:0] right_border_buf_2_14_fu_360;
wire   [7:0] col_buf_2_val_1_0_fu_1567_p3;
reg   [7:0] right_border_buf_1_16_fu_364;
wire   [7:0] col_buf_1_val_1_0_fu_1384_p3;
reg   [7:0] right_border_buf_1_17_fu_368;
reg   [7:0] right_border_buf_2_15_fu_372;
reg   [7:0] right_border_buf_1_18_fu_376;
wire   [7:0] col_buf_1_val_2_0_fu_1403_p3;
reg   [7:0] right_border_buf_1_19_fu_380;
reg   [7:0] right_border_buf_2_16_fu_384;
wire   [7:0] col_buf_2_val_0_0_fu_1548_p3;
wire   [9:0] tmp_fu_713_p4;
wire   [11:0] t_V_cast_fu_685_p1;
wire   [11:0] tmp_42_fu_751_p2;
wire   [0:0] tmp_128_fu_757_p3;
wire   [0:0] tmp_44_fu_771_p2;
wire   [0:0] rev_fu_765_p2;
wire   [0:0] tmp_129_fu_783_p3;
wire   [11:0] p_assign_7_fu_791_p2;
wire   [11:0] p_p2_i426_i_fu_797_p3;
wire   [11:0] p_assign_6_0_1_fu_815_p2;
wire   [1:0] tmp_133_fu_837_p1;
wire   [0:0] tmp_132_fu_829_p3;
wire   [1:0] tmp_134_fu_841_p2;
wire   [1:0] tmp_135_fu_847_p1;
wire   [11:0] p_assign_6_0_2_fu_859_p2;
wire   [1:0] tmp_139_fu_881_p1;
wire   [0:0] tmp_138_fu_873_p3;
wire   [1:0] tmp_140_fu_885_p2;
wire   [1:0] tmp_141_fu_891_p1;
wire   [1:0] tmp_130_fu_811_p1;
wire   [0:0] tmp_46_fu_805_p2;
wire   [1:0] tmp_66_fu_903_p2;
wire   [1:0] tmp_127_fu_747_p1;
wire   [0:0] or_cond_i425_i_fu_777_p2;
wire   [1:0] tmp_68_fu_917_p2;
wire   [1:0] tmp_67_fu_909_p3;
wire   [1:0] tmp_69_fu_923_p3;
wire   [0:0] tmp_131_fu_821_p3;
wire   [1:0] tmp_136_fu_851_p3;
wire   [1:0] tmp_74_fu_937_p2;
wire   [1:0] tmp_75_fu_943_p3;
wire   [0:0] tmp_137_fu_865_p3;
wire   [1:0] tmp_142_fu_895_p3;
wire   [1:0] tmp_80_fu_957_p2;
wire   [1:0] tmp_81_fu_963_p3;
wire   [9:0] tmp_143_fu_993_p4;
wire   [11:0] t_V_3_cast_fu_977_p1;
wire  signed [11:0] ImagLoc_x_fu_1009_p2;
wire   [0:0] tmp_144_fu_1019_p3;
wire   [0:0] tmp_51_fu_1033_p2;
wire   [0:0] rev2_fu_1027_p2;
wire   [0:0] tmp_145_fu_1045_p3;
wire   [11:0] p_assign_1_fu_1053_p2;
wire  signed [11:0] p_p2_i_i_fu_1059_p3;
wire  signed [13:0] p_p2_i_i_cast_fu_1067_p1;
wire   [0:0] tmp_53_fu_1071_p2;
wire   [13:0] p_assign_2_fu_1077_p2;
wire  signed [13:0] ImagLoc_x_cast_fu_1015_p1;
wire   [13:0] p_p2_i_i_p_assign_2_fu_1083_p3;
wire   [0:0] icmp2_fu_1003_p2;
wire  signed [31:0] x_cast_fu_1113_p1;
wire   [1:0] col_assign_3_0_t_fu_1156_p2;
wire   [7:0] tmp_62_fu_1161_p5;
wire   [7:0] tmp_63_fu_1180_p5;
wire   [7:0] tmp_64_fu_1199_p5;
wire   [7:0] tmp_70_fu_1257_p5;
wire   [7:0] tmp_76_fu_1275_p5;
wire   [7:0] tmp_82_fu_1293_p5;
wire   [8:0] OP1_V_0_0_cast_fu_1317_p1;
wire  signed [8:0] r_V_8_fu_1321_p2;
wire   [7:0] tmp_85_fu_1353_p5;
wire   [7:0] tmp_86_fu_1372_p5;
wire   [7:0] tmp_87_fu_1391_p5;
wire   [7:0] tmp_88_fu_1449_p5;
wire   [7:0] tmp_89_fu_1467_p5;
wire   [7:0] tmp_90_fu_1485_p5;
wire   [8:0] OP1_V_1_0_cast_fu_1509_p1;
wire  signed [8:0] r_V_8_1_fu_1513_p2;
wire   [7:0] tmp_93_fu_1536_p5;
wire   [7:0] tmp_94_fu_1555_p5;
wire   [7:0] tmp_95_fu_1574_p5;
wire   [7:0] tmp_96_fu_1623_p5;
wire   [7:0] tmp_97_fu_1641_p5;
wire   [7:0] tmp_98_fu_1659_p5;
wire   [8:0] OP1_V_2_0_cast_fu_1683_p1;
wire  signed [8:0] r_V_8_2_fu_1687_p2;
wire  signed [10:0] grp_fu_2418_p3;
wire  signed [2:0] r_V_8_0_1_fu_1759_p0;
wire   [7:0] r_V_8_0_1_fu_1759_p1;
wire  signed [10:0] r_V_8_0_1_fu_1759_p2;
wire  signed [11:0] tmp_472_0_1_cast_cas_fu_1764_p1;
wire  signed [11:0] p_Val2_89_0_0_2_ca_fu_1752_p1;
wire   [3:0] r_V_8_0_1_2_fu_1784_p0;
wire   [7:0] r_V_8_0_1_2_fu_1784_p1;
wire   [7:0] tmp_150_fu_1772_p1;
wire   [7:0] tmp_149_fu_1768_p1;
wire  signed [1:0] r_V_8_0_2_fu_1803_p0;
wire   [7:0] r_V_8_0_2_fu_1803_p1;
wire   [9:0] r_V_8_0_2_fu_1803_p2;
wire   [2:0] r_V_8_0_2_1_fu_1816_p0;
wire   [7:0] r_V_8_0_2_1_fu_1816_p1;
wire   [10:0] r_V_8_0_2_1_fu_1816_p2;
wire   [9:0] tmp_472_0_2_2_cast_c_fu_1825_p1;
wire   [9:0] tmp33_fu_1828_p2;
wire  signed [10:0] tmp33_cast_fu_1834_p1;
wire   [7:0] tmp_83_fu_1793_p2;
wire   [7:0] tmp_151_fu_1789_p1;
wire   [7:0] tmp_153_fu_1821_p1;
wire  signed [10:0] grp_fu_2426_p3;
wire  signed [2:0] r_V_8_1_1_fu_1874_p0;
wire   [7:0] r_V_8_1_1_fu_1874_p1;
wire  signed [10:0] r_V_8_1_1_fu_1874_p2;
wire  signed [11:0] tmp_472_1_1_cast_cas_fu_1879_p1;
wire  signed [11:0] p_Val2_89_1_0_2_ca_fu_1867_p1;
wire   [3:0] r_V_8_1_1_2_fu_1899_p0;
wire   [7:0] r_V_8_1_1_2_fu_1899_p1;
wire   [7:0] tmp_159_fu_1887_p1;
wire   [7:0] tmp_158_fu_1883_p1;
wire  signed [1:0] r_V_8_1_2_fu_1918_p0;
wire   [7:0] r_V_8_1_2_fu_1918_p1;
wire   [9:0] r_V_8_1_2_fu_1918_p2;
wire   [2:0] r_V_8_1_2_1_fu_1931_p0;
wire   [7:0] r_V_8_1_2_1_fu_1931_p1;
wire   [10:0] r_V_8_1_2_1_fu_1931_p2;
wire   [9:0] tmp_472_1_2_2_cast_c_fu_1940_p1;
wire   [9:0] tmp41_fu_1943_p2;
wire  signed [10:0] tmp41_cast_fu_1949_p1;
wire   [7:0] tmp_91_fu_1908_p2;
wire   [7:0] tmp_160_fu_1904_p1;
wire   [7:0] tmp_162_fu_1936_p1;
wire  signed [10:0] grp_fu_2434_p3;
wire  signed [2:0] r_V_8_2_1_fu_1989_p0;
wire   [7:0] r_V_8_2_1_fu_1989_p1;
wire  signed [10:0] r_V_8_2_1_fu_1989_p2;
wire  signed [11:0] tmp_472_2_1_cast_cas_fu_1994_p1;
wire  signed [11:0] p_Val2_89_2_0_2_ca_fu_1982_p1;
wire   [3:0] r_V_8_2_1_2_fu_2014_p0;
wire   [7:0] r_V_8_2_1_2_fu_2014_p1;
wire   [7:0] tmp_168_fu_2002_p1;
wire   [7:0] tmp_167_fu_1998_p1;
wire  signed [1:0] r_V_8_2_2_fu_2033_p0;
wire   [7:0] r_V_8_2_2_fu_2033_p1;
wire   [9:0] r_V_8_2_2_fu_2033_p2;
wire   [2:0] r_V_8_2_2_1_fu_2046_p0;
wire   [7:0] r_V_8_2_2_1_fu_2046_p1;
wire   [10:0] r_V_8_2_2_1_fu_2046_p2;
wire   [9:0] tmp_472_2_2_2_cast_c_fu_2055_p1;
wire   [9:0] tmp49_fu_2058_p2;
wire  signed [10:0] tmp49_cast_fu_2064_p1;
wire   [7:0] tmp_99_fu_2023_p2;
wire   [7:0] tmp_169_fu_2019_p1;
wire   [7:0] tmp_171_fu_2051_p1;
wire   [11:0] tmp31_fu_2157_p2;
wire  signed [11:0] tmp32_cast_fu_2161_p1;
wire   [11:0] p_Val2_27_fu_2164_p2;
wire   [7:0] tmp35_fu_2178_p2;
wire   [0:0] isneg_fu_2170_p3;
wire   [3:0] tmp_84_fu_2187_p4;
wire   [0:0] not_i_i_i_fu_2203_p2;
wire   [0:0] tmp_i_i_fu_2197_p2;
wire   [0:0] overflow_fu_2209_p2;
wire   [0:0] tmp_i_i_78_fu_2223_p2;
wire   [7:0] p_mux_i_i_cast_fu_2215_p3;
wire   [7:0] p_Val2_7_fu_2182_p2;
wire   [11:0] tmp39_fu_2237_p2;
wire  signed [11:0] tmp40_cast_fu_2241_p1;
wire   [11:0] p_Val2_29_fu_2244_p2;
wire   [7:0] tmp43_fu_2258_p2;
wire   [0:0] isneg_1_fu_2250_p3;
wire   [3:0] tmp_92_fu_2267_p4;
wire   [0:0] not_i_i_i5_fu_2283_p2;
wire   [0:0] tmp_i_i4_fu_2277_p2;
wire   [0:0] overflow_1_fu_2289_p2;
wire   [0:0] tmp_i_i8_fu_2303_p2;
wire   [7:0] p_mux_i_i7_cast_fu_2295_p3;
wire   [7:0] p_Val2_8_fu_2262_p2;
wire   [11:0] tmp47_fu_2317_p2;
wire  signed [11:0] tmp48_cast_fu_2321_p1;
wire   [11:0] p_Val2_s_fu_2324_p2;
wire   [7:0] tmp51_fu_2338_p2;
wire   [0:0] isneg_2_fu_2330_p3;
wire   [3:0] tmp_100_fu_2347_p4;
wire   [0:0] not_i_i_i1_fu_2363_p2;
wire   [0:0] tmp_i_i1_fu_2357_p2;
wire   [0:0] overflow_2_fu_2369_p2;
wire   [0:0] tmp_i_i1_79_fu_2383_p2;
wire   [7:0] p_mux_i_i16_cast_fu_2375_p3;
wire   [7:0] p_Val2_31_fu_2342_p2;
wire  signed [1:0] grp_fu_2397_p0;
wire   [7:0] grp_fu_2397_p1;
wire  signed [1:0] grp_fu_2404_p0;
wire   [7:0] grp_fu_2404_p1;
wire  signed [1:0] grp_fu_2411_p0;
wire   [7:0] grp_fu_2411_p1;
wire  signed [1:0] grp_fu_2418_p0;
wire   [7:0] grp_fu_2418_p1;
wire  signed [1:0] grp_fu_2426_p0;
wire   [7:0] grp_fu_2426_p1;
wire  signed [1:0] grp_fu_2434_p0;
wire   [7:0] grp_fu_2434_p1;
reg   [4:0] ap_NS_fsm;
reg    ap_idle_pp0;
wire    ap_enable_pp0;
wire   [9:0] grp_fu_2397_p10;
wire   [9:0] grp_fu_2404_p10;
wire   [9:0] grp_fu_2411_p10;
wire   [9:0] grp_fu_2418_p10;
wire   [9:0] grp_fu_2426_p10;
wire   [9:0] grp_fu_2434_p10;
wire   [11:0] r_V_8_0_1_2_fu_1784_p10;
wire   [10:0] r_V_8_0_1_fu_1759_p10;
wire   [10:0] r_V_8_0_2_1_fu_1816_p10;
wire   [9:0] r_V_8_0_2_fu_1803_p10;
wire   [11:0] r_V_8_1_1_2_fu_1899_p10;
wire   [10:0] r_V_8_1_1_fu_1874_p10;
wire   [10:0] r_V_8_1_2_1_fu_1931_p10;
wire   [9:0] r_V_8_1_2_fu_1918_p10;
wire   [11:0] r_V_8_2_1_2_fu_2014_p10;
wire   [10:0] r_V_8_2_1_fu_1989_p10;
wire   [10:0] r_V_8_2_2_1_fu_2046_p10;
wire   [9:0] r_V_8_2_2_fu_2033_p10;
reg    ap_condition_655;
reg    ap_condition_649;

// power-on initialization
initial begin
#0 ap_CS_fsm = 5'd1;
#0 ap_enable_reg_pp0_iter2 = 1'b0;
#0 ap_enable_reg_pp0_iter5 = 1'b0;
#0 ap_enable_reg_pp0_iter0 = 1'b0;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter3 = 1'b0;
#0 ap_enable_reg_pp0_iter4 = 1'b0;
end

Filter2D_1_k_buf_eOg #(
    .DataWidth( 8 ),
    .AddressRange( 1920 ),
    .AddressWidth( 11 ))
k_buf_0_val_3_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(k_buf_0_val_3_address0),
    .ce0(k_buf_0_val_3_ce0),
    .q0(k_buf_0_val_3_q0),
    .address1(k_buf_0_val_3_addr_reg_2855),
    .ce1(k_buf_0_val_3_ce1),
    .we1(k_buf_0_val_3_we1),
    .d1(p_src_data_stream_0_V_dout)
);

Filter2D_1_k_buf_eOg #(
    .DataWidth( 8 ),
    .AddressRange( 1920 ),
    .AddressWidth( 11 ))
k_buf_0_val_4_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(k_buf_0_val_4_address0),
    .ce0(k_buf_0_val_4_ce0),
    .q0(k_buf_0_val_4_q0),
    .address1(k_buf_0_val_4_addr_reg_2861),
    .ce1(k_buf_0_val_4_ce1),
    .we1(k_buf_0_val_4_we1),
    .d1(k_buf_0_val_4_d1)
);

Filter2D_1_k_buf_eOg #(
    .DataWidth( 8 ),
    .AddressRange( 1920 ),
    .AddressWidth( 11 ))
k_buf_0_val_5_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(k_buf_0_val_5_address0),
    .ce0(k_buf_0_val_5_ce0),
    .q0(k_buf_0_val_5_q0),
    .address1(k_buf_0_val_5_addr_reg_2867),
    .ce1(k_buf_0_val_5_ce1),
    .we1(k_buf_0_val_5_we1),
    .d1(k_buf_0_val_5_d1)
);

Filter2D_1_k_buf_eOg #(
    .DataWidth( 8 ),
    .AddressRange( 1920 ),
    .AddressWidth( 11 ))
k_buf_1_val_3_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(k_buf_1_val_3_address0),
    .ce0(k_buf_1_val_3_ce0),
    .q0(k_buf_1_val_3_q0),
    .address1(k_buf_1_val_3_addr_reg_2873),
    .ce1(k_buf_1_val_3_ce1),
    .we1(k_buf_1_val_3_we1),
    .d1(p_src_data_stream_1_V_dout)
);

Filter2D_1_k_buf_eOg #(
    .DataWidth( 8 ),
    .AddressRange( 1920 ),
    .AddressWidth( 11 ))
k_buf_1_val_4_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(k_buf_1_val_4_address0),
    .ce0(k_buf_1_val_4_ce0),
    .q0(k_buf_1_val_4_q0),
    .address1(k_buf_1_val_4_addr_reg_2879),
    .ce1(k_buf_1_val_4_ce1),
    .we1(k_buf_1_val_4_we1),
    .d1(k_buf_1_val_4_d1)
);

Filter2D_1_k_buf_eOg #(
    .DataWidth( 8 ),
    .AddressRange( 1920 ),
    .AddressWidth( 11 ))
k_buf_1_val_5_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(k_buf_1_val_5_address0),
    .ce0(k_buf_1_val_5_ce0),
    .q0(k_buf_1_val_5_q0),
    .address1(k_buf_1_val_5_addr_reg_2885),
    .ce1(k_buf_1_val_5_ce1),
    .we1(k_buf_1_val_5_we1),
    .d1(k_buf_1_val_5_d1)
);

Filter2D_1_k_buf_eOg #(
    .DataWidth( 8 ),
    .AddressRange( 1920 ),
    .AddressWidth( 11 ))
k_buf_2_val_3_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(k_buf_2_val_3_address0),
    .ce0(k_buf_2_val_3_ce0),
    .q0(k_buf_2_val_3_q0),
    .address1(k_buf_2_val_3_addr_reg_2891),
    .ce1(k_buf_2_val_3_ce1),
    .we1(k_buf_2_val_3_we1),
    .d1(p_src_data_stream_2_V_dout)
);

Filter2D_1_k_buf_eOg #(
    .DataWidth( 8 ),
    .AddressRange( 1920 ),
    .AddressWidth( 11 ))
k_buf_2_val_4_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(k_buf_2_val_4_address0),
    .ce0(k_buf_2_val_4_ce0),
    .q0(k_buf_2_val_4_q0),
    .address1(k_buf_2_val_4_addr_reg_2897),
    .ce1(k_buf_2_val_4_ce1),
    .we1(k_buf_2_val_4_we1),
    .d1(k_buf_2_val_4_d1)
);

Filter2D_1_k_buf_eOg #(
    .DataWidth( 8 ),
    .AddressRange( 1920 ),
    .AddressWidth( 11 ))
k_buf_2_val_5_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(k_buf_2_val_5_address0),
    .ce0(k_buf_2_val_5_ce0),
    .q0(k_buf_2_val_5_q0),
    .address1(k_buf_2_val_5_addr_reg_2903),
    .ce1(k_buf_2_val_5_ce1),
    .we1(k_buf_2_val_5_we1),
    .d1(k_buf_2_val_5_d1)
);

SobelFilter_mux_3ncg #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 8 ),
    .din2_WIDTH( 8 ),
    .din3_WIDTH( 2 ),
    .dout_WIDTH( 8 ))
SobelFilter_mux_3ncg_U84(
    .din0(right_border_buf_0_s_fu_316),
    .din1(right_border_buf_0_15_fu_320),
    .din2(8'd0),
    .din3(col_assign_3_0_t_fu_1156_p2),
    .dout(tmp_62_fu_1161_p5)
);

SobelFilter_mux_3ncg #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 8 ),
    .din2_WIDTH( 8 ),
    .din3_WIDTH( 2 ),
    .dout_WIDTH( 8 ))
SobelFilter_mux_3ncg_U85(
    .din0(right_border_buf_0_16_fu_328),
    .din1(right_border_buf_0_17_fu_332),
    .din2(8'd0),
    .din3(col_assign_3_0_t_fu_1156_p2),
    .dout(tmp_63_fu_1180_p5)
);

SobelFilter_mux_3ncg #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 8 ),
    .din2_WIDTH( 8 ),
    .din3_WIDTH( 2 ),
    .dout_WIDTH( 8 ))
SobelFilter_mux_3ncg_U86(
    .din0(right_border_buf_0_18_fu_340),
    .din1(right_border_buf_0_19_fu_344),
    .din2(8'd0),
    .din3(col_assign_3_0_t_fu_1156_p2),
    .dout(tmp_64_fu_1199_p5)
);

SobelFilter_mux_3ncg #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 8 ),
    .din2_WIDTH( 8 ),
    .din3_WIDTH( 2 ),
    .dout_WIDTH( 8 ))
SobelFilter_mux_3ncg_U87(
    .din0(col_buf_0_val_0_0_fu_1173_p3),
    .din1(col_buf_0_val_1_0_fu_1192_p3),
    .din2(col_buf_0_val_2_0_fu_1211_p3),
    .din3(row_assign_10_0_0_t_reg_2794),
    .dout(tmp_70_fu_1257_p5)
);

SobelFilter_mux_3ncg #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 8 ),
    .din2_WIDTH( 8 ),
    .din3_WIDTH( 2 ),
    .dout_WIDTH( 8 ))
SobelFilter_mux_3ncg_U88(
    .din0(col_buf_0_val_0_0_fu_1173_p3),
    .din1(col_buf_0_val_1_0_fu_1192_p3),
    .din2(col_buf_0_val_2_0_fu_1211_p3),
    .din3(row_assign_10_0_1_t_reg_2801),
    .dout(tmp_76_fu_1275_p5)
);

SobelFilter_mux_3ncg #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 8 ),
    .din2_WIDTH( 8 ),
    .din3_WIDTH( 2 ),
    .dout_WIDTH( 8 ))
SobelFilter_mux_3ncg_U89(
    .din0(col_buf_0_val_0_0_fu_1173_p3),
    .din1(col_buf_0_val_1_0_fu_1192_p3),
    .din2(col_buf_0_val_2_0_fu_1211_p3),
    .din3(row_assign_10_0_2_t_reg_2808),
    .dout(tmp_82_fu_1293_p5)
);

SobelFilter_mux_3ncg #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 8 ),
    .din2_WIDTH( 8 ),
    .din3_WIDTH( 2 ),
    .dout_WIDTH( 8 ))
SobelFilter_mux_3ncg_U90(
    .din0(right_border_buf_1_s_fu_352),
    .din1(right_border_buf_1_15_fu_356),
    .din2(8'd0),
    .din3(col_assign_3_0_t_fu_1156_p2),
    .dout(tmp_85_fu_1353_p5)
);

SobelFilter_mux_3ncg #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 8 ),
    .din2_WIDTH( 8 ),
    .din3_WIDTH( 2 ),
    .dout_WIDTH( 8 ))
SobelFilter_mux_3ncg_U91(
    .din0(right_border_buf_1_16_fu_364),
    .din1(right_border_buf_1_17_fu_368),
    .din2(8'd0),
    .din3(col_assign_3_0_t_fu_1156_p2),
    .dout(tmp_86_fu_1372_p5)
);

SobelFilter_mux_3ncg #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 8 ),
    .din2_WIDTH( 8 ),
    .din3_WIDTH( 2 ),
    .dout_WIDTH( 8 ))
SobelFilter_mux_3ncg_U92(
    .din0(right_border_buf_1_18_fu_376),
    .din1(right_border_buf_1_19_fu_380),
    .din2(8'd0),
    .din3(col_assign_3_0_t_fu_1156_p2),
    .dout(tmp_87_fu_1391_p5)
);

SobelFilter_mux_3ncg #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 8 ),
    .din2_WIDTH( 8 ),
    .din3_WIDTH( 2 ),
    .dout_WIDTH( 8 ))
SobelFilter_mux_3ncg_U93(
    .din0(col_buf_1_val_0_0_fu_1365_p3),
    .din1(col_buf_1_val_1_0_fu_1384_p3),
    .din2(col_buf_1_val_2_0_fu_1403_p3),
    .din3(row_assign_10_0_0_t_reg_2794),
    .dout(tmp_88_fu_1449_p5)
);

SobelFilter_mux_3ncg #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 8 ),
    .din2_WIDTH( 8 ),
    .din3_WIDTH( 2 ),
    .dout_WIDTH( 8 ))
SobelFilter_mux_3ncg_U94(
    .din0(col_buf_1_val_0_0_fu_1365_p3),
    .din1(col_buf_1_val_1_0_fu_1384_p3),
    .din2(col_buf_1_val_2_0_fu_1403_p3),
    .din3(row_assign_10_0_1_t_reg_2801),
    .dout(tmp_89_fu_1467_p5)
);

SobelFilter_mux_3ncg #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 8 ),
    .din2_WIDTH( 8 ),
    .din3_WIDTH( 2 ),
    .dout_WIDTH( 8 ))
SobelFilter_mux_3ncg_U95(
    .din0(col_buf_1_val_0_0_fu_1365_p3),
    .din1(col_buf_1_val_1_0_fu_1384_p3),
    .din2(col_buf_1_val_2_0_fu_1403_p3),
    .din3(row_assign_10_0_2_t_reg_2808),
    .dout(tmp_90_fu_1485_p5)
);

SobelFilter_mux_3ncg #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 8 ),
    .din2_WIDTH( 8 ),
    .din3_WIDTH( 2 ),
    .dout_WIDTH( 8 ))
SobelFilter_mux_3ncg_U96(
    .din0(right_border_buf_2_16_fu_384),
    .din1(right_border_buf_2_15_fu_372),
    .din2(8'd0),
    .din3(col_assign_3_0_t_fu_1156_p2),
    .dout(tmp_93_fu_1536_p5)
);

SobelFilter_mux_3ncg #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 8 ),
    .din2_WIDTH( 8 ),
    .din3_WIDTH( 2 ),
    .dout_WIDTH( 8 ))
SobelFilter_mux_3ncg_U97(
    .din0(right_border_buf_2_14_fu_360),
    .din1(right_border_buf_2_13_fu_348),
    .din2(8'd0),
    .din3(col_assign_3_0_t_fu_1156_p2),
    .dout(tmp_94_fu_1555_p5)
);

SobelFilter_mux_3ncg #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 8 ),
    .din2_WIDTH( 8 ),
    .din3_WIDTH( 2 ),
    .dout_WIDTH( 8 ))
SobelFilter_mux_3ncg_U98(
    .din0(right_border_buf_2_12_fu_336),
    .din1(right_border_buf_2_s_fu_324),
    .din2(8'd0),
    .din3(col_assign_3_0_t_fu_1156_p2),
    .dout(tmp_95_fu_1574_p5)
);

SobelFilter_mux_3ncg #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 8 ),
    .din2_WIDTH( 8 ),
    .din3_WIDTH( 2 ),
    .dout_WIDTH( 8 ))
SobelFilter_mux_3ncg_U99(
    .din0(col_buf_2_val_0_0_fu_1548_p3),
    .din1(col_buf_2_val_1_0_fu_1567_p3),
    .din2(col_buf_2_val_2_0_fu_1586_p3),
    .din3(row_assign_10_0_0_t_reg_2794),
    .dout(tmp_96_fu_1623_p5)
);

SobelFilter_mux_3ncg #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 8 ),
    .din2_WIDTH( 8 ),
    .din3_WIDTH( 2 ),
    .dout_WIDTH( 8 ))
SobelFilter_mux_3ncg_U100(
    .din0(col_buf_2_val_0_0_fu_1548_p3),
    .din1(col_buf_2_val_1_0_fu_1567_p3),
    .din2(col_buf_2_val_2_0_fu_1586_p3),
    .din3(row_assign_10_0_1_t_reg_2801),
    .dout(tmp_97_fu_1641_p5)
);

SobelFilter_mux_3ncg #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 8 ),
    .din2_WIDTH( 8 ),
    .din3_WIDTH( 2 ),
    .dout_WIDTH( 8 ))
SobelFilter_mux_3ncg_U101(
    .din0(col_buf_2_val_0_0_fu_1548_p3),
    .din1(col_buf_2_val_1_0_fu_1567_p3),
    .din2(col_buf_2_val_2_0_fu_1586_p3),
    .din3(row_assign_10_0_2_t_reg_2808),
    .dout(tmp_98_fu_1659_p5)
);

SobelFilter_mac_mBew #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 2 ),
    .din1_WIDTH( 8 ),
    .din2_WIDTH( 9 ),
    .dout_WIDTH( 11 ))
SobelFilter_mac_mBew_U102(
    .din0(grp_fu_2397_p0),
    .din1(grp_fu_2397_p1),
    .din2(r_V_8_fu_1321_p2),
    .dout(grp_fu_2397_p3)
);

SobelFilter_mac_mBew #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 2 ),
    .din1_WIDTH( 8 ),
    .din2_WIDTH( 9 ),
    .dout_WIDTH( 11 ))
SobelFilter_mac_mBew_U103(
    .din0(grp_fu_2404_p0),
    .din1(grp_fu_2404_p1),
    .din2(r_V_8_1_fu_1513_p2),
    .dout(grp_fu_2404_p3)
);

SobelFilter_mac_mBew #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 2 ),
    .din1_WIDTH( 8 ),
    .din2_WIDTH( 9 ),
    .dout_WIDTH( 11 ))
SobelFilter_mac_mBew_U104(
    .din0(grp_fu_2411_p0),
    .din1(grp_fu_2411_p1),
    .din2(r_V_8_2_fu_1687_p2),
    .dout(grp_fu_2411_p3)
);

SobelFilter_mac_mCeG #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 2 ),
    .din1_WIDTH( 8 ),
    .din2_WIDTH( 11 ),
    .dout_WIDTH( 11 ))
SobelFilter_mac_mCeG_U105(
    .din0(grp_fu_2418_p0),
    .din1(grp_fu_2418_p1),
    .din2(p_Val2_89_0_0_1_reg_2927),
    .dout(grp_fu_2418_p3)
);

SobelFilter_mac_mCeG #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 2 ),
    .din1_WIDTH( 8 ),
    .din2_WIDTH( 11 ),
    .dout_WIDTH( 11 ))
SobelFilter_mac_mCeG_U106(
    .din0(grp_fu_2426_p0),
    .din1(grp_fu_2426_p1),
    .din2(p_Val2_89_1_0_1_reg_2950),
    .dout(grp_fu_2426_p3)
);

SobelFilter_mac_mCeG #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 2 ),
    .din1_WIDTH( 8 ),
    .din2_WIDTH( 11 ),
    .dout_WIDTH( 11 ))
SobelFilter_mac_mCeG_U107(
    .din0(grp_fu_2434_p0),
    .din1(grp_fu_2434_p1),
    .din2(p_Val2_89_2_0_1_reg_2973),
    .dout(grp_fu_2434_p3)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter0 <= 1'b0;
    end else begin
        if (((exitcond389_i_fu_981_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_enable_reg_pp0_iter0 <= 1'b0;
        end else if (((exitcond390_i_fu_689_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state3))) begin
            ap_enable_reg_pp0_iter0 <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter1 <= ap_enable_reg_pp0_iter0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter2 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter3 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            if ((1'b1 == ap_condition_pp0_exit_iter2_state6)) begin
                ap_enable_reg_pp0_iter3 <= ap_enable_reg_pp0_iter1;
            end else if ((1'b1 == 1'b1)) begin
                ap_enable_reg_pp0_iter3 <= ap_enable_reg_pp0_iter2;
            end
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter4 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter4 <= ap_enable_reg_pp0_iter3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter5 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter5 <= ap_enable_reg_pp0_iter4;
        end else if (((exitcond390_i_fu_689_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state3))) begin
            ap_enable_reg_pp0_iter5 <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((exitcond389_i_fu_981_p2 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        t_V_3_reg_644 <= j_V_fu_987_p2;
    end else if (((exitcond390_i_fu_689_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state3))) begin
        t_V_3_reg_644 <= 11'd0;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state10)) begin
        t_V_reg_633 <= i_V_reg_2754;
    end else if (((tmp_33_fu_661_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state2))) begin
        t_V_reg_633 <= 11'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
        tmp_s_reg_622 <= 2'd0;
    end else if (((tmp_33_fu_661_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state2))) begin
        tmp_s_reg_622 <= tmp_32_fu_655_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((tmp_33_fu_661_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state2))) begin
        OP2_V_0_0_1_cast_reg_2708 <= OP2_V_0_0_1_cast_fu_667_p1;
        OP2_V_0_0_2_cast_reg_2715 <= OP2_V_0_0_2_cast_fu_670_p1;
        OP2_V_0_1_2_cast_reg_2729[3 : 0] <= OP2_V_0_1_2_cast_fu_676_p1[3 : 0];
        OP2_V_0_1_cast_reg_2722 <= OP2_V_0_1_cast_fu_673_p1;
        OP2_V_0_2_1_cast_reg_2743[2 : 0] <= OP2_V_0_2_1_cast_fu_682_p1[2 : 0];
        OP2_V_0_2_cast_reg_2736 <= OP2_V_0_2_cast_fu_679_p1;
    end
end

always @ (posedge ap_clk) begin
    if (((exitcond389_i_fu_981_p2 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        brmerge_reg_2838 <= brmerge_fu_1103_p2;
        or_cond_i_i_reg_2824 <= or_cond_i_i_fu_1039_p2;
        or_cond_i_reg_2851 <= or_cond_i_fu_1108_p2;
        tmp_146_reg_2833 <= tmp_146_fu_1099_p1;
        x_reg_2828 <= x_fu_1091_p3;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        brmerge_reg_2838_pp0_iter1_reg <= brmerge_reg_2838;
        exitcond389_i_reg_2815 <= exitcond389_i_fu_981_p2;
        exitcond389_i_reg_2815_pp0_iter1_reg <= exitcond389_i_reg_2815;
        or_cond_i_i_reg_2824_pp0_iter1_reg <= or_cond_i_i_reg_2824;
        or_cond_i_reg_2851_pp0_iter1_reg <= or_cond_i_reg_2851;
        tmp_146_reg_2833_pp0_iter1_reg <= tmp_146_reg_2833;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        exitcond389_i_reg_2815_pp0_iter2_reg <= exitcond389_i_reg_2815_pp0_iter1_reg;
        or_cond_i_reg_2851_pp0_iter2_reg <= or_cond_i_reg_2851_pp0_iter1_reg;
        or_cond_i_reg_2851_pp0_iter3_reg <= or_cond_i_reg_2851_pp0_iter2_reg;
        or_cond_i_reg_2851_pp0_iter4_reg <= or_cond_i_reg_2851_pp0_iter3_reg;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        i_V_reg_2754 <= i_V_fu_695_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((exitcond390_i_fu_689_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state3))) begin
        icmp_reg_2768 <= icmp_fu_723_p2;
        row_assign_10_0_0_t_reg_2794 <= row_assign_10_0_0_t_fu_931_p2;
        row_assign_10_0_1_t_reg_2801 <= row_assign_10_0_1_t_fu_951_p2;
        row_assign_10_0_2_t_reg_2808 <= row_assign_10_0_2_t_fu_971_p2;
        tmp_384_0_0_not_reg_2763 <= tmp_384_0_0_not_fu_707_p2;
        tmp_38_reg_2759 <= tmp_38_fu_701_p2;
        tmp_40_reg_2773 <= tmp_40_fu_729_p2;
        tmp_41_reg_2781 <= tmp_41_fu_741_p2;
        tmp_428_0_1_reg_2777 <= tmp_428_0_1_fu_735_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((exitcond389_i_reg_2815 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        k_buf_0_val_3_addr_reg_2855 <= tmp_61_fu_1116_p1;
        k_buf_0_val_4_addr_reg_2861 <= tmp_61_fu_1116_p1;
        k_buf_0_val_5_addr_reg_2867 <= tmp_61_fu_1116_p1;
        k_buf_1_val_3_addr_reg_2873 <= tmp_61_fu_1116_p1;
        k_buf_1_val_4_addr_reg_2879 <= tmp_61_fu_1116_p1;
        k_buf_1_val_5_addr_reg_2885 <= tmp_61_fu_1116_p1;
        k_buf_2_val_3_addr_reg_2891 <= tmp_61_fu_1116_p1;
        k_buf_2_val_4_addr_reg_2897 <= tmp_61_fu_1116_p1;
        k_buf_2_val_5_addr_reg_2903 <= tmp_61_fu_1116_p1;
    end
end

always @ (posedge ap_clk) begin
    if (((or_cond_i_reg_2851_pp0_iter3_reg == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        p_Val2_33_reg_3068 <= p_Val2_33_fu_2229_p3;
        p_Val2_34_reg_3073 <= p_Val2_34_fu_2309_p3;
        p_Val2_35_reg_3078 <= p_Val2_35_fu_2389_p3;
    end
end

always @ (posedge ap_clk) begin
    if (((or_cond_i_reg_2851_pp0_iter1_reg == 1'd1) & (exitcond389_i_reg_2815_pp0_iter1_reg == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        p_Val2_89_0_0_1_reg_2927 <= grp_fu_2397_p3;
        p_Val2_89_1_0_1_reg_2950 <= grp_fu_2404_p3;
        p_Val2_89_2_0_1_reg_2973 <= grp_fu_2411_p3;
    end
end

always @ (posedge ap_clk) begin
    if (((or_cond_i_reg_2851_pp0_iter2_reg == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        p_Val2_89_0_1_1_reg_2978 <= p_Val2_89_0_1_1_fu_1775_p2;
        p_Val2_89_1_1_1_reg_3008 <= p_Val2_89_1_1_1_fu_1890_p2;
        p_Val2_89_2_1_1_reg_3038 <= p_Val2_89_2_1_1_fu_2005_p2;
        r_V_8_0_1_2_reg_2983 <= r_V_8_0_1_2_fu_1784_p2;
        r_V_8_1_1_2_reg_3013 <= r_V_8_1_1_2_fu_1899_p2;
        r_V_8_2_1_2_reg_3043 <= r_V_8_2_1_2_fu_2014_p2;
        tmp32_reg_2993 <= tmp32_fu_1838_p2;
        tmp34_reg_2998 <= tmp34_fu_1844_p2;
        tmp36_reg_3003 <= tmp36_fu_1850_p2;
        tmp40_reg_3023 <= tmp40_fu_1953_p2;
        tmp42_reg_3028 <= tmp42_fu_1959_p2;
        tmp44_reg_3033 <= tmp44_fu_1965_p2;
        tmp48_reg_3053 <= tmp48_fu_2068_p2;
        tmp50_reg_3058 <= tmp50_fu_2074_p2;
        tmp52_reg_3063 <= tmp52_fu_2080_p2;
        tmp_152_reg_2988 <= tmp_152_fu_1808_p1;
        tmp_161_reg_3018 <= tmp_161_fu_1923_p1;
        tmp_170_reg_3048 <= tmp_170_fu_2038_p1;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1) & (ap_predicate_op239_read_state6 == 1'b1))) begin
        right_border_buf_0_15_fu_320 <= right_border_buf_0_s_fu_316;
        right_border_buf_0_16_fu_328 <= col_buf_0_val_1_0_fu_1192_p3;
        right_border_buf_0_17_fu_332 <= right_border_buf_0_16_fu_328;
        right_border_buf_0_18_fu_340 <= col_buf_0_val_2_0_fu_1211_p3;
        right_border_buf_0_19_fu_344 <= right_border_buf_0_18_fu_340;
        right_border_buf_0_s_fu_316 <= col_buf_0_val_0_0_fu_1173_p3;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1) & (ap_predicate_op290_read_state6 == 1'b1))) begin
        right_border_buf_1_15_fu_356 <= right_border_buf_1_s_fu_352;
        right_border_buf_1_16_fu_364 <= col_buf_1_val_1_0_fu_1384_p3;
        right_border_buf_1_17_fu_368 <= right_border_buf_1_16_fu_364;
        right_border_buf_1_18_fu_376 <= col_buf_1_val_2_0_fu_1403_p3;
        right_border_buf_1_19_fu_380 <= right_border_buf_1_18_fu_376;
        right_border_buf_1_s_fu_352 <= col_buf_1_val_0_0_fu_1365_p3;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1) & (ap_predicate_op335_read_state6 == 1'b1))) begin
        right_border_buf_2_12_fu_336 <= col_buf_2_val_2_0_fu_1586_p3;
        right_border_buf_2_13_fu_348 <= right_border_buf_2_14_fu_360;
        right_border_buf_2_14_fu_360 <= col_buf_2_val_1_0_fu_1567_p3;
        right_border_buf_2_15_fu_372 <= right_border_buf_2_16_fu_384;
        right_border_buf_2_16_fu_384 <= col_buf_2_val_0_0_fu_1548_p3;
        right_border_buf_2_s_fu_324 <= right_border_buf_2_12_fu_336;
    end
end

always @ (posedge ap_clk) begin
    if (((exitcond389_i_reg_2815_pp0_iter2_reg == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter3 == 1'b1))) begin
        src_kernel_win_0_va_18_fu_248 <= src_kernel_win_0_va_fu_244;
        src_kernel_win_0_va_19_fu_252 <= src_kernel_win_0_va_24_reg_2916;
        src_kernel_win_0_va_20_fu_256 <= src_kernel_win_0_va_19_fu_252;
        src_kernel_win_0_va_fu_244 <= src_kernel_win_0_va_23_reg_2909;
        src_kernel_win_1_va_18_fu_272 <= src_kernel_win_1_va_fu_268;
        src_kernel_win_1_va_19_fu_276 <= src_kernel_win_1_va_24_reg_2939;
        src_kernel_win_1_va_20_fu_280 <= src_kernel_win_1_va_19_fu_276;
        src_kernel_win_1_va_fu_268 <= src_kernel_win_1_va_23_reg_2932;
        src_kernel_win_2_va_18_fu_296 <= src_kernel_win_2_va_fu_292;
        src_kernel_win_2_va_19_fu_300 <= src_kernel_win_2_va_27_reg_2962;
        src_kernel_win_2_va_20_fu_304 <= src_kernel_win_2_va_19_fu_300;
        src_kernel_win_2_va_fu_292 <= src_kernel_win_2_va_26_reg_2955;
    end
end

always @ (posedge ap_clk) begin
    if (((exitcond389_i_reg_2815_pp0_iter1_reg == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        src_kernel_win_0_va_21_fu_260 <= src_kernel_win_0_va_25_fu_1304_p3;
        src_kernel_win_0_va_22_fu_264 <= src_kernel_win_0_va_21_fu_260;
        src_kernel_win_1_va_21_fu_284 <= src_kernel_win_1_va_25_fu_1496_p3;
        src_kernel_win_1_va_22_fu_288 <= src_kernel_win_1_va_21_fu_284;
        src_kernel_win_2_va_21_fu_308 <= src_kernel_win_2_va_28_fu_1670_p3;
        src_kernel_win_2_va_22_fu_312 <= src_kernel_win_2_va_21_fu_308;
    end
end

always @ (posedge ap_clk) begin
    if (((exitcond389_i_reg_2815_pp0_iter1_reg == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        src_kernel_win_0_va_23_reg_2909 <= src_kernel_win_0_va_23_fu_1268_p3;
        src_kernel_win_0_va_24_reg_2916 <= src_kernel_win_0_va_24_fu_1286_p3;
        src_kernel_win_0_va_25_reg_2922 <= src_kernel_win_0_va_25_fu_1304_p3;
        src_kernel_win_1_va_23_reg_2932 <= src_kernel_win_1_va_23_fu_1460_p3;
        src_kernel_win_1_va_24_reg_2939 <= src_kernel_win_1_va_24_fu_1478_p3;
        src_kernel_win_1_va_25_reg_2945 <= src_kernel_win_1_va_25_fu_1496_p3;
        src_kernel_win_2_va_26_reg_2955 <= src_kernel_win_2_va_26_fu_1634_p3;
        src_kernel_win_2_va_27_reg_2962 <= src_kernel_win_2_va_27_fu_1652_p3;
        src_kernel_win_2_va_28_reg_2968 <= src_kernel_win_2_va_28_fu_1670_p3;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter2 == 1'b1) & (ap_enable_reg_pp0_iter1 == 1'b0))) begin
        ap_condition_pp0_exit_iter2_state6 = 1'b1;
    end else begin
        ap_condition_pp0_exit_iter2_state6 = 1'b0;
    end
end

always @ (*) begin
    if ((((exitcond390_i_fu_689_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state3)) | ((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1)))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter5 == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter4 == 1'b0) & (ap_enable_reg_pp0_iter3 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((exitcond390_i_fu_689_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state3))) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        k_buf_0_val_3_ce0 = 1'b1;
    end else begin
        k_buf_0_val_3_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((((tmp_40_reg_2773 == 1'd1) & (or_cond_i_i_reg_2824_pp0_iter1_reg == 1'd1) & (icmp_reg_2768 == 1'd0) & (exitcond389_i_reg_2815_pp0_iter1_reg == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1)) | ((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1) & (ap_predicate_op239_read_state6 == 1'b1)))) begin
        k_buf_0_val_3_ce1 = 1'b1;
    end else begin
        k_buf_0_val_3_ce1 = 1'b0;
    end
end

always @ (*) begin
    if ((((tmp_40_reg_2773 == 1'd1) & (or_cond_i_i_reg_2824_pp0_iter1_reg == 1'd1) & (icmp_reg_2768 == 1'd0) & (exitcond389_i_reg_2815_pp0_iter1_reg == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1)) | ((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1) & (ap_predicate_op239_read_state6 == 1'b1)))) begin
        k_buf_0_val_3_we1 = 1'b1;
    end else begin
        k_buf_0_val_3_we1 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        k_buf_0_val_4_ce0 = 1'b1;
    end else begin
        k_buf_0_val_4_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((((tmp_428_0_1_reg_2777 == 1'd1) & (or_cond_i_i_reg_2824_pp0_iter1_reg == 1'd1) & (icmp_reg_2768 == 1'd0) & (exitcond389_i_reg_2815_pp0_iter1_reg == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1)) | ((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1) & (ap_predicate_op239_read_state6 == 1'b1)))) begin
        k_buf_0_val_4_ce1 = 1'b1;
    end else begin
        k_buf_0_val_4_ce1 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        if ((ap_predicate_op239_read_state6 == 1'b1)) begin
            k_buf_0_val_4_d1 = k_buf_0_val_3_q0;
        end else if ((1'b1 == ap_condition_655)) begin
            k_buf_0_val_4_d1 = p_src_data_stream_0_V_dout;
        end else begin
            k_buf_0_val_4_d1 = 'bx;
        end
    end else begin
        k_buf_0_val_4_d1 = 'bx;
    end
end

always @ (*) begin
    if ((((tmp_428_0_1_reg_2777 == 1'd1) & (or_cond_i_i_reg_2824_pp0_iter1_reg == 1'd1) & (icmp_reg_2768 == 1'd0) & (exitcond389_i_reg_2815_pp0_iter1_reg == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1)) | ((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1) & (ap_predicate_op239_read_state6 == 1'b1)))) begin
        k_buf_0_val_4_we1 = 1'b1;
    end else begin
        k_buf_0_val_4_we1 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        k_buf_0_val_5_ce0 = 1'b1;
    end else begin
        k_buf_0_val_5_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((((tmp_40_reg_2773 == 1'd1) & (or_cond_i_i_reg_2824_pp0_iter1_reg == 1'd1) & (icmp_reg_2768 == 1'd0) & (exitcond389_i_reg_2815_pp0_iter1_reg == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1)) | ((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1) & (ap_predicate_op239_read_state6 == 1'b1)))) begin
        k_buf_0_val_5_ce1 = 1'b1;
    end else begin
        k_buf_0_val_5_ce1 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        if ((ap_predicate_op239_read_state6 == 1'b1)) begin
            k_buf_0_val_5_d1 = k_buf_0_val_4_q0;
        end else if ((1'b1 == ap_condition_649)) begin
            k_buf_0_val_5_d1 = p_src_data_stream_0_V_dout;
        end else begin
            k_buf_0_val_5_d1 = 'bx;
        end
    end else begin
        k_buf_0_val_5_d1 = 'bx;
    end
end

always @ (*) begin
    if ((((tmp_40_reg_2773 == 1'd1) & (or_cond_i_i_reg_2824_pp0_iter1_reg == 1'd1) & (icmp_reg_2768 == 1'd0) & (exitcond389_i_reg_2815_pp0_iter1_reg == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1)) | ((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1) & (ap_predicate_op239_read_state6 == 1'b1)))) begin
        k_buf_0_val_5_we1 = 1'b1;
    end else begin
        k_buf_0_val_5_we1 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        k_buf_1_val_3_ce0 = 1'b1;
    end else begin
        k_buf_1_val_3_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((((tmp_40_reg_2773 == 1'd1) & (or_cond_i_i_reg_2824_pp0_iter1_reg == 1'd1) & (icmp_reg_2768 == 1'd0) & (exitcond389_i_reg_2815_pp0_iter1_reg == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1)) | ((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1) & (ap_predicate_op290_read_state6 == 1'b1)))) begin
        k_buf_1_val_3_ce1 = 1'b1;
    end else begin
        k_buf_1_val_3_ce1 = 1'b0;
    end
end

always @ (*) begin
    if ((((tmp_40_reg_2773 == 1'd1) & (or_cond_i_i_reg_2824_pp0_iter1_reg == 1'd1) & (icmp_reg_2768 == 1'd0) & (exitcond389_i_reg_2815_pp0_iter1_reg == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1)) | ((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1) & (ap_predicate_op290_read_state6 == 1'b1)))) begin
        k_buf_1_val_3_we1 = 1'b1;
    end else begin
        k_buf_1_val_3_we1 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        k_buf_1_val_4_ce0 = 1'b1;
    end else begin
        k_buf_1_val_4_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((((tmp_428_0_1_reg_2777 == 1'd1) & (or_cond_i_i_reg_2824_pp0_iter1_reg == 1'd1) & (icmp_reg_2768 == 1'd0) & (exitcond389_i_reg_2815_pp0_iter1_reg == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1)) | ((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1) & (ap_predicate_op290_read_state6 == 1'b1)))) begin
        k_buf_1_val_4_ce1 = 1'b1;
    end else begin
        k_buf_1_val_4_ce1 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        if ((ap_predicate_op290_read_state6 == 1'b1)) begin
            k_buf_1_val_4_d1 = k_buf_1_val_3_q0;
        end else if ((1'b1 == ap_condition_655)) begin
            k_buf_1_val_4_d1 = p_src_data_stream_1_V_dout;
        end else begin
            k_buf_1_val_4_d1 = 'bx;
        end
    end else begin
        k_buf_1_val_4_d1 = 'bx;
    end
end

always @ (*) begin
    if ((((tmp_428_0_1_reg_2777 == 1'd1) & (or_cond_i_i_reg_2824_pp0_iter1_reg == 1'd1) & (icmp_reg_2768 == 1'd0) & (exitcond389_i_reg_2815_pp0_iter1_reg == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1)) | ((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1) & (ap_predicate_op290_read_state6 == 1'b1)))) begin
        k_buf_1_val_4_we1 = 1'b1;
    end else begin
        k_buf_1_val_4_we1 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        k_buf_1_val_5_ce0 = 1'b1;
    end else begin
        k_buf_1_val_5_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((((tmp_40_reg_2773 == 1'd1) & (or_cond_i_i_reg_2824_pp0_iter1_reg == 1'd1) & (icmp_reg_2768 == 1'd0) & (exitcond389_i_reg_2815_pp0_iter1_reg == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1)) | ((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1) & (ap_predicate_op290_read_state6 == 1'b1)))) begin
        k_buf_1_val_5_ce1 = 1'b1;
    end else begin
        k_buf_1_val_5_ce1 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        if ((ap_predicate_op290_read_state6 == 1'b1)) begin
            k_buf_1_val_5_d1 = k_buf_1_val_4_q0;
        end else if ((1'b1 == ap_condition_649)) begin
            k_buf_1_val_5_d1 = p_src_data_stream_1_V_dout;
        end else begin
            k_buf_1_val_5_d1 = 'bx;
        end
    end else begin
        k_buf_1_val_5_d1 = 'bx;
    end
end

always @ (*) begin
    if ((((tmp_40_reg_2773 == 1'd1) & (or_cond_i_i_reg_2824_pp0_iter1_reg == 1'd1) & (icmp_reg_2768 == 1'd0) & (exitcond389_i_reg_2815_pp0_iter1_reg == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1)) | ((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1) & (ap_predicate_op290_read_state6 == 1'b1)))) begin
        k_buf_1_val_5_we1 = 1'b1;
    end else begin
        k_buf_1_val_5_we1 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        k_buf_2_val_3_ce0 = 1'b1;
    end else begin
        k_buf_2_val_3_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((((tmp_40_reg_2773 == 1'd1) & (or_cond_i_i_reg_2824_pp0_iter1_reg == 1'd1) & (icmp_reg_2768 == 1'd0) & (exitcond389_i_reg_2815_pp0_iter1_reg == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1)) | ((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1) & (ap_predicate_op335_read_state6 == 1'b1)))) begin
        k_buf_2_val_3_ce1 = 1'b1;
    end else begin
        k_buf_2_val_3_ce1 = 1'b0;
    end
end

always @ (*) begin
    if ((((tmp_40_reg_2773 == 1'd1) & (or_cond_i_i_reg_2824_pp0_iter1_reg == 1'd1) & (icmp_reg_2768 == 1'd0) & (exitcond389_i_reg_2815_pp0_iter1_reg == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1)) | ((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1) & (ap_predicate_op335_read_state6 == 1'b1)))) begin
        k_buf_2_val_3_we1 = 1'b1;
    end else begin
        k_buf_2_val_3_we1 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        k_buf_2_val_4_ce0 = 1'b1;
    end else begin
        k_buf_2_val_4_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((((tmp_428_0_1_reg_2777 == 1'd1) & (or_cond_i_i_reg_2824_pp0_iter1_reg == 1'd1) & (icmp_reg_2768 == 1'd0) & (exitcond389_i_reg_2815_pp0_iter1_reg == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1)) | ((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1) & (ap_predicate_op335_read_state6 == 1'b1)))) begin
        k_buf_2_val_4_ce1 = 1'b1;
    end else begin
        k_buf_2_val_4_ce1 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        if ((ap_predicate_op335_read_state6 == 1'b1)) begin
            k_buf_2_val_4_d1 = k_buf_2_val_3_q0;
        end else if ((1'b1 == ap_condition_655)) begin
            k_buf_2_val_4_d1 = p_src_data_stream_2_V_dout;
        end else begin
            k_buf_2_val_4_d1 = 'bx;
        end
    end else begin
        k_buf_2_val_4_d1 = 'bx;
    end
end

always @ (*) begin
    if ((((tmp_428_0_1_reg_2777 == 1'd1) & (or_cond_i_i_reg_2824_pp0_iter1_reg == 1'd1) & (icmp_reg_2768 == 1'd0) & (exitcond389_i_reg_2815_pp0_iter1_reg == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1)) | ((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1) & (ap_predicate_op335_read_state6 == 1'b1)))) begin
        k_buf_2_val_4_we1 = 1'b1;
    end else begin
        k_buf_2_val_4_we1 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        k_buf_2_val_5_ce0 = 1'b1;
    end else begin
        k_buf_2_val_5_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((((tmp_40_reg_2773 == 1'd1) & (or_cond_i_i_reg_2824_pp0_iter1_reg == 1'd1) & (icmp_reg_2768 == 1'd0) & (exitcond389_i_reg_2815_pp0_iter1_reg == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1)) | ((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1) & (ap_predicate_op335_read_state6 == 1'b1)))) begin
        k_buf_2_val_5_ce1 = 1'b1;
    end else begin
        k_buf_2_val_5_ce1 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        if ((ap_predicate_op335_read_state6 == 1'b1)) begin
            k_buf_2_val_5_d1 = k_buf_2_val_4_q0;
        end else if ((1'b1 == ap_condition_649)) begin
            k_buf_2_val_5_d1 = p_src_data_stream_2_V_dout;
        end else begin
            k_buf_2_val_5_d1 = 'bx;
        end
    end else begin
        k_buf_2_val_5_d1 = 'bx;
    end
end

always @ (*) begin
    if ((((tmp_40_reg_2773 == 1'd1) & (or_cond_i_i_reg_2824_pp0_iter1_reg == 1'd1) & (icmp_reg_2768 == 1'd0) & (exitcond389_i_reg_2815_pp0_iter1_reg == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1)) | ((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1) & (ap_predicate_op335_read_state6 == 1'b1)))) begin
        k_buf_2_val_5_we1 = 1'b1;
    end else begin
        k_buf_2_val_5_we1 = 1'b0;
    end
end

always @ (*) begin
    if (((or_cond_i_reg_2851_pp0_iter4_reg == 1'd1) & (1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter5 == 1'b1))) begin
        p_dst_data_stream_0_V_blk_n = p_dst_data_stream_0_V_full_n;
    end else begin
        p_dst_data_stream_0_V_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((or_cond_i_reg_2851_pp0_iter4_reg == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter5 == 1'b1))) begin
        p_dst_data_stream_0_V_write = 1'b1;
    end else begin
        p_dst_data_stream_0_V_write = 1'b0;
    end
end

always @ (*) begin
    if (((or_cond_i_reg_2851_pp0_iter4_reg == 1'd1) & (1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter5 == 1'b1))) begin
        p_dst_data_stream_1_V_blk_n = p_dst_data_stream_1_V_full_n;
    end else begin
        p_dst_data_stream_1_V_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((or_cond_i_reg_2851_pp0_iter4_reg == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter5 == 1'b1))) begin
        p_dst_data_stream_1_V_write = 1'b1;
    end else begin
        p_dst_data_stream_1_V_write = 1'b0;
    end
end

always @ (*) begin
    if (((or_cond_i_reg_2851_pp0_iter4_reg == 1'd1) & (1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter5 == 1'b1))) begin
        p_dst_data_stream_2_V_blk_n = p_dst_data_stream_2_V_full_n;
    end else begin
        p_dst_data_stream_2_V_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((or_cond_i_reg_2851_pp0_iter4_reg == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter5 == 1'b1))) begin
        p_dst_data_stream_2_V_write = 1'b1;
    end else begin
        p_dst_data_stream_2_V_write = 1'b0;
    end
end

always @ (*) begin
    if ((((or_cond_i_i_reg_2824_pp0_iter1_reg == 1'd1) & (icmp_reg_2768 == 1'd0) & (exitcond389_i_reg_2815_pp0_iter1_reg == 1'd0) & (1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter2 == 1'b1)) | ((tmp_38_reg_2759 == 1'd1) & (icmp_reg_2768 == 1'd1) & (or_cond_i_i_reg_2824_pp0_iter1_reg == 1'd1) & (exitcond389_i_reg_2815_pp0_iter1_reg == 1'd0) & (1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter2 == 1'b1)))) begin
        p_src_data_stream_0_V_blk_n = p_src_data_stream_0_V_empty_n;
    end else begin
        p_src_data_stream_0_V_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1) & (ap_predicate_op239_read_state6 == 1'b1)) | ((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1) & (ap_predicate_op227_read_state6 == 1'b1)))) begin
        p_src_data_stream_0_V_read = 1'b1;
    end else begin
        p_src_data_stream_0_V_read = 1'b0;
    end
end

always @ (*) begin
    if ((((or_cond_i_i_reg_2824_pp0_iter1_reg == 1'd1) & (icmp_reg_2768 == 1'd0) & (exitcond389_i_reg_2815_pp0_iter1_reg == 1'd0) & (1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter2 == 1'b1)) | ((tmp_38_reg_2759 == 1'd1) & (icmp_reg_2768 == 1'd1) & (or_cond_i_i_reg_2824_pp0_iter1_reg == 1'd1) & (exitcond389_i_reg_2815_pp0_iter1_reg == 1'd0) & (1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter2 == 1'b1)))) begin
        p_src_data_stream_1_V_blk_n = p_src_data_stream_1_V_empty_n;
    end else begin
        p_src_data_stream_1_V_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1) & (ap_predicate_op290_read_state6 == 1'b1)) | ((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1) & (ap_predicate_op278_read_state6 == 1'b1)))) begin
        p_src_data_stream_1_V_read = 1'b1;
    end else begin
        p_src_data_stream_1_V_read = 1'b0;
    end
end

always @ (*) begin
    if ((((or_cond_i_i_reg_2824_pp0_iter1_reg == 1'd1) & (icmp_reg_2768 == 1'd0) & (exitcond389_i_reg_2815_pp0_iter1_reg == 1'd0) & (1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter2 == 1'b1)) | ((tmp_38_reg_2759 == 1'd1) & (icmp_reg_2768 == 1'd1) & (or_cond_i_i_reg_2824_pp0_iter1_reg == 1'd1) & (exitcond389_i_reg_2815_pp0_iter1_reg == 1'd0) & (1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter2 == 1'b1)))) begin
        p_src_data_stream_2_V_blk_n = p_src_data_stream_2_V_empty_n;
    end else begin
        p_src_data_stream_2_V_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1) & (ap_predicate_op335_read_state6 == 1'b1)) | ((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1) & (ap_predicate_op326_read_state6 == 1'b1)))) begin
        p_src_data_stream_2_V_read = 1'b1;
    end else begin
        p_src_data_stream_2_V_read = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            if (((tmp_33_fu_661_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state2))) begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end
        end
        ap_ST_fsm_state3 : begin
            if (((exitcond390_i_fu_689_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state3))) begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end
        end
        ap_ST_fsm_pp0_stage0 : begin
            if ((~((ap_enable_reg_pp0_iter3 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0) & (1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter2 == 1'b1)) & ~((ap_enable_reg_pp0_iter4 == 1'b0) & (1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter5 == 1'b1)))) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end else if ((((ap_enable_reg_pp0_iter4 == 1'b0) & (1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter5 == 1'b1)) | ((ap_enable_reg_pp0_iter3 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0) & (1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter2 == 1'b1)))) begin
                ap_NS_fsm = ap_ST_fsm_state10;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end
        end
        ap_ST_fsm_state10 : begin
            ap_NS_fsm = ap_ST_fsm_state3;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign ImagLoc_x_cast_fu_1015_p1 = ImagLoc_x_fu_1009_p2;

assign ImagLoc_x_fu_1009_p2 = ($signed(12'd4095) + $signed(t_V_3_cast_fu_977_p1));

assign OP1_V_0_0_cast_fu_1317_p1 = src_kernel_win_0_va_22_fu_264;

assign OP1_V_1_0_cast_fu_1509_p1 = src_kernel_win_1_va_22_fu_288;

assign OP1_V_2_0_cast_fu_1683_p1 = src_kernel_win_2_va_22_fu_312;

assign OP2_V_0_0_1_cast_fu_667_p1 = $signed(p_kernel_val_0_V_1_read);

assign OP2_V_0_0_2_cast_fu_670_p1 = $signed(p_kernel_val_0_V_2_read);

assign OP2_V_0_1_2_cast_fu_676_p1 = p_kernel_val_1_V_2_read;

assign OP2_V_0_1_cast_fu_673_p1 = $signed(p_kernel_val_1_V_0_read);

assign OP2_V_0_2_1_cast_fu_682_p1 = p_kernel_val_2_V_1_read;

assign OP2_V_0_2_cast_fu_679_p1 = $signed(p_kernel_val_2_V_0_read);

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd3];

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state10 = ap_CS_fsm[32'd4];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state3 = ap_CS_fsm[32'd2];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage0_01001 = (((ap_enable_reg_pp0_iter5 == 1'b1) & (((or_cond_i_reg_2851_pp0_iter4_reg == 1'd1) & (p_dst_data_stream_2_V_full_n == 1'b0)) | ((or_cond_i_reg_2851_pp0_iter4_reg == 1'd1) & (p_dst_data_stream_1_V_full_n == 1'b0)) | ((or_cond_i_reg_2851_pp0_iter4_reg == 1'd1) & (p_dst_data_stream_0_V_full_n == 1'b0)))) | ((ap_enable_reg_pp0_iter2 == 1'b1) & (((p_src_data_stream_2_V_empty_n == 1'b0) & (ap_predicate_op335_read_state6 == 1'b1)) | ((p_src_data_stream_2_V_empty_n == 1'b0) & (ap_predicate_op326_read_state6 == 1'b1)) | ((p_src_data_stream_1_V_empty_n == 1'b0) & (ap_predicate_op290_read_state6 == 1'b1)) | ((p_src_data_stream_1_V_empty_n == 1'b0) & (ap_predicate_op278_read_state6 == 1'b1)) | ((p_src_data_stream_0_V_empty_n == 1'b0) & (ap_predicate_op239_read_state6 == 1'b1)) | ((p_src_data_stream_0_V_empty_n == 1'b0) & (ap_predicate_op227_read_state6 == 1'b1)))));
end

always @ (*) begin
    ap_block_pp0_stage0_11001 = (((ap_enable_reg_pp0_iter5 == 1'b1) & (((or_cond_i_reg_2851_pp0_iter4_reg == 1'd1) & (p_dst_data_stream_2_V_full_n == 1'b0)) | ((or_cond_i_reg_2851_pp0_iter4_reg == 1'd1) & (p_dst_data_stream_1_V_full_n == 1'b0)) | ((or_cond_i_reg_2851_pp0_iter4_reg == 1'd1) & (p_dst_data_stream_0_V_full_n == 1'b0)))) | ((ap_enable_reg_pp0_iter2 == 1'b1) & (((p_src_data_stream_2_V_empty_n == 1'b0) & (ap_predicate_op335_read_state6 == 1'b1)) | ((p_src_data_stream_2_V_empty_n == 1'b0) & (ap_predicate_op326_read_state6 == 1'b1)) | ((p_src_data_stream_1_V_empty_n == 1'b0) & (ap_predicate_op290_read_state6 == 1'b1)) | ((p_src_data_stream_1_V_empty_n == 1'b0) & (ap_predicate_op278_read_state6 == 1'b1)) | ((p_src_data_stream_0_V_empty_n == 1'b0) & (ap_predicate_op239_read_state6 == 1'b1)) | ((p_src_data_stream_0_V_empty_n == 1'b0) & (ap_predicate_op227_read_state6 == 1'b1)))));
end

always @ (*) begin
    ap_block_pp0_stage0_subdone = (((ap_enable_reg_pp0_iter5 == 1'b1) & (((or_cond_i_reg_2851_pp0_iter4_reg == 1'd1) & (p_dst_data_stream_2_V_full_n == 1'b0)) | ((or_cond_i_reg_2851_pp0_iter4_reg == 1'd1) & (p_dst_data_stream_1_V_full_n == 1'b0)) | ((or_cond_i_reg_2851_pp0_iter4_reg == 1'd1) & (p_dst_data_stream_0_V_full_n == 1'b0)))) | ((ap_enable_reg_pp0_iter2 == 1'b1) & (((p_src_data_stream_2_V_empty_n == 1'b0) & (ap_predicate_op335_read_state6 == 1'b1)) | ((p_src_data_stream_2_V_empty_n == 1'b0) & (ap_predicate_op326_read_state6 == 1'b1)) | ((p_src_data_stream_1_V_empty_n == 1'b0) & (ap_predicate_op290_read_state6 == 1'b1)) | ((p_src_data_stream_1_V_empty_n == 1'b0) & (ap_predicate_op278_read_state6 == 1'b1)) | ((p_src_data_stream_0_V_empty_n == 1'b0) & (ap_predicate_op239_read_state6 == 1'b1)) | ((p_src_data_stream_0_V_empty_n == 1'b0) & (ap_predicate_op227_read_state6 == 1'b1)))));
end

assign ap_block_state4_pp0_stage0_iter0 = ~(1'b1 == 1'b1);

assign ap_block_state5_pp0_stage0_iter1 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_state6_pp0_stage0_iter2 = (((p_src_data_stream_2_V_empty_n == 1'b0) & (ap_predicate_op335_read_state6 == 1'b1)) | ((p_src_data_stream_2_V_empty_n == 1'b0) & (ap_predicate_op326_read_state6 == 1'b1)) | ((p_src_data_stream_1_V_empty_n == 1'b0) & (ap_predicate_op290_read_state6 == 1'b1)) | ((p_src_data_stream_1_V_empty_n == 1'b0) & (ap_predicate_op278_read_state6 == 1'b1)) | ((p_src_data_stream_0_V_empty_n == 1'b0) & (ap_predicate_op239_read_state6 == 1'b1)) | ((p_src_data_stream_0_V_empty_n == 1'b0) & (ap_predicate_op227_read_state6 == 1'b1)));
end

assign ap_block_state7_pp0_stage0_iter3 = ~(1'b1 == 1'b1);

assign ap_block_state8_pp0_stage0_iter4 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_state9_pp0_stage0_iter5 = (((or_cond_i_reg_2851_pp0_iter4_reg == 1'd1) & (p_dst_data_stream_2_V_full_n == 1'b0)) | ((or_cond_i_reg_2851_pp0_iter4_reg == 1'd1) & (p_dst_data_stream_1_V_full_n == 1'b0)) | ((or_cond_i_reg_2851_pp0_iter4_reg == 1'd1) & (p_dst_data_stream_0_V_full_n == 1'b0)));
end

always @ (*) begin
    ap_condition_649 = ((tmp_40_reg_2773 == 1'd1) & (or_cond_i_i_reg_2824_pp0_iter1_reg == 1'd1) & (icmp_reg_2768 == 1'd0) & (exitcond389_i_reg_2815_pp0_iter1_reg == 1'd0));
end

always @ (*) begin
    ap_condition_655 = ((tmp_428_0_1_reg_2777 == 1'd1) & (or_cond_i_i_reg_2824_pp0_iter1_reg == 1'd1) & (icmp_reg_2768 == 1'd0) & (exitcond389_i_reg_2815_pp0_iter1_reg == 1'd0));
end

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

always @ (*) begin
    ap_predicate_op227_read_state6 = ((or_cond_i_i_reg_2824_pp0_iter1_reg == 1'd1) & (icmp_reg_2768 == 1'd0) & (exitcond389_i_reg_2815_pp0_iter1_reg == 1'd0));
end

always @ (*) begin
    ap_predicate_op239_read_state6 = ((tmp_38_reg_2759 == 1'd1) & (icmp_reg_2768 == 1'd1) & (or_cond_i_i_reg_2824_pp0_iter1_reg == 1'd1) & (exitcond389_i_reg_2815_pp0_iter1_reg == 1'd0));
end

always @ (*) begin
    ap_predicate_op278_read_state6 = ((or_cond_i_i_reg_2824_pp0_iter1_reg == 1'd1) & (icmp_reg_2768 == 1'd0) & (exitcond389_i_reg_2815_pp0_iter1_reg == 1'd0));
end

always @ (*) begin
    ap_predicate_op290_read_state6 = ((tmp_38_reg_2759 == 1'd1) & (icmp_reg_2768 == 1'd1) & (or_cond_i_i_reg_2824_pp0_iter1_reg == 1'd1) & (exitcond389_i_reg_2815_pp0_iter1_reg == 1'd0));
end

always @ (*) begin
    ap_predicate_op326_read_state6 = ((or_cond_i_i_reg_2824_pp0_iter1_reg == 1'd1) & (icmp_reg_2768 == 1'd0) & (exitcond389_i_reg_2815_pp0_iter1_reg == 1'd0));
end

always @ (*) begin
    ap_predicate_op335_read_state6 = ((tmp_38_reg_2759 == 1'd1) & (icmp_reg_2768 == 1'd1) & (or_cond_i_i_reg_2824_pp0_iter1_reg == 1'd1) & (exitcond389_i_reg_2815_pp0_iter1_reg == 1'd0));
end

assign brmerge_fu_1103_p2 = (tmp_51_fu_1033_p2 | tmp_384_0_0_not_reg_2763);

assign col_assign_3_0_t_fu_1156_p2 = (tmp_146_reg_2833_pp0_iter1_reg ^ 2'd3);

assign col_buf_0_val_0_0_fu_1173_p3 = ((brmerge_reg_2838_pp0_iter1_reg[0:0] === 1'b1) ? k_buf_0_val_3_q0 : tmp_62_fu_1161_p5);

assign col_buf_0_val_1_0_fu_1192_p3 = ((brmerge_reg_2838_pp0_iter1_reg[0:0] === 1'b1) ? k_buf_0_val_4_q0 : tmp_63_fu_1180_p5);

assign col_buf_0_val_2_0_fu_1211_p3 = ((brmerge_reg_2838_pp0_iter1_reg[0:0] === 1'b1) ? k_buf_0_val_5_q0 : tmp_64_fu_1199_p5);

assign col_buf_1_val_0_0_fu_1365_p3 = ((brmerge_reg_2838_pp0_iter1_reg[0:0] === 1'b1) ? k_buf_1_val_3_q0 : tmp_85_fu_1353_p5);

assign col_buf_1_val_1_0_fu_1384_p3 = ((brmerge_reg_2838_pp0_iter1_reg[0:0] === 1'b1) ? k_buf_1_val_4_q0 : tmp_86_fu_1372_p5);

assign col_buf_1_val_2_0_fu_1403_p3 = ((brmerge_reg_2838_pp0_iter1_reg[0:0] === 1'b1) ? k_buf_1_val_5_q0 : tmp_87_fu_1391_p5);

assign col_buf_2_val_0_0_fu_1548_p3 = ((brmerge_reg_2838_pp0_iter1_reg[0:0] === 1'b1) ? k_buf_2_val_3_q0 : tmp_93_fu_1536_p5);

assign col_buf_2_val_1_0_fu_1567_p3 = ((brmerge_reg_2838_pp0_iter1_reg[0:0] === 1'b1) ? k_buf_2_val_4_q0 : tmp_94_fu_1555_p5);

assign col_buf_2_val_2_0_fu_1586_p3 = ((brmerge_reg_2838_pp0_iter1_reg[0:0] === 1'b1) ? k_buf_2_val_5_q0 : tmp_95_fu_1574_p5);

assign exitcond389_i_fu_981_p2 = ((t_V_3_reg_644 == 11'd1922) ? 1'b1 : 1'b0);

assign exitcond390_i_fu_689_p2 = ((t_V_reg_633 == 11'd1082) ? 1'b1 : 1'b0);

assign grp_fu_2397_p0 = OP2_V_0_0_1_cast_reg_2708;

assign grp_fu_2397_p1 = grp_fu_2397_p10;

assign grp_fu_2397_p10 = src_kernel_win_0_va_21_fu_260;

assign grp_fu_2404_p0 = OP2_V_0_0_1_cast_reg_2708;

assign grp_fu_2404_p1 = grp_fu_2404_p10;

assign grp_fu_2404_p10 = src_kernel_win_1_va_21_fu_284;

assign grp_fu_2411_p0 = OP2_V_0_0_1_cast_reg_2708;

assign grp_fu_2411_p1 = grp_fu_2411_p10;

assign grp_fu_2411_p10 = src_kernel_win_2_va_21_fu_308;

assign grp_fu_2418_p0 = OP2_V_0_0_2_cast_reg_2715;

assign grp_fu_2418_p1 = grp_fu_2418_p10;

assign grp_fu_2418_p10 = src_kernel_win_0_va_25_reg_2922;

assign grp_fu_2426_p0 = OP2_V_0_0_2_cast_reg_2715;

assign grp_fu_2426_p1 = grp_fu_2426_p10;

assign grp_fu_2426_p10 = src_kernel_win_1_va_25_reg_2945;

assign grp_fu_2434_p0 = OP2_V_0_0_2_cast_reg_2715;

assign grp_fu_2434_p1 = grp_fu_2434_p10;

assign grp_fu_2434_p10 = src_kernel_win_2_va_28_reg_2968;

assign i_V_fu_695_p2 = (t_V_reg_633 + 11'd1);

assign icmp2_fu_1003_p2 = ((tmp_143_fu_993_p4 != 10'd0) ? 1'b1 : 1'b0);

assign icmp_fu_723_p2 = ((tmp_fu_713_p4 != 10'd0) ? 1'b1 : 1'b0);

assign isneg_1_fu_2250_p3 = p_Val2_29_fu_2244_p2[32'd11];

assign isneg_2_fu_2330_p3 = p_Val2_s_fu_2324_p2[32'd11];

assign isneg_fu_2170_p3 = p_Val2_27_fu_2164_p2[32'd11];

assign j_V_fu_987_p2 = (t_V_3_reg_644 + 11'd1);

assign k_buf_0_val_3_address0 = tmp_61_fu_1116_p1;

assign k_buf_0_val_4_address0 = tmp_61_fu_1116_p1;

assign k_buf_0_val_5_address0 = tmp_61_fu_1116_p1;

assign k_buf_1_val_3_address0 = tmp_61_fu_1116_p1;

assign k_buf_1_val_4_address0 = tmp_61_fu_1116_p1;

assign k_buf_1_val_5_address0 = tmp_61_fu_1116_p1;

assign k_buf_2_val_3_address0 = tmp_61_fu_1116_p1;

assign k_buf_2_val_4_address0 = tmp_61_fu_1116_p1;

assign k_buf_2_val_5_address0 = tmp_61_fu_1116_p1;

assign not_i_i_i1_fu_2363_p2 = ((tmp_100_fu_2347_p4 != 4'd0) ? 1'b1 : 1'b0);

assign not_i_i_i5_fu_2283_p2 = ((tmp_92_fu_2267_p4 != 4'd0) ? 1'b1 : 1'b0);

assign not_i_i_i_fu_2203_p2 = ((tmp_84_fu_2187_p4 != 4'd0) ? 1'b1 : 1'b0);

assign or_cond_i425_i_fu_777_p2 = (tmp_44_fu_771_p2 & rev_fu_765_p2);

assign or_cond_i_fu_1108_p2 = (icmp_reg_2768 & icmp2_fu_1003_p2);

assign or_cond_i_i_fu_1039_p2 = (tmp_51_fu_1033_p2 & rev2_fu_1027_p2);

assign overflow_1_fu_2289_p2 = (tmp_i_i4_fu_2277_p2 & not_i_i_i5_fu_2283_p2);

assign overflow_2_fu_2369_p2 = (tmp_i_i1_fu_2357_p2 & not_i_i_i1_fu_2363_p2);

assign overflow_fu_2209_p2 = (tmp_i_i_fu_2197_p2 & not_i_i_i_fu_2203_p2);

assign p_Val2_27_fu_2164_p2 = ($signed(tmp31_fu_2157_p2) + $signed(tmp32_cast_fu_2161_p1));

assign p_Val2_29_fu_2244_p2 = ($signed(tmp39_fu_2237_p2) + $signed(tmp40_cast_fu_2241_p1));

assign p_Val2_31_fu_2342_p2 = (tmp50_reg_3058 + tmp51_fu_2338_p2);

assign p_Val2_33_fu_2229_p3 = ((tmp_i_i_78_fu_2223_p2[0:0] === 1'b1) ? p_mux_i_i_cast_fu_2215_p3 : p_Val2_7_fu_2182_p2);

assign p_Val2_34_fu_2309_p3 = ((tmp_i_i8_fu_2303_p2[0:0] === 1'b1) ? p_mux_i_i7_cast_fu_2295_p3 : p_Val2_8_fu_2262_p2);

assign p_Val2_35_fu_2389_p3 = ((tmp_i_i1_79_fu_2383_p2[0:0] === 1'b1) ? p_mux_i_i16_cast_fu_2375_p3 : p_Val2_31_fu_2342_p2);

assign p_Val2_7_fu_2182_p2 = (tmp34_reg_2998 + tmp35_fu_2178_p2);

assign p_Val2_89_0_0_2_ca_fu_1752_p1 = grp_fu_2418_p3;

assign p_Val2_89_0_1_1_fu_1775_p2 = ($signed(tmp_472_0_1_cast_cas_fu_1764_p1) + $signed(p_Val2_89_0_0_2_ca_fu_1752_p1));

assign p_Val2_89_1_0_2_ca_fu_1867_p1 = grp_fu_2426_p3;

assign p_Val2_89_1_1_1_fu_1890_p2 = ($signed(tmp_472_1_1_cast_cas_fu_1879_p1) + $signed(p_Val2_89_1_0_2_ca_fu_1867_p1));

assign p_Val2_89_2_0_2_ca_fu_1982_p1 = grp_fu_2434_p3;

assign p_Val2_89_2_1_1_fu_2005_p2 = ($signed(tmp_472_2_1_cast_cas_fu_1994_p1) + $signed(p_Val2_89_2_0_2_ca_fu_1982_p1));

assign p_Val2_8_fu_2262_p2 = (tmp42_reg_3028 + tmp43_fu_2258_p2);

assign p_Val2_s_fu_2324_p2 = ($signed(tmp47_fu_2317_p2) + $signed(tmp48_cast_fu_2321_p1));

assign p_assign_1_fu_1053_p2 = (12'd1 - t_V_3_cast_fu_977_p1);

assign p_assign_2_fu_1077_p2 = ($signed(14'd3838) - $signed(p_p2_i_i_cast_fu_1067_p1));

assign p_assign_6_0_1_fu_815_p2 = ($signed(12'd4094) + $signed(t_V_cast_fu_685_p1));

assign p_assign_6_0_2_fu_859_p2 = ($signed(12'd4093) + $signed(t_V_cast_fu_685_p1));

assign p_assign_7_fu_791_p2 = (12'd1 - t_V_cast_fu_685_p1);

assign p_dst_data_stream_0_V_din = p_Val2_33_reg_3068;

assign p_dst_data_stream_1_V_din = p_Val2_34_reg_3073;

assign p_dst_data_stream_2_V_din = p_Val2_35_reg_3078;

assign p_mux_i_i16_cast_fu_2375_p3 = ((tmp_i_i1_fu_2357_p2[0:0] === 1'b1) ? 8'd255 : 8'd0);

assign p_mux_i_i7_cast_fu_2295_p3 = ((tmp_i_i4_fu_2277_p2[0:0] === 1'b1) ? 8'd255 : 8'd0);

assign p_mux_i_i_cast_fu_2215_p3 = ((tmp_i_i_fu_2197_p2[0:0] === 1'b1) ? 8'd255 : 8'd0);

assign p_p2_i426_i_fu_797_p3 = ((tmp_129_fu_783_p3[0:0] === 1'b1) ? p_assign_7_fu_791_p2 : tmp_42_fu_751_p2);

assign p_p2_i_i_cast_fu_1067_p1 = p_p2_i_i_fu_1059_p3;

assign p_p2_i_i_fu_1059_p3 = ((tmp_145_fu_1045_p3[0:0] === 1'b1) ? p_assign_1_fu_1053_p2 : ImagLoc_x_fu_1009_p2);

assign p_p2_i_i_p_assign_2_fu_1083_p3 = ((tmp_53_fu_1071_p2[0:0] === 1'b1) ? p_p2_i_i_cast_fu_1067_p1 : p_assign_2_fu_1077_p2);

assign r_V_8_0_1_2_fu_1784_p0 = OP2_V_0_1_2_cast_reg_2729;

assign r_V_8_0_1_2_fu_1784_p1 = r_V_8_0_1_2_fu_1784_p10;

assign r_V_8_0_1_2_fu_1784_p10 = src_kernel_win_0_va_24_reg_2916;

assign r_V_8_0_1_2_fu_1784_p2 = (r_V_8_0_1_2_fu_1784_p0 * r_V_8_0_1_2_fu_1784_p1);

assign r_V_8_0_1_fu_1759_p0 = OP2_V_0_1_cast_reg_2722;

assign r_V_8_0_1_fu_1759_p1 = r_V_8_0_1_fu_1759_p10;

assign r_V_8_0_1_fu_1759_p10 = src_kernel_win_0_va_20_fu_256;

assign r_V_8_0_1_fu_1759_p2 = ($signed(r_V_8_0_1_fu_1759_p0) * $signed({{1'b0}, {r_V_8_0_1_fu_1759_p1}}));

assign r_V_8_0_2_1_fu_1816_p0 = OP2_V_0_2_1_cast_reg_2743;

assign r_V_8_0_2_1_fu_1816_p1 = r_V_8_0_2_1_fu_1816_p10;

assign r_V_8_0_2_1_fu_1816_p10 = src_kernel_win_0_va_fu_244;

assign r_V_8_0_2_1_fu_1816_p2 = (r_V_8_0_2_1_fu_1816_p0 * r_V_8_0_2_1_fu_1816_p1);

assign r_V_8_0_2_fu_1803_p0 = OP2_V_0_2_cast_reg_2736;

assign r_V_8_0_2_fu_1803_p1 = r_V_8_0_2_fu_1803_p10;

assign r_V_8_0_2_fu_1803_p10 = src_kernel_win_0_va_18_fu_248;

assign r_V_8_0_2_fu_1803_p2 = ($signed(r_V_8_0_2_fu_1803_p0) * $signed({{1'b0}, {r_V_8_0_2_fu_1803_p1}}));

assign r_V_8_1_1_2_fu_1899_p0 = OP2_V_0_1_2_cast_reg_2729;

assign r_V_8_1_1_2_fu_1899_p1 = r_V_8_1_1_2_fu_1899_p10;

assign r_V_8_1_1_2_fu_1899_p10 = src_kernel_win_1_va_24_reg_2939;

assign r_V_8_1_1_2_fu_1899_p2 = (r_V_8_1_1_2_fu_1899_p0 * r_V_8_1_1_2_fu_1899_p1);

assign r_V_8_1_1_fu_1874_p0 = OP2_V_0_1_cast_reg_2722;

assign r_V_8_1_1_fu_1874_p1 = r_V_8_1_1_fu_1874_p10;

assign r_V_8_1_1_fu_1874_p10 = src_kernel_win_1_va_20_fu_280;

assign r_V_8_1_1_fu_1874_p2 = ($signed(r_V_8_1_1_fu_1874_p0) * $signed({{1'b0}, {r_V_8_1_1_fu_1874_p1}}));

assign r_V_8_1_2_1_fu_1931_p0 = OP2_V_0_2_1_cast_reg_2743;

assign r_V_8_1_2_1_fu_1931_p1 = r_V_8_1_2_1_fu_1931_p10;

assign r_V_8_1_2_1_fu_1931_p10 = src_kernel_win_1_va_fu_268;

assign r_V_8_1_2_1_fu_1931_p2 = (r_V_8_1_2_1_fu_1931_p0 * r_V_8_1_2_1_fu_1931_p1);

assign r_V_8_1_2_fu_1918_p0 = OP2_V_0_2_cast_reg_2736;

assign r_V_8_1_2_fu_1918_p1 = r_V_8_1_2_fu_1918_p10;

assign r_V_8_1_2_fu_1918_p10 = src_kernel_win_1_va_18_fu_272;

assign r_V_8_1_2_fu_1918_p2 = ($signed(r_V_8_1_2_fu_1918_p0) * $signed({{1'b0}, {r_V_8_1_2_fu_1918_p1}}));

assign r_V_8_1_fu_1513_p2 = (9'd0 - OP1_V_1_0_cast_fu_1509_p1);

assign r_V_8_2_1_2_fu_2014_p0 = OP2_V_0_1_2_cast_reg_2729;

assign r_V_8_2_1_2_fu_2014_p1 = r_V_8_2_1_2_fu_2014_p10;

assign r_V_8_2_1_2_fu_2014_p10 = src_kernel_win_2_va_27_reg_2962;

assign r_V_8_2_1_2_fu_2014_p2 = (r_V_8_2_1_2_fu_2014_p0 * r_V_8_2_1_2_fu_2014_p1);

assign r_V_8_2_1_fu_1989_p0 = OP2_V_0_1_cast_reg_2722;

assign r_V_8_2_1_fu_1989_p1 = r_V_8_2_1_fu_1989_p10;

assign r_V_8_2_1_fu_1989_p10 = src_kernel_win_2_va_20_fu_304;

assign r_V_8_2_1_fu_1989_p2 = ($signed(r_V_8_2_1_fu_1989_p0) * $signed({{1'b0}, {r_V_8_2_1_fu_1989_p1}}));

assign r_V_8_2_2_1_fu_2046_p0 = OP2_V_0_2_1_cast_reg_2743;

assign r_V_8_2_2_1_fu_2046_p1 = r_V_8_2_2_1_fu_2046_p10;

assign r_V_8_2_2_1_fu_2046_p10 = src_kernel_win_2_va_fu_292;

assign r_V_8_2_2_1_fu_2046_p2 = (r_V_8_2_2_1_fu_2046_p0 * r_V_8_2_2_1_fu_2046_p1);

assign r_V_8_2_2_fu_2033_p0 = OP2_V_0_2_cast_reg_2736;

assign r_V_8_2_2_fu_2033_p1 = r_V_8_2_2_fu_2033_p10;

assign r_V_8_2_2_fu_2033_p10 = src_kernel_win_2_va_18_fu_296;

assign r_V_8_2_2_fu_2033_p2 = ($signed(r_V_8_2_2_fu_2033_p0) * $signed({{1'b0}, {r_V_8_2_2_fu_2033_p1}}));

assign r_V_8_2_fu_1687_p2 = (9'd0 - OP1_V_2_0_cast_fu_1683_p1);

assign r_V_8_fu_1321_p2 = (9'd0 - OP1_V_0_0_cast_fu_1317_p1);

assign rev2_fu_1027_p2 = (tmp_144_fu_1019_p3 ^ 1'd1);

assign rev_fu_765_p2 = (tmp_128_fu_757_p3 ^ 1'd1);

assign row_assign_10_0_0_t_fu_931_p2 = (tmp_69_fu_923_p3 ^ 2'd3);

assign row_assign_10_0_1_t_fu_951_p2 = (tmp_75_fu_943_p3 ^ 2'd3);

assign row_assign_10_0_2_t_fu_971_p2 = (tmp_81_fu_963_p3 ^ 2'd3);

assign src_kernel_win_0_va_23_fu_1268_p3 = ((tmp_41_reg_2781[0:0] === 1'b1) ? tmp_70_fu_1257_p5 : col_buf_0_val_0_0_fu_1173_p3);

assign src_kernel_win_0_va_24_fu_1286_p3 = ((tmp_41_reg_2781[0:0] === 1'b1) ? tmp_76_fu_1275_p5 : col_buf_0_val_1_0_fu_1192_p3);

assign src_kernel_win_0_va_25_fu_1304_p3 = ((tmp_41_reg_2781[0:0] === 1'b1) ? tmp_82_fu_1293_p5 : col_buf_0_val_2_0_fu_1211_p3);

assign src_kernel_win_1_va_23_fu_1460_p3 = ((tmp_41_reg_2781[0:0] === 1'b1) ? tmp_88_fu_1449_p5 : col_buf_1_val_0_0_fu_1365_p3);

assign src_kernel_win_1_va_24_fu_1478_p3 = ((tmp_41_reg_2781[0:0] === 1'b1) ? tmp_89_fu_1467_p5 : col_buf_1_val_1_0_fu_1384_p3);

assign src_kernel_win_1_va_25_fu_1496_p3 = ((tmp_41_reg_2781[0:0] === 1'b1) ? tmp_90_fu_1485_p5 : col_buf_1_val_2_0_fu_1403_p3);

assign src_kernel_win_2_va_26_fu_1634_p3 = ((tmp_41_reg_2781[0:0] === 1'b1) ? tmp_96_fu_1623_p5 : col_buf_2_val_0_0_fu_1548_p3);

assign src_kernel_win_2_va_27_fu_1652_p3 = ((tmp_41_reg_2781[0:0] === 1'b1) ? tmp_97_fu_1641_p5 : col_buf_2_val_1_0_fu_1567_p3);

assign src_kernel_win_2_va_28_fu_1670_p3 = ((tmp_41_reg_2781[0:0] === 1'b1) ? tmp_98_fu_1659_p5 : col_buf_2_val_2_0_fu_1586_p3);

assign t_V_3_cast_fu_977_p1 = t_V_3_reg_644;

assign t_V_cast_fu_685_p1 = t_V_reg_633;

assign tmp31_fu_2157_p2 = (r_V_8_0_1_2_reg_2983 + p_Val2_89_0_1_1_reg_2978);

assign tmp32_cast_fu_2161_p1 = $signed(tmp32_reg_2993);

assign tmp32_fu_1838_p2 = ($signed(r_V_8_0_2_1_fu_1816_p2) + $signed(tmp33_cast_fu_1834_p1));

assign tmp33_cast_fu_1834_p1 = $signed(tmp33_fu_1828_p2);

assign tmp33_fu_1828_p2 = (tmp_472_0_2_2_cast_c_fu_1825_p1 + r_V_8_0_2_fu_1803_p2);

assign tmp34_fu_1844_p2 = (tmp_83_fu_1793_p2 + tmp_151_fu_1789_p1);

assign tmp35_fu_2178_p2 = (tmp_152_reg_2988 + tmp36_reg_3003);

assign tmp36_fu_1850_p2 = (src_kernel_win_0_va_23_reg_2909 + tmp_153_fu_1821_p1);

assign tmp39_fu_2237_p2 = (r_V_8_1_1_2_reg_3013 + p_Val2_89_1_1_1_reg_3008);

assign tmp40_cast_fu_2241_p1 = $signed(tmp40_reg_3023);

assign tmp40_fu_1953_p2 = ($signed(r_V_8_1_2_1_fu_1931_p2) + $signed(tmp41_cast_fu_1949_p1));

assign tmp41_cast_fu_1949_p1 = $signed(tmp41_fu_1943_p2);

assign tmp41_fu_1943_p2 = (tmp_472_1_2_2_cast_c_fu_1940_p1 + r_V_8_1_2_fu_1918_p2);

assign tmp42_fu_1959_p2 = (tmp_91_fu_1908_p2 + tmp_160_fu_1904_p1);

assign tmp43_fu_2258_p2 = (tmp_161_reg_3018 + tmp44_reg_3033);

assign tmp44_fu_1965_p2 = (src_kernel_win_1_va_23_reg_2932 + tmp_162_fu_1936_p1);

assign tmp47_fu_2317_p2 = (r_V_8_2_1_2_reg_3043 + p_Val2_89_2_1_1_reg_3038);

assign tmp48_cast_fu_2321_p1 = $signed(tmp48_reg_3053);

assign tmp48_fu_2068_p2 = ($signed(r_V_8_2_2_1_fu_2046_p2) + $signed(tmp49_cast_fu_2064_p1));

assign tmp49_cast_fu_2064_p1 = $signed(tmp49_fu_2058_p2);

assign tmp49_fu_2058_p2 = (tmp_472_2_2_2_cast_c_fu_2055_p1 + r_V_8_2_2_fu_2033_p2);

assign tmp50_fu_2074_p2 = (tmp_99_fu_2023_p2 + tmp_169_fu_2019_p1);

assign tmp51_fu_2338_p2 = (tmp_170_reg_3048 + tmp52_reg_3063);

assign tmp52_fu_2080_p2 = (src_kernel_win_2_va_26_reg_2955 + tmp_171_fu_2051_p1);

assign tmp_100_fu_2347_p4 = {{p_Val2_s_fu_2324_p2[11:8]}};

assign tmp_127_fu_747_p1 = t_V_reg_633[1:0];

assign tmp_128_fu_757_p3 = tmp_42_fu_751_p2[32'd11];

assign tmp_129_fu_783_p3 = tmp_42_fu_751_p2[32'd11];

assign tmp_130_fu_811_p1 = p_p2_i426_i_fu_797_p3[1:0];

assign tmp_131_fu_821_p3 = p_assign_6_0_1_fu_815_p2[32'd11];

assign tmp_132_fu_829_p3 = p_assign_6_0_1_fu_815_p2[32'd11];

assign tmp_133_fu_837_p1 = t_V_reg_633[1:0];

assign tmp_134_fu_841_p2 = ($signed(2'd2) - $signed(tmp_133_fu_837_p1));

assign tmp_135_fu_847_p1 = p_assign_6_0_1_fu_815_p2[1:0];

assign tmp_136_fu_851_p3 = ((tmp_132_fu_829_p3[0:0] === 1'b1) ? tmp_134_fu_841_p2 : tmp_135_fu_847_p1);

assign tmp_137_fu_865_p3 = p_assign_6_0_2_fu_859_p2[32'd11];

assign tmp_138_fu_873_p3 = p_assign_6_0_2_fu_859_p2[32'd11];

assign tmp_139_fu_881_p1 = t_V_reg_633[1:0];

assign tmp_140_fu_885_p2 = (tmp_139_fu_881_p1 ^ 2'd3);

assign tmp_141_fu_891_p1 = p_assign_6_0_2_fu_859_p2[1:0];

assign tmp_142_fu_895_p3 = ((tmp_138_fu_873_p3[0:0] === 1'b1) ? tmp_140_fu_885_p2 : tmp_141_fu_891_p1);

assign tmp_143_fu_993_p4 = {{t_V_3_reg_644[10:1]}};

assign tmp_144_fu_1019_p3 = ImagLoc_x_fu_1009_p2[32'd11];

assign tmp_145_fu_1045_p3 = ImagLoc_x_fu_1009_p2[32'd11];

assign tmp_146_fu_1099_p1 = x_fu_1091_p3[1:0];

assign tmp_149_fu_1768_p1 = r_V_8_0_1_fu_1759_p2[7:0];

assign tmp_150_fu_1772_p1 = grp_fu_2418_p3[7:0];

assign tmp_151_fu_1789_p1 = r_V_8_0_1_2_fu_1784_p2[7:0];

assign tmp_152_fu_1808_p1 = r_V_8_0_2_fu_1803_p2[7:0];

assign tmp_153_fu_1821_p1 = r_V_8_0_2_1_fu_1816_p2[7:0];

assign tmp_158_fu_1883_p1 = r_V_8_1_1_fu_1874_p2[7:0];

assign tmp_159_fu_1887_p1 = grp_fu_2426_p3[7:0];

assign tmp_160_fu_1904_p1 = r_V_8_1_1_2_fu_1899_p2[7:0];

assign tmp_161_fu_1923_p1 = r_V_8_1_2_fu_1918_p2[7:0];

assign tmp_162_fu_1936_p1 = r_V_8_1_2_1_fu_1931_p2[7:0];

assign tmp_167_fu_1998_p1 = r_V_8_2_1_fu_1989_p2[7:0];

assign tmp_168_fu_2002_p1 = grp_fu_2434_p3[7:0];

assign tmp_169_fu_2019_p1 = r_V_8_2_1_2_fu_2014_p2[7:0];

assign tmp_170_fu_2038_p1 = r_V_8_2_2_fu_2033_p2[7:0];

assign tmp_171_fu_2051_p1 = r_V_8_2_2_1_fu_2046_p2[7:0];

assign tmp_32_fu_655_p2 = (tmp_s_reg_622 + 2'd1);

assign tmp_33_fu_661_p2 = ((tmp_s_reg_622 == 2'd2) ? 1'b1 : 1'b0);

assign tmp_384_0_0_not_fu_707_p2 = (tmp_38_fu_701_p2 ^ 1'd1);

assign tmp_38_fu_701_p2 = ((t_V_reg_633 < 11'd1080) ? 1'b1 : 1'b0);

assign tmp_40_fu_729_p2 = ((t_V_reg_633 == 11'd1) ? 1'b1 : 1'b0);

assign tmp_41_fu_741_p2 = ((t_V_reg_633 > 11'd1080) ? 1'b1 : 1'b0);

assign tmp_428_0_1_fu_735_p2 = ((t_V_reg_633 == 11'd0) ? 1'b1 : 1'b0);

assign tmp_42_fu_751_p2 = ($signed(12'd4095) + $signed(t_V_cast_fu_685_p1));

assign tmp_44_fu_771_p2 = (($signed(tmp_42_fu_751_p2) < $signed(12'd1080)) ? 1'b1 : 1'b0);

assign tmp_46_fu_805_p2 = (($signed(p_p2_i426_i_fu_797_p3) < $signed(12'd1080)) ? 1'b1 : 1'b0);

assign tmp_472_0_1_cast_cas_fu_1764_p1 = r_V_8_0_1_fu_1759_p2;

assign tmp_472_0_2_2_cast_c_fu_1825_p1 = src_kernel_win_0_va_23_reg_2909;

assign tmp_472_1_1_cast_cas_fu_1879_p1 = r_V_8_1_1_fu_1874_p2;

assign tmp_472_1_2_2_cast_c_fu_1940_p1 = src_kernel_win_1_va_23_reg_2932;

assign tmp_472_2_1_cast_cas_fu_1994_p1 = r_V_8_2_1_fu_1989_p2;

assign tmp_472_2_2_2_cast_c_fu_2055_p1 = src_kernel_win_2_va_26_reg_2955;

assign tmp_51_fu_1033_p2 = (($signed(ImagLoc_x_fu_1009_p2) < $signed(12'd1920)) ? 1'b1 : 1'b0);

assign tmp_53_fu_1071_p2 = (($signed(p_p2_i_i_fu_1059_p3) < $signed(12'd1920)) ? 1'b1 : 1'b0);

assign tmp_61_fu_1116_p1 = $unsigned(x_cast_fu_1113_p1);

assign tmp_66_fu_903_p2 = ($signed(2'd2) - $signed(tmp_130_fu_811_p1));

assign tmp_67_fu_909_p3 = ((tmp_46_fu_805_p2[0:0] === 1'b1) ? tmp_130_fu_811_p1 : tmp_66_fu_903_p2);

assign tmp_68_fu_917_p2 = ($signed(2'd3) + $signed(tmp_127_fu_747_p1));

assign tmp_69_fu_923_p3 = ((or_cond_i425_i_fu_777_p2[0:0] === 1'b1) ? tmp_68_fu_917_p2 : tmp_67_fu_909_p3);

assign tmp_74_fu_937_p2 = (tmp_127_fu_747_p1 ^ 2'd2);

assign tmp_75_fu_943_p3 = ((tmp_131_fu_821_p3[0:0] === 1'b1) ? tmp_136_fu_851_p3 : tmp_74_fu_937_p2);

assign tmp_80_fu_957_p2 = (2'd1 + tmp_127_fu_747_p1);

assign tmp_81_fu_963_p3 = ((tmp_137_fu_865_p3[0:0] === 1'b1) ? tmp_142_fu_895_p3 : tmp_80_fu_957_p2);

assign tmp_83_fu_1793_p2 = (tmp_150_fu_1772_p1 + tmp_149_fu_1768_p1);

assign tmp_84_fu_2187_p4 = {{p_Val2_27_fu_2164_p2[11:8]}};

assign tmp_91_fu_1908_p2 = (tmp_159_fu_1887_p1 + tmp_158_fu_1883_p1);

assign tmp_92_fu_2267_p4 = {{p_Val2_29_fu_2244_p2[11:8]}};

assign tmp_99_fu_2023_p2 = (tmp_168_fu_2002_p1 + tmp_167_fu_1998_p1);

assign tmp_fu_713_p4 = {{t_V_reg_633[10:1]}};

assign tmp_i_i1_79_fu_2383_p2 = (overflow_2_fu_2369_p2 | isneg_2_fu_2330_p3);

assign tmp_i_i1_fu_2357_p2 = (isneg_2_fu_2330_p3 ^ 1'd1);

assign tmp_i_i4_fu_2277_p2 = (isneg_1_fu_2250_p3 ^ 1'd1);

assign tmp_i_i8_fu_2303_p2 = (overflow_1_fu_2289_p2 | isneg_1_fu_2250_p3);

assign tmp_i_i_78_fu_2223_p2 = (overflow_fu_2209_p2 | isneg_fu_2170_p3);

assign tmp_i_i_fu_2197_p2 = (isneg_fu_2170_p3 ^ 1'd1);

assign x_cast_fu_1113_p1 = x_reg_2828;

assign x_fu_1091_p3 = ((or_cond_i_i_fu_1039_p2[0:0] === 1'b1) ? ImagLoc_x_cast_fu_1015_p1 : p_p2_i_i_p_assign_2_fu_1083_p3);

always @ (posedge ap_clk) begin
    OP2_V_0_1_2_cast_reg_2729[11:4] <= 8'b00000000;
    OP2_V_0_2_1_cast_reg_2743[10:3] <= 8'b00000000;
end

endmodule //Filter2D
