// ==============================================================
// File generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2018.2
// Copyright (C) 1986-2018 Xilinx, Inc. All Rights Reserved.
// 
// ==============================================================

/***************************** Include Files *********************************/
#include "xblack.h"

/************************** Function Implementation *************************/
#ifndef __linux__
int XBlack_CfgInitialize(XBlack *InstancePtr, XBlack_Config *ConfigPtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(ConfigPtr != NULL);

    InstancePtr->Control_bus_BaseAddress = ConfigPtr->Control_bus_BaseAddress;
    InstancePtr->IsReady = XIL_COMPONENT_IS_READY;

    return XST_SUCCESS;
}
#endif

void XBlack_Start(XBlack *InstancePtr) {
    u32 Data;

    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XBlack_ReadReg(InstancePtr->Control_bus_BaseAddress, XBLACK_CONTROL_BUS_ADDR_AP_CTRL) & 0x80;
    XBlack_WriteReg(InstancePtr->Control_bus_BaseAddress, XBLACK_CONTROL_BUS_ADDR_AP_CTRL, Data | 0x01);
}

u32 XBlack_IsDone(XBlack *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XBlack_ReadReg(InstancePtr->Control_bus_BaseAddress, XBLACK_CONTROL_BUS_ADDR_AP_CTRL);
    return (Data >> 1) & 0x1;
}

u32 XBlack_IsIdle(XBlack *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XBlack_ReadReg(InstancePtr->Control_bus_BaseAddress, XBLACK_CONTROL_BUS_ADDR_AP_CTRL);
    return (Data >> 2) & 0x1;
}

u32 XBlack_IsReady(XBlack *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XBlack_ReadReg(InstancePtr->Control_bus_BaseAddress, XBLACK_CONTROL_BUS_ADDR_AP_CTRL);
    // check ap_start to see if the pcore is ready for next input
    return !(Data & 0x1);
}

void XBlack_EnableAutoRestart(XBlack *InstancePtr) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XBlack_WriteReg(InstancePtr->Control_bus_BaseAddress, XBLACK_CONTROL_BUS_ADDR_AP_CTRL, 0x80);
}

void XBlack_DisableAutoRestart(XBlack *InstancePtr) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XBlack_WriteReg(InstancePtr->Control_bus_BaseAddress, XBLACK_CONTROL_BUS_ADDR_AP_CTRL, 0);
}

void XBlack_InterruptGlobalEnable(XBlack *InstancePtr) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XBlack_WriteReg(InstancePtr->Control_bus_BaseAddress, XBLACK_CONTROL_BUS_ADDR_GIE, 1);
}

void XBlack_InterruptGlobalDisable(XBlack *InstancePtr) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XBlack_WriteReg(InstancePtr->Control_bus_BaseAddress, XBLACK_CONTROL_BUS_ADDR_GIE, 0);
}

void XBlack_InterruptEnable(XBlack *InstancePtr, u32 Mask) {
    u32 Register;

    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Register =  XBlack_ReadReg(InstancePtr->Control_bus_BaseAddress, XBLACK_CONTROL_BUS_ADDR_IER);
    XBlack_WriteReg(InstancePtr->Control_bus_BaseAddress, XBLACK_CONTROL_BUS_ADDR_IER, Register | Mask);
}

void XBlack_InterruptDisable(XBlack *InstancePtr, u32 Mask) {
    u32 Register;

    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Register =  XBlack_ReadReg(InstancePtr->Control_bus_BaseAddress, XBLACK_CONTROL_BUS_ADDR_IER);
    XBlack_WriteReg(InstancePtr->Control_bus_BaseAddress, XBLACK_CONTROL_BUS_ADDR_IER, Register & (~Mask));
}

void XBlack_InterruptClear(XBlack *InstancePtr, u32 Mask) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XBlack_WriteReg(InstancePtr->Control_bus_BaseAddress, XBLACK_CONTROL_BUS_ADDR_ISR, Mask);
}

u32 XBlack_InterruptGetEnabled(XBlack *InstancePtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    return XBlack_ReadReg(InstancePtr->Control_bus_BaseAddress, XBLACK_CONTROL_BUS_ADDR_IER);
}

u32 XBlack_InterruptGetStatus(XBlack *InstancePtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    return XBlack_ReadReg(InstancePtr->Control_bus_BaseAddress, XBLACK_CONTROL_BUS_ADDR_ISR);
}

