webtalk_init -webtalk_dir C:\\Digilent19\\Digilent18\\LinuxBase.sdk\\webtalk
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "2018-12-22 00:31:38" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "SDK v2018.2" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "2018.2" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "amd64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "211454509_0_0_247" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "SDK" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "false" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "5febi4au8l707opdj76i4bjfu4" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "2018.2_17" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "17" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Microsoft Windows 8 or later , 64-bit" -context "user_environment"
webtalk_add_data -client project -key os_release -value "major release  (build 9200)" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "Intel(R) Core(TM) i7-8700K CPU @ 3.70GHz" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "3696 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "17.119 GB" -context "user_environment"
webtalk_register_client -client sdk
webtalk_add_data -client sdk -key uid -value "1545420386666" -context "sdk\\\\hardware/1545420386666"
webtalk_add_data -client sdk -key isZynq -value "true" -context "sdk\\\\hardware/1545420386666"
webtalk_add_data -client sdk -key isZynqMP -value "false" -context "sdk\\\\hardware/1545420386666"
webtalk_add_data -client sdk -key Processors -value "2" -context "sdk\\\\hardware/1545420386666"
webtalk_add_data -client sdk -key VivadoVersion -value "2018.2" -context "sdk\\\\hardware/1545420386666"
webtalk_add_data -client sdk -key Arch -value "zynq" -context "sdk\\\\hardware/1545420386666"
webtalk_add_data -client sdk -key Device -value "7z020" -context "sdk\\\\hardware/1545420386666"
webtalk_add_data -client sdk -key IsHandoff -value "true" -context "sdk\\\\hardware/1545420386666"
webtalk_add_data -client sdk -key os -value "NA" -context "sdk\\\\hardware/1545420386666"
webtalk_add_data -client sdk -key apptemplate -value "NA" -context "sdk\\\\hardware/1545420386666"
webtalk_add_data -client sdk -key RecordType -value "HWCreation" -context "sdk\\\\hardware/1545420386666"
webtalk_add_data -client sdk -key uid -value "NA" -context "sdk\\\\bsp/1545431498525"
webtalk_add_data -client sdk -key RecordType -value "ToolUsage" -context "sdk\\\\bsp/1545431498525"
webtalk_add_data -client sdk -key BootgenCount -value "0" -context "sdk\\\\bsp/1545431498525"
webtalk_add_data -client sdk -key DebugCount -value "32" -context "sdk\\\\bsp/1545431498525"
webtalk_add_data -client sdk -key PerfCount -value "0" -context "sdk\\\\bsp/1545431498525"
webtalk_add_data -client sdk -key FlashCount -value "0" -context "sdk\\\\bsp/1545431498525"
webtalk_add_data -client sdk -key CrossTriggCount -value "0" -context "sdk\\\\bsp/1545431498525"
webtalk_add_data -client sdk -key QemuDebugCount -value "0" -context "sdk\\\\bsp/1545431498525"
webtalk_transmit -clientid 78561375 -regid "211454509_0_0_247" -xml C:\\Digilent19\\Digilent18\\LinuxBase.sdk\\webtalk\\usage_statistics_ext_sdk.xml -html C:\\Digilent19\\Digilent18\\LinuxBase.sdk\\webtalk\\usage_statistics_ext_sdk.html -wdm C:\\Digilent19\\Digilent18\\LinuxBase.sdk\\webtalk\\sdk_webtalk.wdm -intro "<H3>SDK Usage Report</H3><BR>"
webtalk_terminate
